sosy-lab/sv-benchmarks

c/array-examples/README.txt, c/array-examples/relax_true-unreach-call.c, c/array-examples/relax_true-unreach-call.i, c/heap-manipulation/README.txt, c/heap-manipulation/dancing_true-unreach-call.c, c/heap-manipulation/dancing_true-unreach-call.i, c/pthread-atomic/README.txt, c/pthread-atomic/gcd_true-unreach-call_true-termination.c, c/pthread-atomic/gcd_true-unreach-call_true-termination.i
Hi,
I am aware this might be too late for this year's SV-COMP, but just in case it isn't: I had previously sent these examples via email. I decided to put them into the various folders that had the most suitable context, rather than creating a new "verifythis" folder and then amending various *.set files.
Best,
Michael
=> CBMC's solutions for VerifyThis 2015

c/Concurrency.set, c/DeviceDrivers64.set, c/ldv-linux-3.16-rc1/43_2a_bitvector_linux-3.16-rc1.tar.xz-43_2a-drivers--usb--host--max3421-hcd.ko-entry_point_false-unreach-call.cil.out.c
Add 
ldv-races to Concurrency  
linux-4.2-rc1 and validator-v0.8 to DeviceDrivers64
=> Add ldv- benchmarks to the corresponding category sets

.travis.yml, README.md, c/Makefile.rules
Doesn't succeed yet due to problematic benchmarks other PRs ( #49 #47 #46 #45 #43) fix this enough so that the syntax check succeeds with gcc.
=> TravisCI support

c/array-examples/sorting_selectionsort_false-unreach-call_ground.c, c/array-examples/sorting_selectionsort_false-unreach-call_ground.i, c/array-examples/sorting_selectionsort_true-unreach-call_ground.c, c/array-examples/sorting_selectionsort_true-unreach-call_ground.i
Fixed sorting_selectionsort_true-unreach-call_ground.* in
array-examples.
=> Fixed incorrect true-unreach-call files

c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--char--ramoops.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--mtd--devices--doc2001plus.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/43_1a_cilled_true-unreach-call_ok_nondet_linux-43_1a-drivers--mtd--devices--doc2001plus.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c
clang reports a problem for those
=> Removed illegal inline assembly instructions

c/ldv-memsafety/memleaks-notpreprocessed/memleaks_test17_2_true-valid-memsafety.c, c/ldv-memsafety/memleaks-notpreprocessed/memleaks_test5_2_false-valid-memtrack.c, c/ldv-memsafety/memleaks_test17_2_true-valid-memsafety.i, c/ldv-memsafety/memleaks_test5_2_false-valid-memtrack.i
Fix overflow and undefined behaviour
=> Fix ldv benchmarks

c/array-examples/standard_copyInitSum_true-unreach-call_ground.i, c/ldv-consumption/32_7a_cilled_true-unreach-call_linux-3.8-rc1-32_7a-drivers--media--v4l2-core--videobuf-dma-contig.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/loops/s3_false-unreach-call.i, c/seq-pthread/cs_dekker_true-unreach-call.i, c/seq-pthread/cs_fib_longer_true-unreach-call.i, c/seq-pthread/cs_fib_true-unreach-call.i, c/seq-pthread/cs_lamport_true-unreach-call.i, c/seq-pthread/cs_peterson_true-unreach-call.i, c/seq-pthread/cs_queue_true-unreach-call.i, c/seq-pthread/cs_read_write_lock_true-unreach-call.i, c/seq-pthread/cs_stack_true-unreach-call.i, c/seq-pthread/cs_stateful_true-unreach-call.i, c/seq-pthread/cs_sync_true-unreach-call.i, c/seq-pthread/cs_szymanski_true-unreach-call.i, c/seq-pthread/cs_time_var_mutex_true-unreach-call.i
This pull request contains several fixes related to getting rid of undefined behaviors.
=> Getting rid of undefined behaviors

c/loop-lit/bhmr2007_true-unreach-call.c, c/loop-lit/bhmr2007_true-unreach-call.c.i, c/loop-lit/gcnr2008_false-unreach-call.c, c/loop-lit/gcnr2008_false-unreach-call.c.i, c/loop-lit/hhk2008_true-unreach-call.c, c/loop-lit/hhk2008_true-unreach-call.c.i
assert is a no-op.
Changed to __VERIFIER_assert.
=> Fixed "assert" statement.

c/seq-pthread/cs_queue_true-unreach-call.i
Initializing the structure with nondet values field-by-field.
=> Appropriately initializing QType structure with nondet values

c/ArraysReach.set
Correction to `commit 220339e593f1c54e331a334b4df14d7483c8a1d2`
=> Add files in reducercommutativity to ArraysReach.set

c/Makefile
@dbeyer Your recent commit broken the build.
=> Fix build broken by 7816af8a3d5db6ed190239a9e997ab6de07b8f77

c/loop-invgen/SpamAssassin-loop_true-unreach-call.c, c/loop-invgen/SpamAssassin-loop_true-unreach-call.i, c/loop-lit/cggmp2005_variant_true-unreach-call.c, c/loop-lit/cggmp2005_variant_true-unreach-call.c.i, c/loop-new/half_true-unreach-call.c, c/loop-new/half_true-unreach-call.i, c/loops/sum01_true-unreach-call_true-termination.c, c/loops/sum01_true-unreach-call_true-termination.i, c/loops/trex04_true-unreach-call_false-termination.c, c/loops/trex04_true-unreach-call_false-termination.i
Hi, 
so 10 was an over-estimate, but there are 5 bugs left indeed.
Sorry for large change, I had to change the indentation as the file was unreadable otherwise.
=> Fixing more "Loops" benchmarks with UB

.travis.yml, c/Makefile-README.md, c/Makefile.config, c/Makefile.rules
the warnings that were supposed to be treated as errors were not
passed. Also refactor a little bit and add the current value of
CC.Warnings and CC.WarningsAsErrors to the output of ``make debug_vars``
=> Fix bug in Makefile.rules where if ``SUPPRESS_WARNINGS=1`` then

c/ldv-linux-3.0/usb_urb-drivers-usb-serial-whiteheat.ko_true-unreach-call.cil.out.i.pp.i, c/loops/trex04_true-unreach-call_false-termination.c, c/loops/trex04_true-unreach-call_false-termination.i
@dbeyer The commits you merged recently were failing the build and probably shouldn't have been merged without the authors (@mutilin @cheshire) fixing them first. This PR fixes the problems that have been introduced so that the build should pass again.
=> Fix recently broken build

c/floats-esbmc-regression/ceil_nondet_true-unreach-call.c, c/floats-esbmc-regression/ceil_nondet_true-unreach-call.i, c/floats-esbmc-regression/floor_nondet_true-unreach-call.c, c/floats-esbmc-regression/floor_nondet_true-unreach-call.i, c/floats-esbmc-regression/round_nondet_true-unreach-call.c, c/floats-esbmc-regression/round_nondet_true-unreach-call.i, c/floats-esbmc-regression/trunc_nondet_2_true-unreach-call.c, c/floats-esbmc-regression/trunc_nondet_2_true-unreach-call.i, c/floats-esbmc-regression/trunc_nondet_true-unreach-call.c, c/floats-esbmc-regression/trunc_nondet_true-unreach-call.i
=> Fix uninitialized in float benchmarks

c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--ethernet--natsemi--ns83820.ko-entry_point_true-unreach-call.cil.out.c
=> Deactivate timers, which are not initialized

c/loop-acceleration/array_false-unreach-call3_true-termination.c, c/loop-acceleration/array_false-unreach-call3_true-termination.i
=> Fixed undefined behavior by initializing array A

c/heap-manipulation/tree_false-unreach-call.c, c/heap-manipulation/tree_true-unreach-call.c, c/heap-manipulation/tree_true-unreach-call.i
=> Removing definition of __VERIFIER_nondet_int

c/loop-industry-pattern/mod3_true-unreach-call.c
As per svcomp guidelines replaced user-definened nondet_int to __VERIFIER_nondet_int().
=> Update as per svcomp guidelines.

c/ldv-memsafety-bitfields/test-bitfields-1_false-valid-deref.c, c/ldv-memsafety-bitfields/test-bitfields-1_false-valid-deref.i, c/ldv-memsafety-bitfields/test-bitfields-1_true-valid-memsafety.c, c/ldv-memsafety-bitfields/test-bitfields-1_true-valid-memsafety.i, c/ldv-memsafety-bitfields/test-bitfields-2.1_false-valid-free.c, c/ldv-memsafety-bitfields/test-bitfields-2.1_false-valid-free.i, c/ldv-memsafety-bitfields/test-bitfields-2.1_true-valid-memsafety.c, c/ldv-memsafety-bitfields/test-bitfields-2.1_true-valid-memsafety.i, c/ldv-memsafety-bitfields/test-bitfields-2_false-valid-deref.c, c/ldv-memsafety-bitfields/test-bitfields-2_false-valid-deref.i, c/ldv-memsafety-bitfields/test-bitfields-2_true-valid-memsafety.c, c/ldv-memsafety-bitfields/test-bitfields-2_true-valid-memsafety.i, c/ldv-memsafety-bitfields/test-bitfields-3.1_false-valid-deref.c, c/ldv-memsafety-bitfields/test-bitfields-3.1_false-valid-deref.i, c/ldv-memsafety-bitfields/test-bitfields-3.1_true-valid-memsafety.c, c/ldv-memsafety-bitfields/test-bitfields-3.1_true-valid-memsafety.i, c/ldv-memsafety-bitfields/test-bitfields-3_false-valid-deref.c, c/ldv-memsafety-bitfields/test-bitfields-3_false-valid-deref.i, c/ldv-memsafety-bitfields/test-bitfields-3_true-valid-memsafety.c, c/ldv-memsafety-bitfields/test-bitfields-3_true-valid-memsafety.i
=> Added packed attribute to structures with bitfields

c/ldv-memsafety-bitfields/README.txt, c/ldv-memsafety-bitfields/test-bitfields-2.1_false-valid-free.c, c/ldv-memsafety-bitfields/test-bitfields-2.1_false-valid-free.i, c/ldv-memsafety-bitfields/test-bitfields-2.1_true-valid-memsafety.c, c/ldv-memsafety-bitfields/test-bitfields-2.1_true-valid-memsafety.i, c/ldv-memsafety-bitfields/test-bitfields-2_false-valid-deref.c, c/ldv-memsafety-bitfields/test-bitfields-2_false-valid-deref.i, c/ldv-memsafety-bitfields/test-bitfields-2_true-valid-memsafety.c, c/ldv-memsafety-bitfields/test-bitfields-2_true-valid-memsafety.i, c/ldv-memsafety-bitfields/test-bitfields-3.1_false-valid-deref.c, c/ldv-memsafety-bitfields/test-bitfields-3.1_false-valid-deref.i, c/ldv-memsafety-bitfields/test-bitfields-3.1_true-valid-memsafety.c, c/ldv-memsafety-bitfields/test-bitfields-3.1_true-valid-memsafety.i, c/ldv-memsafety-bitfields/test-bitfields-3_false-valid-deref.c, c/ldv-memsafety-bitfields/test-bitfields-3_false-valid-deref.i, c/ldv-memsafety-bitfields/test-bitfields-3_true-valid-memsafety.c, c/ldv-memsafety-bitfields/test-bitfields-3_true-valid-memsafety.i
=> Bitfields alignment

c/pthread-lit/qw2004_true-unreach-call.c, c/pthread-lit/qw2004_variant_true-unreach-call.c
=> Fix misplaced __VERIFIER_atomic_end()

c/ldv-regression/test22_false-unreach-call.c
Signed-off-by: Mikhail Ramalho <mikhail.ramalho@gmail.com>
=> Fix underflow on ldv-regression/test22_false-unreach-call.c

c/array-examples/sanfoundry_24_false-valid-deref.c, c/array-examples/sanfoundry_24_false-valid-deref.i
Local variable num was used without being initialized first.
I am initializing it now to nondet value.
=> Fixed undefined behavior

c/seq-pthread/cs_fib_false-unreach-call.c, c/seq-pthread/cs_fib_longer_false-unreach-call.c, c/seq-pthread/cs_queue_false-unreach-call.c, c/seq-pthread/cs_read_write_lock_false-unreach-call.c, c/seq-pthread/cs_stack_false-unreach-call.c, c/seq-pthread/cs_stateful_false-unreach-call.c
modify even the C files, so that they match the .i files
=> fix the PR #324

c/bitvector/gcd_1_true-unreach-call_true-no-overflow.i, c/bitvector/gcd_2_true-unreach-call_true-no-overflow.i, c/bitvector/gcd_3_true-unreach-call_true-no-overflow.i, c/bitvector/modulus_false-no-overflow.c, c/bitvector/modulus_false-no-overflow.i
=> Fixes for bitvectors benchmarks

c/MemSafety-LinkedLists.set, c/heap-manipulation/tree_false-valid-deref.c, c/heap-manipulation/tree_false-valid-deref.i, c/heap-manipulation/tree_true-unreach-call_true-valid-memsafety.c, c/heap-manipulation/tree_true-unreach-call_true-valid-memsafety.i
Fix for #335
@dbeyer: I have a simple question. Should I add the original file back? If so, what should be the proper name for it?
=> Fix null pointer deference in heap-manipulation/tree_true-unreach-call_true-valid-memsafety.*

c/list-ext-properties/simple-ext_false-unreach-call_true-valid-memsafety.c, c/list-ext-properties/simple-ext_false-unreach-call_true-valid-memsafety.i, c/list-properties/list_search_false-unreach-call_true-valid-memsafety.c, c/list-properties/list_search_false-unreach-call_true-valid-memsafety.i
Fix the memory leaks on the program changed by PR #367.
Signed-off-by: Mikhail Ramalho <mikhail.ramalho@gmail.com>
=> Fix memory leak on benchmarks

c/termination-memory-linkedlists/cll_search-alloca_true-termination.c, c/termination-memory-linkedlists/cll_search-alloca_true-termination.c.i, c/termination-memory-linkedlists/nondet_ll_search-alloca_true-termination.c, c/termination-memory-linkedlists/nondet_ll_search-alloca_true-termination.c.i
Changes we already contained in PR #319 submitted by @letonchanh  (which was not
merged because I accidentally incorrectly claimed that all this changes
are a subset of my PR #425)
=>     Fix "modulo by zero" in termination-memory-linkedlists

c/busybox-1.22.0/busybox_sv_comp-stpcpy.h, c/busybox-1.22.0/echo_true-no-overflow_true-valid-memsafety.i
=> busybox echo: fix stpcpy function

.github/PULL_REQUEST_TEMPLATE, CONTRIBUTING.md, README.md
- Move checklist for PRs to a [PR template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)
that GitHub will insert automatically in the description field for new PRs.
- Document everything that submitters should read in new file [CONTRIBUTING.md](https://help.github.com/articles/setting-guidelines-for-repository-contributors/),
for which GitHub will automatically show a link when creating a new issue or PR.
- Remove content that is now in CONTRIBUTING.md from README.md.
Fixes #167.
=> Update documentation on how to submit verification tasks

README.md, c/PropertyMemCleanup.prp
Fixes #471 and several other issues.
=> Added missing property 'memcleanup'

.travis.yml
Speed up build with GCC by using CCache.
Please do **not** merge until evaluation is completed.
=> Update travis.yml (for testing)

c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--input--joystick--spaceball.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--input--joystick--stinger.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--input--keyboard--xtkbd.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--input--misc--atlas_btns.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3_false-termination.4-32_1-drivers--input--misc--pcap_keys.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3_false-termination.4-32_1-drivers--input--misc--pcspkr.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3_true-termination.4-32_1-drivers--input--touchscreen--mk712.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3_true-termination.4-32_1-drivers--platform--x86--dell-wmi-aio.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/43_1a_cilled_true-unreach-call_ok_nondet_linux-43_1a-drivers--input--joystick--spaceball.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/43_1a_cilled_true-unreach-call_ok_nondet_linux-43_1a-drivers--input--joystick--stinger.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/43_1a_cilled_true-unreach-call_ok_nondet_linux-43_1a-drivers--input--keyboard--xtkbd.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/43_1a_cilled_true-unreach-call_ok_nondet_linux-43_1a-drivers--input--misc--atlas_btns.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/43_1a_cilled_true-unreach-call_ok_nondet_linux-43_1a-drivers--input--misc--pcap_keys_false-termination.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/43_1a_cilled_true-unreach-call_ok_nondet_linux-43_1a-drivers--input--misc--pcspkr_false-termination.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/43_1a_cilled_true-unreach-call_ok_nondet_linux-43_1a-drivers--input--touchscreen--mk712_true-termination.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/43_1a_cilled_true-unreach-call_ok_nondet_linux-43_1a-drivers--platform--x86--dell-wmi-aio_true-termination.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/43_1a_cilled_true-unreach-call_ok_nondet_linux-43_1a-drivers--platform--x86--topstar-laptop.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--staging--speakup--speakup.ko-entry_point_true-unreach-call.cil.out.c, c/list-ext-properties/simple-ext_1_true-valid-memsafety.c, c/list-ext-properties/simple-ext_false-unreach-call_false-valid-memcleanup_true-termination.c, c/pthread-lit/fk2012_true-unreach-call.c
=> Fix declarations

c/reducercommutativity/rangesum05_false-unreach-call.yml
This change reflects the discussed adjustments to the syntax of the task-definition files.
=> Task Definition: Slight syntax change according to discussion about implementation

c/MemSafety-Concurrency.cfg, c/MemSafety-Concurrency.set, c/MemSafety-Other.set
SVCOMP19 does not yet allow more categories.
New files must be added to an existing category.
=> move files from one set-file to another one.

c/array-memsafety-realloc/array-realloc_true-valid-memsafety.c, c/array-memsafety-realloc/array-realloc_true-valid-memsafety.i
This fixes two problems:
- wrong signature of method.
- double free.
See #610 for discussion.
=> remove freeing of pointer.

java/jayhorn-recursive/Addition_true-assert/src/main/java/Main.java
The program should be formulated in such a way that it is correct regardless of the Random.nextInt semantics
=> Fixed Java benchmark

c/array-multidimensional/diff-2-n-u_true-unreach-call.c, c/array-multidimensional/diff-2-n-u_true-unreach-call.i, c/array-multidimensional/diff-3-n-u_true-unreach-call.c, c/array-multidimensional/diff-3-n-u_true-unreach-call.i, c/array-multidimensional/init-non-constant-2-n-u_true-unreach-call.c, c/array-multidimensional/init-non-constant-2-n-u_true-unreach-call.i, c/array-multidimensional/init-non-constant-3-u_true-unreach-call.c, c/array-multidimensional/init-non-constant-3-u_true-unreach-call.i
=> fix unintentional overflows by using unsigned int.

c/list-ext3-properties/sll_shallow_copy_false-valid-memtrack.c, c/list-ext3-properties/sll_shallow_copy_false-valid-memtrack.i
=> Fixed unwanted invalid free

c/array-multidimensional/add-2-n-u_true-unreach-call.c, c/array-multidimensional/add-2-n-u_true-unreach-call.i, c/array-multidimensional/add-3-n-u_true-unreach-call.c, c/array-multidimensional/add-3-n-u_true-unreach-call.i
It should be unsigned int and not just int.
=> Fixed wrong signature of nondet_uint

java/jbmc-regression/bitwise1/Main.java
=> Fix bitwise1

java/jpf-regression/ExSymExeD2I_true/Main.java, java/jpf-regression/ExSymExeD2L_true/Main.java, java/jpf-regression/ExSymExeF2I_true/Main.java, java/jpf-regression/ExSymExeF2L_true/Main.java
Fixes consistencies introduced in f9eb01e
See commit message body for details
=> Fix jpf-regression benchmarks

java/jbmc-regression/arraylength1/Main.java
Fixes bug introduced in f9eb01e
See commit message body for details
=> Fix arraylength1

java/jbmc-regression/charArray/Main.java
Fixes bug introduced in f9eb01e
See commit message body for details
=> Fix charArray

c/pthread-nondet/nondet-array_true-unreach-call.c, c/pthread-nondet/nondet-array_true-unreach-call.i
Note: there is no need to keep the originals, as an unsafe version of the programs is already in the repository.
=> Avoid reachable assertion failure (combined .i and .c file)

c/loops/veris.c_OpenSER__cases1_stripFullBoth_arr_true-unreach-call_true-termination.c, c/loops/veris.c_OpenSER__cases1_stripFullBoth_arr_true-unreach-call_true-termination.i, c/loops/verisec_OpenSER__cases1_stripFullBoth_arr_false-unreach-call_true-termination.c, c/loops/verisec_OpenSER__cases1_stripFullBoth_arr_false-unreach-call_true-termination.i
=> see #613: fix remaining issues in loops

c/ddv-machzwd/ddv_machzwd_all_false-unreach-call_true-valid-memsafety.i, c/ddv-machzwd/ddv_machzwd_inb_p_true-unreach-call_false-valid-memtrack.i, c/ddv-machzwd/ddv_machzwd_inb_true-unreach-call_false-valid-memtrack.i, c/ddv-machzwd/ddv_machzwd_inl_p_true-unreach-call_false-valid-memtrack.i, c/ddv-machzwd/ddv_machzwd_inl_true-unreach-call_false-valid-memtrack.i, c/ddv-machzwd/ddv_machzwd_inw_false-unreach-call_true-valid-memsafety.i, c/ddv-machzwd/ddv_machzwd_inw_p_true-unreach-call_false-valid-memtrack.i, c/ddv-machzwd/ddv_machzwd_outb_false-unreach-call_true-valid-memsafety.i, c/ddv-machzwd/ddv_machzwd_outb_p_true-unreach-call_false-valid-memtrack.i, c/ddv-machzwd/ddv_machzwd_outl_p_true-unreach-call_false-valid-memtrack.i, c/ddv-machzwd/ddv_machzwd_outl_true-unreach-call_false-valid-memtrack.i, c/ddv-machzwd/ddv_machzwd_outw_p_true-unreach-call_false-valid-memtrack.i, c/ddv-machzwd/ddv_machzwd_pthread_mutex_unlock_true-unreach-call_false-valid-memtrack.i
Remove unused functions from source code as discussed with @dbeyer via e-mail.
=> ddv_machzwd: remove unused functions

c/heap-data/hash_fun_true-unreach-call.c, c/heap-data/hash_fun_true-unreach-call.i, c/heap-data/packet_filter_true-unreach-call.c, c/heap-data/packet_filter_true-unreach-call.i, c/heap-data/process_queue_true-unreach-call.c, c/heap-data/process_queue_true-unreach-call.i
As per #613, some simple fixes. 
If the commit-flood is a problem, I can try rebasing later during Friday.
=> Fix heap-data/ undefined functions

c/eca-rers2018/Problem10.yml, c/eca-rers2018/Problem11.yml, c/eca-rers2018/Problem12.yml, c/eca-rers2018/Problem13.yml, c/eca-rers2018/Problem14.yml, c/eca-rers2018/Problem15.yml, c/eca-rers2018/Problem16.yml, c/eca-rers2018/Problem17.yml, c/eca-rers2018/Problem18.yml, c/eca-rers2018/createYml.py
see https://github.com/sosy-lab/sv-benchmarks/pull/768#issuecomment-457942890
=> fix filename in yaml-files.

c/array-crafted/zero_sum_const1.c, c/array-crafted/zero_sum_const2.c, c/array-crafted/zero_sum_const3.c, c/array-crafted/zero_sum_const4.c, c/array-crafted/zero_sum_const5.c, c/array-crafted/zero_sum_const_m2.c, c/array-crafted/zero_sum_const_m3.c, c/array-crafted/zero_sum_const_m4.c, c/array-crafted/zero_sum_const_m5.c, c/array-tiling/mlceu.c, c/array-tiling/pnr2.c, c/array-tiling/pnr3.c, c/array-tiling/pnr4.c, c/array-tiling/pnr5.c, c/array-tiling/poly1.c, c/array-tiling/poly2.c, c/array-tiling/revcpyswp2.c, c/array-tiling/rew.c, c/array-tiling/rewnif.c, c/array-tiling/rewnifrev.c, c/array-tiling/rewnifrev2.c, c/array-tiling/rewrev.c, c/array-tiling/skipped.c, c/array-tiling/skippedu.c, c/array-tiling/tcpy.c, c/loops/linear_sea.ch.c, c/loops/linear_search.c
This PR tries to quickly fix #787 since @ccadar is travelling.
=> Transformed VLA allocation into heap allocation and bounded the allocation size

c/recursive-with-pointer/simple-recursive.c
=> fix invalid pointer increment.

c/array-memsafety-realloc/array-realloc-3.c, c/array-memsafety-realloc/array-realloc-3.i, c/array-memsafety-realloc/array-realloc-3.yml
There is a memory leak in the `expandArray` function and double free in `main` (`valid-memtrack` and `valid-free` are violated). My edits seem too artificial. 
@kfriedberger You added these benchmarks. What do you suggest?
=> Fix file with multiple errors in array-memsafety-realloc

c/array-memsafety/openbsd_cmemchr-alloca-2.c, c/array-memsafety/openbsd_cmemchr-alloca-2.i
wrong variable used in for loop (n=/=length)
=> Fix wrong size of array in array-memsafety

c/array-memsafety/lis_unsafe.c, c/array-memsafety/lis_unsafe.i
=> array-memsafety/lis_unsafe.c: missing array size limit

c/seq-mthreaded/rekcba_aso.2.M1-1.yml, c/seq-mthreaded/rekh_aso.2.M1-1.yml, c/seq-mthreaded/rekh_aso.3.M1.yml
We've been reporting bug in these benchmarks for years but the counterexamples are massive and hard to debug (~1500 assignments).
Now, we found another tool that also produces counterexample for these tasks (CBMC). The witnesses are available at issue #849.
=> Change verdict of buggy programs. Issue #849

java/algorithms/Tsp-FunSat01.yml
We found a counter example for the algorithms/Tsp-FunSat01 task.
Running the corresponding Main.java file with the following seeded Verifier instance leads to an assertion violation. Therefore, we think that the corresponding label should be changed.
```
import java.util.Random;
public final class Verifier
{
private static int count = 0;
// [INFO] /* java.lang.Integer:_int0= */1,
// [INFO] /* java.lang.Integer:_int0= */5,
private static int[] vals = new int[] {
/* java.lang.Integer:_int0= */3,
/* java.lang.Integer:_int1= */2147483647,
/* java.lang.Integer:_int2= */2139103271,
/* java.lang.Integer:_int3= */0,
/* java.lang.Integer:_int4= */0,
/* java.lang.Integer:_int5= */0,
/* java.lang.Integer:_int6= */692084728,
/* java.lang.Integer:_int7= */1447035718,
/* java.lang.Integer:_int8= */0, …
```
=> Update the expected verdict for algorithms/Tsp-FunSat01

java/algorithms/BellmanFord-FunSat02.yml
We found a counter example for the algorithms/BellmanFord-FunSat02 task.
Running the corresponding Main.java file with the following seeded Verifier instance leads to an assertion violation. Therefore, we think that the corresponding label should be changed.
```
import java.util.Random;
public final class Verifier
{
private static int count = 0;
// [INFO] /* java.lang.Integer:_int0= */1, 
// [INFO] /* java.lang.Integer:_int0= */5, 
private static int[] vals = new int[] {
/* java.lang.Integer:_int0= */5, 
/* java.lang.Integer:_int1= */5, 
/* java.lang.Integer:_int2= */3, 
/* java.lang.Integer:_int3= */4, 
/* java.lang.Integer:_int4= */66, 
/* java.lang.Integer:_int5= */7712, 
/* java.lang.Integer:_int6= */3, 
/* java.lang.Integer:_int7= */8187, 
/* java.lang.Integer:_int8= */538171, 
/* …
```
=> Update the expected verdict for algorithms/BellmanFord-FunSat02

java/algorithms/BellmanFord-FunSat01.yml
We found a counter example for the algorithms/BellmanFord-FunSat01 task.
Running the corresponding Main.java file with the following seeded Verifier instance leads to an assertion violation. Therefore, we think that the corresponding label should be changed.
```
import java.util.Random;
public final class Verifier
{
private static int count = 0;
// [INFO] /* /* java.lang.Integer:_int0= */ */1, 
// [INFO] /* /* java.lang.Integer:_int0= */ */5, 
private static int[] vals = new int[] {
/* java.lang.Integer:_int0= */5, 
/* java.lang.Integer:_int1= */3, 
/* java.lang.Integer:_int2= */3, 
/* java.lang.Integer:_int3= */2, 
/* java.lang.Integer:_int4= */32766, 
/* java.lang.Integer:_int5= */0, 
/* java.lang.Integer:_int6= */61, 
/* java.lang.Integer:_int7= */62, 
/* java.lang.Integer:_int8= …
```
=> Update the expected verdict for algorithms/BellmanFord-FunSat01

c/SoftwareSystems-DeviceDriversLinux64Large-ReachSafety.cfg, c/SoftwareSystems-DeviceDriversLinux64Large-ReachSafety.set, c/compare.py
Adding extra category to honor verification of large verification tasks, partially addresses issue #819.
=> Adding sub-category of large verification tasks

java/algorithms/Trie-MemUnsat01/Main.java
This program passes deterministically despite the bug (just execute to verify - the only nondeterministic input has no influence in reaching the offending statement).
@zafer-esen, please check that this is correct and my changes are as intended.
=> Add assertion to detect the expected bug

c/eca-programs/README.txt
This PR extends the README in the directory.
=> Update eca-programs readme

java/compile.xml
This should close #1017, once CI passes.
=> Add java ranger directories to compile.xml

.gitlab-ci.yml, .travis.yml, c/.Dockerfile.clang-3.9, c/.Dockerfile.gcc-5, c/.Dockerfile.preprocessing-consistency, c/compare.py, c/diff_ci.sh
Pull request changing the ci build:
1. For branches the build will be performed on the folders which have diff to master 
2. for master branch the complete build will be done
=> CI build on diff

c/loops-crafted-1/iftelse.c, c/loops-crafted-1/sum_by_3.c, c/loops-crafted-1/sumt2.c, c/loops-crafted-1/sumt3.c, c/loops-crafted-1/sumt4.c, c/loops-crafted-1/vnew1.c, c/loops-crafted-1/vnew2.c
Removed conflicting declarations.
=> Fix declaration of __VERIFIER_nondet_int()

c/list-ext-properties/list-ext_2.yml
This PR is a fix for the previously closed #1083 .
Somehow I forgot to update the yml file and nobody noticed it :-)
=> fix yml task definition.

get_tasks_for_property.sh
Two different tools with that name exist. We use https://pypi.org/project/yq/
=> Disambiguate tool 'yq'

README.md
Addresses documentation requirements from issue #1110.
=> Document the new version of the SV-COMP task-definition format

c/check.py, c/ldv-races/race-1_2-join.yml, c/ldv-races/race-1_2b-join.c, c/ldv-races/race-1_2b-join.i, c/ldv-races/race-1_2b-join.yml, c/ldv-races/race-1_3-join.c, c/ldv-races/race-1_3-join.i, c/ldv-races/race-1_3-join.yml, c/ldv-races/race-1_3b-join.c, c/ldv-races/race-1_3b-join.i, c/ldv-races/race-1_3b-join.yml, c/properties/no-data-race.prp
Data races are undefined behavior. A property to check for those
would be useful in my opinion, so this commit/PR also proposes
such a property.
=> Fix some data races and add no-data-race property

c/diff_ci.sh
=>  fix diff_ci

.github/PULL_REQUEST_TEMPLATE
This PR tries to clarify what 'original' means for the requirement that original sources must be present in PRs for new verification and test tasks.
- Ideally, we would like to maintain the original source code, even though some competitions actually use the preprocessed source code to hand to tools as input.
- Original means "as programmed".
- Sometimes, we cannot get the original programs, e.g., if the code is generated for a certain machine architecture by a system that can only produce preprocessed source code.
- Some historic code is perhaps not available in its original form.
=> PR Template: Clarify what 'original sources' means

c/properties/coverage-error-call.prp
Changes the test specifications to `reach_error` as well.
=> Adapted specification to rule changes

c/loop-acceleration/array_2-1-simple.c, c/loop-acceleration/array_2-1-simple.i, c/loop-acceleration/array_2-1-simple.yml, c/loop-acceleration/array_2-1.c, c/loop-acceleration/array_2-1.i, c/loop-acceleration/array_2-2-simple.c, c/loop-acceleration/array_2-2-simple.i, c/loop-acceleration/array_2-2-simple.yml, c/loop-acceleration/array_2-2.c, c/loop-acceleration/array_2-2.i
The loop access uninitialised memory thus resulting in undefined behaviour.
This RP initialised to zero (the value is irrelevant for the verification) all the elements in the array
=> removed UB

c/MemSafety-Arrays.set, c/MemSafety-Other.set, c/MemSafety-TerminCrafted.set
Since architecture is no longer a problem, I'm reopening #882.
=> change MemSafety sub-categories #841

c/ldv-races/race-2_3-container_of.c, c/ldv-races/race-2_3-container_of.i, c/pthread-ext/18_read_write_lock.c, c/pthread-ext/18_read_write_lock.i
This PR solves data races in two benchmarks by wrapping the racing accesses with __VERIFIER_atomic blocks.
=> Solved data races

c/ldv-races/race-2_4-container_of.c, c/ldv-races/race-2_4-container_of.i
Similar problem / solution as in #1218.
=> Yet another data race

c/seq-mthreaded/pals_floodmax.3.3.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_floodmax.3_overflow.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_lcr.3_overflow.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_lcr.4_overflow.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_lcr.5_overflow.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_opt-floodmax.3.2.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_opt-floodmax.3.3.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_opt-floodmax.3_overflow.ufo.UNBOUNDED.pals.yml
=> seq-mthreaded: fix termination lablel at several benchmraks

.reuse/dep5, LICENSES/BSD-2-Clause-Attribution.txt, LICENSES/BSD-2-Clause.txt, java/rtems-lock-model/lock-00-01-10/Main.java, java/rtems-lock-model/lock-00-01-10/base/Condition.java, java/rtems-lock-model/lock-00-01-10/base/Lock.java, java/rtems-lock-model/lock-00-01-10/base/PrioLock.java, java/rtems-lock-model/lock-00-01-10/harness/Environment.java, java/rtems-lock-model/lock-00-01-10/harness/TestThread.java, java/rtems-lock-model/lock-00-01-10/rtems/Mutex.java, java/rtems-lock-model/lock-00-01-10/rtems/OrderList.java, java/rtems-lock-model/lock-00-01-10/rtems/RTEMSThread.java, java/rtems-lock-model/lock-00-01-10/rtems/WaitQueue.java
=> Added BSD 2-clause license to licenses, REUSE spec to each Java file.

c/busybox-1.22.0/cut-2.yml, c/busybox-1.22.0/cut-3.c, c/busybox-1.22.0/cut-3.i, c/busybox-1.22.0/cut-3.yml, c/busybox-1.22.0/od-1.yml, c/busybox-1.22.0/od-3.c, c/busybox-1.22.0/od-3.i, c/busybox-1.22.0/od-3.yml
Fix labeling of two busybox benchmarks, see #1275 .
=> Busybox memsafety fixes
