sosy-lab/sv-benchmarks

c/ldv-linux-3.4-simple/43_1a_cilled_false-unreach-call_ok_linux-43_1a-drivers--scsi--megaraid--megaraid_mm.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c
Initialize global static variable. In the current state, the benchmark is not marked correctly.
=> fix global initialization

c/pthread-atomic/qrcu_false-unreach-call.c, c/pthread-atomic/qrcu_false-unreach-call.i, c/pthread-atomic/scull_true-unreach-call.c, c/pthread-atomic/scull_true-unreach-call.i, c/pthread/sigma_false-unreach-call.c, c/pthread/sigma_false-unreach-call.i
fixes for some undefined behaviors for pthread examples, including uninitialized variables, function definitions of thread routines missing parameter list, array index out-of-bound.
=> fixes for some undefined behaviors for pthread examples

c/loop-invgen/id_build_true-unreach-call.i, c/loop-invgen/sendmail-close-angle_true-unreach-call.i
In a couple of benchmarks in the loops category there are some uninitialized variables. The fix initializes them before they are used.
=> Some uses of uninitialized variables in loops category

c/pthread-atomic/gcd_true-unreach-call_true-termination.c, c/pthread-atomic/gcd_true-unreach-call_true-termination.i, c/pthread-ext/09_fmaxsym_true-unreach-call.c, c/pthread-ext/09_fmaxsym_true-unreach-call.i, c/pthread-ext/10_fmaxsym_cas_true-unreach-call.c, c/pthread-ext/10_fmaxsym_cas_true-unreach-call.i, c/pthread-ext/11_fmaxsymopt_true-unreach-call.c, c/pthread-ext/11_fmaxsymopt_true-unreach-call.i, c/pthread-ext/12_fmaxsymopt_cas_true-unreach-call.c, c/pthread-ext/12_fmaxsymopt_cas_true-unreach-call.i, c/pthread-ext/28_buggy_simple_loop1_vf_false-unreach-call.c, c/pthread-ext/28_buggy_simple_loop1_vf_false-unreach-call.i
fixed uninitialized variables using __VERIFIER_nondet_int(uint) function calls.
=> fixed uninitialized variables using nondet_int function calls

c/pthread-atomic/gcd_true-unreach-call_true-termination.c, c/pthread-atomic/gcd_true-unreach-call_true-termination.i
move the assumption that guessed_gcd>1 so that the modulus denominator could never be zero.
=> fixed modulus denominator possibly being zero.

c/regression/drivers--isdn--mISDN--mISDN_core.ko_001.c5b61d5.08_1a.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_001.c5b61d5.32_7a.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_001.c5b61d5.39_7a.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_001.c5b61d5.43_1a.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_001.c5b61d5.68_1.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_002.ff4cc1d.08_1a.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_002.ff4cc1d.32_1.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_002.ff4cc1d.32_7a.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_002.ff4cc1d.39_7a.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_002.ff4cc1d.43_1a.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_002.ff4cc1d.68_1.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_003.ce425a9.08_1a.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_003.ce425a9.32_1.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_003.ce425a9.32_7a.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_003.ce425a9.39_7a.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_003.ce425a9.43_1a.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_003.ce425a9.68_1.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_004.6bff338.08_1a.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_004.6bff338.32_1.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_004.6bff338.32_7a.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_004.6bff338.39_7a.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_004.6bff338.43_1a.cil_true-unreach-call.i, c/regression/drivers--isdn--mISDN--mISDN_core.ko_004.6bff338.68_1.cil_true-unreach-call.i
=> Fix mismatched argument type in isdn drivers. GCC 5.2.0 emitted

c/pthread-ext/28_buggy_simple_loop1_vf_false-unreach-call.c, c/pthread-ext/28_buggy_simple_loop1_vf_false-unreach-call.i
When x equals to 0, j and k will never get initialized; therefore, initialized j and k to 1, as what would be done by the initializations in the nested for loops.
=> fixed uninitialized variables

c/pthread-lit/fkp2014_true-unreach-call.c, c/pthread-lit/fkp2014_true-unreach-call.i
t=0; is unsafe because pthread_t is an opaque object and it could be defined as a struct in some implementation. Thus removed this assignment.
=> fixed the initialization of the variable t of type pthread_t

c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--char--ramoops.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--mtd--devices--doc2001plus.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/43_1a_cilled_true-unreach-call_ok_nondet_linux-43_1a-drivers--mtd--devices--doc2001plus.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c
Inline asm was causing clang compilation errors in two benchmarks. These small fixes address this issue. Benchmarks can still be compiled on gcc too without any problems.
=> Fixed two clang compilation errors

c/array-examples/relax_true-unreach-call.c, c/array-examples/relax_true-unreach-call.i, c/array-examples/standard_seq_init_true-unreach-call_ground.i, c/bitvector/interleave_bits_true-unreach-call.i, c/bitvector/modulus_true-unreach-call.i
We added an assume statement that prevents undefined behavior in the left shift operator from happening. Note that left shift is undefined if one is shifting for >= the number of available bits.
=> Left shift operator creates undefined behavior

c/pthread-ext/42_FreeBSD__rdma_addr__sliced_true-unreach-call.c, c/pthread-ext/42_FreeBSD__rdma_addr__sliced_true-unreach-call.i
It is possible that refctr gets incremented infinitely. Therefore, we need to change its type to unsigned int.
=> fixed integer overflow by using unsigned integer

c/Makefile.config, c/Makefile.rules, c/ldv-consumption/32_7a_cilled_true-unreach-call_linux-3.8-rc1-32_7a-drivers--isdn--hisax--hisax.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-races/race-4_2-thread_local_vars_false-unreach-call.c, c/ldv-races/race-4_2-thread_local_vars_false-unreach-call.i, c/loop-invgen/apache-escape-absolute_true-unreach-call.c, c/loop-invgen/apache-escape-absolute_true-unreach-call.i
This PR 
* Reverts the hack I added to workaround benchmarks that didn't compile with Clang without ``-Wno-return-type``.
* Removes some warning suppression flags which I see no good reason for suppressing
* Lays the ground work for treating certain warnings as errors and adds ``-Werror=main`` as an example.
Ideally I'd like to add ``-Werror=implicit-function-declaration`` and ``-Werror=implicit-int`` but unfortunately it looks like the benchmarks are littered with violations of these.
=> Remove some warning suppression flags and lay the ground work for treating some warnings as errors

c/pthread-atomic/qrcu_false-unreach-call.c, c/pthread-atomic/qrcu_false-unreach-call.i, c/pthread-atomic/qrcu_true-unreach-call.c, c/pthread-atomic/qrcu_true-unreach-call.i, c/pthread-atomic/read_write_lock_false-unreach-call.c, c/pthread-atomic/read_write_lock_false-unreach-call.i, c/pthread-atomic/read_write_lock_true-unreach-call.c, c/pthread-atomic/read_write_lock_true-unreach-call.i
Based on my understanding of the spec, these routines should take one void* argument.
=> Fixing signatures of routines that are passed to pthread_create

c/ldv-linux-3.0/usb_urb-drivers-media-video-c-qcam.ko_true-unreach-call.cil.out.i.pp.cil.c, c/ldv-linux-3.0/usb_urb-drivers-media-video-msp3400.ko_true-unreach-call.cil.out.i.pp.cil.c, c/ldv-linux-3.0/usb_urb-drivers-usb-misc-iowarrior.ko_false-unreach-call.cil.out.i.pp.cil.c, c/ldv-linux-3.0/usb_urb-drivers-usb-serial-whiteheat.ko_true-unreach-call.cil.out.i.pp.cil.c, c/ldv-linux-3.0/usb_urb-drivers-vhost-vhost_net.ko_true-unreach-call.cil.out.i.pp.cil.c
```
Error: incorrect register `%rax' used with `w' suffix
```
This only appears when make is run with ``SYNTAX_ONLY=0`` because
when gcc is passed ``-fsyntax-only`` (i.e. ``SYNTAX_ONLY=1``) the
GNU assembler is not invoked.
This fixes issue #42
=> Fix or comment out bad assembly code that gcc 5.2 rejects with the error

c/termination-crafted/LexIndexValue-Pointer_false-valid-deref.c
additionally, I added the original copy with a _false-valid-deref label
=> memsafety bugfix in termination-crafted

README.md
The breakage is due to the move of the repository from dbeyer/sv-benchmarks to sosy-lab/sv-benchmarks on GitHub.
=> Fix broken TravisCI build status badge.

c/ldv-linux-3.16-rc1/205_9a_array_safes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--wireless--libertas_tf--libertas_tf.ko-entry_point_true-unreach-call.cil.out.c
To avoid of null pointer dereference we consider the service variables to be allocated successfully.
=> Add successfull allocation for special (service) variables

c/seq-pthread/cs_read_write_lock_false-unreach-call.c, c/seq-pthread/cs_read_write_lock_false-unreach-call.i, c/seq-pthread/cs_read_write_lock_true-unreach-call.c, c/seq-pthread/cs_read_write_lock_true-unreach-call.i
Argument types of functions reader and writer did not match
what was expected by the respective invocations through
function pointers.
=> Fixed wrong argument types of thread functions

c/ldv-validator-v0.8/Makefile, c/signedintegeroverflow-regression/Makefile, c/termination-15/Makefile, c/termination-libowfat/Makefile, c/termination-restricted-15/Makefile
Fix incorrectly set build architecture (was implicitly 32-bit but should be 64-bit) to match what is documented at
http://sv-comp.sosy-lab.org/2016/benchmarks.php
=> Fix incorrectly set build architecture

c/ldv-linux-3.0/usb_urb-drivers-usb-serial-whiteheat.ko_true-unreach-call.cil.out.i.pp.i
Function whiteheat_attach can fail without actually attaching anything. On the
other hand, whiteheat_release actually has an assertion that checks that
something was attached. So it should not be called if nothing was attached,
which is indicated with error codes -19 and -12.
=> Added checks to ensure that something was attached

c/heap-manipulation/bubble_sort_linux_false-unreach-call.i, c/heap-manipulation/bubble_sort_linux_true-unreach-call.i, c/heap-manipulation/dancing_true-unreach-call.i, c/heap-manipulation/dll_of_dll_false-unreach-call.i, c/heap-manipulation/dll_of_dll_true-unreach-call.i, c/heap-manipulation/merge_sort_false-unreach-call.i, c/heap-manipulation/merge_sort_true-unreach-call.i, c/heap-manipulation/sll_to_dll_rev_false-unreach-call.i, c/heap-manipulation/sll_to_dll_rev_true-unreach-call.i
The files in c/heap-manipulation are declared as 32bit, but have been pre-processed with 64bit headers. This PR provides versions that have been pre-processed on a 64bit Ubuntu 14.04 with GCC 4.8 and a 32-bit build architecture (`-m32` compiler flag).
I do not know whether this changes the expected result, somebody with more understanding of these files should probably have a look at this.
=> Preprocess files in heap-manipulation with 32bit headers

c/pthread-ext/06_ticket_true-unreach-call.c, c/pthread-ext/06_ticket_true-unreach-call.i, c/pthread-lit/assert.h, c/pthread-lit/fk2012_true-unreach-call.c, c/pthread-lit/fk2012_true-unreach-call.i, c/pthread-lit/fkp2013_false-unreach-call.i, c/pthread-lit/fkp2013_true-unreach-call.i, c/pthread-lit/fkp2013_variant_false-unreach-call.i, c/pthread-lit/fkp2013_variant_true-unreach-call.i, c/pthread-lit/fkp2014_true-unreach-call.c, c/pthread-lit/fkp2014_true-unreach-call.i, c/pthread-lit/qw2004_false-unreach-call.c, c/pthread-lit/qw2004_false-unreach-call.i, c/pthread-lit/qw2004_true-unreach-call.c, c/pthread-lit/qw2004_true-unreach-call.i, c/pthread-lit/qw2004_variant_true-unreach-call.c, c/pthread-lit/qw2004_variant_true-unreach-call.i, c/pthread-lit/sssc12_true-unreach-call.c, c/pthread-lit/sssc12_true-unreach-call.i, c/pthread-lit/sssc12_variant_true-unreach-call.c, c/pthread-lit/sssc12_variant_true-unreach-call.i
This pull request removes depreciated __VERIFIER_atomic_*() declarations, definitions, and calls from the pthread-lit group of benchmarks.
It changes occurrences of __VERIFIER_atomic_*() to *(), and wraps the bodies of such function definitions in __VERIFIER_atomic_begin() and __VERIFIER_atomic_end() calls.
=> Depreciated concurrency atomic fix  - pthread-lit

c/Makefile.rules
Show the value of `WARNINGS_AS_ERRORS` when the `debug_vars` target is run
=> Show the value of `WARNINGS_AS_ERRORS` when the `debug_vars` target is run

c/bitvector/byte_add_1_true-unreach-call.c, c/bitvector/byte_add_2_true-unreach-call.c, c/bitvector/interleave_bits_true-unreach-call.c, c/bitvector/num_conversion_2_true-unreach-call.c, c/bitvector/parity_true-unreach-call.c, c/bitvector/s3_clnt_1_true-unreach-call.BV.c.cil.c, c/bitvector/s3_clnt_2_true-unreach-call.BV.c.cil.c, c/bitvector/s3_clnt_3_true-unreach-call.BV.c.cil.c
Initialize variables with nondet values, if they were previously used uninitialized.
For bitvector/interleave_bits_true-unreach-call.c ,
RV-Match reports undefinedness due to a bitwise left shift
for which the right operand is "equal or bigger" than
the bit size of the left operand. (Line 28).
To my understanding, this is a false positive since GNU C only defines
this operation undefined if the right operand is "bigger"
than the bit size of the left operand.
(https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Bit-Shifting)
In the given case .. << (i + 1), i is always smaller than 32,
so assuming a 32 bit machine model, the operation is defined
due to i+1 <= 32.
=> Fixed undefinedness for bitvector category.

c/ldv-races/race-2_1-container_of_true-unreach-call.c, c/ldv-races/race-3_1-container_of-global_true-unreach-call.c, c/pthread-lit/sssc12_true-unreach-call.c, c/pthread-lit/sssc12_variant_true-unreach-call.c
One error reported by RV-Match is due to macro `offsetof` being defined multiple times.
Should we fix these by adding `#ifndef` or not? In a real-case scenario, a warning might be more useful than masking the error, IMO.
Other fixes add missing headers to include `malloc`.
=> Fix undefined behavior in tasks of category Concurrency

c/signedintegeroverflow-regression/IntegerPromotion_true-no-overflow.c, c/signedintegeroverflow-regression/IntegerPromotion_true-no-overflow.c.i
Use correct printf placeholders for `unsigned short`.
=> Fix undefinedness of task in signedintegeroverflow-regression

c/array-industry-pattern/array_mul_init_true-unreach-call.c, c/array-industry-pattern/array_mul_init_true-unreach-call.i, c/array-industry-pattern/array_of_struct_ptr_mul_init_true-unreach-call.c, c/array-industry-pattern/array_of_struct_ptr_mul_init_true-unreach-call.i, c/array-industry-pattern/array_single_elem_init_false-unreach-call.c, c/array-industry-pattern/array_single_elem_init_false-unreach-call.i
In these benchmarks nondet functions had improper signatures.
I fixed these issues to the best of my understanding of these
benchmarks.
=> Fixed improper signatures of nondet functions

c/array-industry-pattern/check_removal_from_set_after_insertion_false-unreach-call.c, c/array-industry-pattern/check_removal_from_set_after_insertion_false-unreach-call.i
Variable SIZE was not initialized before it was used. I suspect
that SIZE should be a constant set to 100000 like in other
benchmarks in this folder.
=> Fixed undefined behavior due to uninitialized variable

c/array-industry-pattern/Makefile, c/array-industry-pattern/array_of_struct_ptr_cond_init_true-unreach-call.c, c/array-industry-pattern/array_of_struct_ptr_cond_init_true-unreach-call.i, c/array-industry-pattern/array_of_struct_ptr_flag_init_true-unreach-call.c, c/array-industry-pattern/array_of_struct_ptr_flag_init_true-unreach-call.i, c/array-industry-pattern/array_of_struct_ptr_monotonic_true-unreach-call.c, c/array-industry-pattern/array_of_struct_ptr_monotonic_true-unreach-call.i, c/array-industry-pattern/array_ptr_partial_init_true-unreach-call.c, c/array-industry-pattern/array_ptr_partial_init_true-unreach-call.i, c/array-industry-pattern/array_ptr_single_elem_init_true-unreach-call.c, c/array-industry-pattern/array_ptr_single_elem_init_true-unreach-call.i
It was declared as unsigned long int, but it needs to be unsigned int
because the files are in a 32 bit category.
size_t is only used for the declaration of malloc in these benchmarks.
=> Fix declaration of size_t in array-industry-pattern benchmarks.

c/loops/Makefile, c/loops/n.c24_false-unreach-call.i, c/loops/s3_false-unreach-call.i, c/loops/veris.c_OpenSER__cases1_stripFullBoth_arr_true-unreach-call_true-termination.c, c/loops/veris.c_OpenSER__cases1_stripFullBoth_arr_true-unreach-call_true-termination.i, c/loops/verisec_OpenSER__cases1_stripFullBoth_arr_false-unreach-call_true-termination.c, c/loops/verisec_OpenSER__cases1_stripFullBoth_arr_false-unreach-call_true-termination.i
For n.c24_false-unreach-call.i, this is fixed by doing a fresh
pre-processing, which changes only extern function declarations.
For the other files, this is fixed by manually correcting the definition
of size_t (which is only used in extern function declarations) to be unsigned
or fixing malloc declarations.
Thus the change should not affect the semantics of the files.
=> Fix a few incompatible library declarations in directory loops.

c/pthread-lit/fk2012_true-unreach-call.c, c/pthread-lit/fk2012_true-unreach-call.i
The values are never used thus using NULL seems good enough. Fixes #77.
=> Threads should return a value of type void*

c/loops/veris.c_OpenSER__cases1_stripFullBoth_arr_true-unreach-call_true-termination.c, c/loops/veris.c_OpenSER__cases1_stripFullBoth_arr_true-unreach-call_true-termination.i
This variant includes a patch over the failing one
(verisec_OpenSER__cases1_stripFullBoth_arr_false-unreach-call_true-termination.c).
The property to check thus holds, but should still be checked.
Fixes #79.
=> Added assertion from corresponding false-unreach-call task

c/ArraysMemSafety.cfg, c/ArraysReach.cfg, c/BitVectorsOverflows.cfg, c/BitVectorsReach.cfg, c/BusyBox.cfg, c/Concurrency.cfg, c/ControlFlow.cfg, c/DeviceDriversLinux64.cfg, c/ECA.cfg, c/Floats.cfg, c/HeapMemSafety.cfg, c/HeapReach.cfg, c/Loops.cfg, c/ProductLines.cfg, c/Recursive.cfg, c/Sequentialized.cfg, c/Simple.cfg, c/Termination.cfg, c/check.py
With just a single ("Precise") memory model, there is no need to specify
this in configuration files.
=> Specification of memory model is now redundant

c/Termination-Concurrency.cfg, c/Termination-Concurrency.prp, c/Termination-Concurrency.set, c/Termination-ControlFlow.cfg, c/Termination-ControlFlow.prp, c/Termination-ControlFlow.set, c/Termination-Loops.cfg, c/Termination-Loops.prp, c/Termination-Loops.set, c/Termination-ProductLines.cfg, c/Termination-ProductLines.prp, c/Termination-ProductLines.set, c/Termination-Recursive.cfg, c/Termination-Recursive.prp, c/Termination-Recursive.set, c/Termination-Sequentialized.cfg, c/Termination-Sequentialized.prp, c/Termination-Sequentialized.set, c/Termination.set, c/check.py
The product-line files had been processed using Cil to use
pointer-arithmetic to access struct members. This may cause different
behaviour when moving th 64-bit architectures.
=> Create a 32-bit category of Termination benchmarks

c/memsafety/20051113-1.c_false-valid-memtrack.c, c/memsafety/20051113-1.c_false-valid-memtrack.i
The removed malloc declaration is redundant and also not correct for a 32 bit benchmark. Although this benchmark requires re-preprocessing because it was done in a 64 bit set up, it does not hurt to remove the declaration for now.
=> Removing extraneous declaration of malloc

c/ldv-memsafety/memset2_false-valid-deref-write.c, c/ldv-memsafety/memset2_true-valid-memsafety.c, c/ldv-memsafety/memset3_false-valid-deref-write.c, c/ldv-memsafety/memset3_true-valid-memsafety.c, c/ldv-memsafety/memsetNonZero2_false-valid-deref-write.c, c/ldv-memsafety/memsetNonZero2_true-valid-memsafety.c, c/ldv-memsafety/memsetNonZero3_false-valid-deref-write.c, c/ldv-memsafety/memsetNonZero3_true-valid-memsafety.c, c/ldv-memsafety/memsetNonZero_false-valid-deref-write.c, c/ldv-memsafety/memsetNonZero_true-valid-memsafety.c, c/ldv-memsafety/memset_false-valid-deref-write.c, c/ldv-memsafety/memset_true-valid-memsafety.c
Luckily these benchmarks do not have the respective preprocessed files,
and so this was an easy fix.
=> Fixed size_t of several mem safety benchmarks to match 32-bit arch

.travis.yml, c/compare.sh
In the past, source files and their preprocessed counterparts had not
always been updated synchronously. This commit adds a script to compare
all sets except for Concurrency using goto-diff as discussed on the
sv-comp mailing list.
=> RFC: Use goto-diff to compare original source and preprocessed files

c/heap-manipulation/tree_true-unreach-call.c, c/heap-manipulation/tree_true-unreach-call.i
Field `parent` of root node is uninitialized yet accessed in function
`inspect`.
=> Fix access to uninitialized memory in benchmark c/heap-manipulation/tree_true-unreach-call.c

c/array-examples/relax_false-valid-deref.c, c/array-examples/relax_false-valid-deref.i, c/termination-crafted/LexIndexValue-Pointer_false-valid-deref.c, c/termination-crafted/SyntaxSupportPointer01_false-valid-deref.c
Otherwise the programs would also suffer from memory leak
Signed-off-by: Mikhail Ramalho <mikhail.ramalho@gmail.com>
=> Missing frees on false-valid-deref benchmarks

c/ldv-regression/test11_true-unreach-call.c, c/ldv-regression/test14_true-unreach-call.c, c/ldv-regression/test21_false-unreach-call.c, c/ldv-regression/test21_true-unreach-call.c, c/ldv-regression/test22_false-unreach-call.c, c/ldv-regression/test22_true-unreach-call.c, c/ldv-regression/test23_false-unreach-call.c, c/ldv-regression/test23_true-unreach-call.c, c/ldv-regression/test24_false-unreach-call.c, c/ldv-regression/test24_true-unreach-call.c, c/ldv-regression/test25_false-unreach-call.c, c/ldv-regression/test26_false-unreach-call.c, c/ldv-regression/test26_true-unreach-call.c, c/ldv-regression/test27_false-unreach-call.c, c/ldv-regression/test28_false-unreach-call.c, c/ldv-regression/test29_false-unreach-call.c, c/ldv-regression/test30_false-unreach-call.c, c/ldv-regression/test30_true-unreach-call.c
I removed the nondet_pointer calls and replaced them with an static variable and nondet initialization of its content.
I decided to use the static variable instead of malloc'ing to avoid memory leak. The programs use goto statements to jump to the __VERIFIER_error() function call, so by using a static variable we avoid changing too much the program.
=> Remove calls to __VERIFIER_nondet_pointer() from ldv-regression/test*.c

c/memsafety/20020406-1_false-valid-memtrack.c, c/memsafety/20020406-1_false-valid-memtrack.i
Since there is no NULL pointer check for calloc, there is a possibility of NULL pointer dereference. Since the benchmark is for memtrack and not for memory dereferencing, changing calloc to malloc.
=> Replacing calloc with malloc

c/bitvector/jain_1_false-no-overflow.c, c/bitvector/jain_1_false-no-overflow.i, c/bitvector/jain_1_true-unreach-call.c, c/bitvector/jain_1_true-unreach-call.i, c/bitvector/jain_2_false-no-overflow.c, c/bitvector/jain_2_false-no-overflow.i, c/bitvector/jain_2_true-unreach-call.c, c/bitvector/jain_2_true-unreach-call.i, c/bitvector/jain_4_false-no-overflow.c, c/bitvector/jain_4_false-no-overflow.i, c/bitvector/jain_4_true-unreach-call.c, c/bitvector/jain_4_true-unreach-call.i, c/bitvector/jain_5_false-no-overflow.c, c/bitvector/jain_5_false-no-overflow.i, c/bitvector/jain_5_true-unreach-call.c, c/bitvector/jain_5_true-unreach-call.i, c/bitvector/jain_6_false-no-overflow.c, c/bitvector/jain_6_false-no-overflow.i, c/bitvector/jain_6_true-unreach-call.c, c/bitvector/jain_6_true-unreach-call.i, c/bitvector/jain_7_false-no-overflow.c, c/bitvector/jain_7_false-no-overflow.i, c/bitvector/jain_7_true-unreach-call.c, c/bitvector/jain_7_true-unreach-call.i, c/check.py
As discussed in #307, this pull request is created to remove signed integer overflows that exist in the bitvector folder. Basically all signed declarations and arithmetic operations are converted to unsigned. Given the program behavior has changed, I will attach a verified Boogie program with bit vectors types for each related benchmark. We are working on supporting loop invariant and code contracts for SMACK so please understand I have to code them into Boogie manually and thus do not provide correctness witnesses.
Verified Boogie programs for each benchmark are the following.
jain_1_true-unreach-call.*:
```boogie
procedure main() returns (r:bv32)
{
var y,tmp1 : bv32;
y := 1bv32;
while(1==1)
invariant urem.bv32(y, 2bv32) == 1bv32;
{
havoc tmp1;
y := add.bv32(y, mul.bv32(2bv32, tmp1)); …
```
=> Fix overflows in the BitVectorsReach catgegory

c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--media--dvb--dvb-usb--dvb-usb-az6007.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c
This benchmark contains dispatch to uninitialized function pointers, which results in assertion failure. For example, `var_group_4` is calloced, so `__cil_tmp23` at line 8285 is equal to the return value of calloc + 1600. `__cil_tmp24` at line 8286 is the deference of `__cil_tmp23` which equals to 0 (calloced memory). `__cil_tmp26` at line 8288 will be 360, which is not initialized. `__cil_tmp27` at line 8289 is the deference of `__cil_tmp26` which can be any value. In line 8295, a function pointer is called which is the deference of `__cil_tmp27`. So a function that results in the assertion failure will be called since `*__cil_tmp27` could alias with any function.
For the record, this fix is not supposed to fix all uninitialized memory accesses. We only intend to fix those that lead to …
=> Attempt to fix the first benchmark in #191

c/check.py, c/ntdrivers/floppy_false-unreach-call.i.cil.c, c/ntdrivers/floppy_false-valid-deref.i.cil.c, c/ntdrivers/kbfiltr_false-valid-deref.i.cil.c
Fix invalid dereferences in two ntdrivers benchmarks and add the old files as false-valid-deref. I was not sure into which category these should be added, so I just put them to check.py.
The floppy benchmarks were dereferencing some kernel object whose address was hardcoded into the benchmark, so I created a dummy object instead and made the only value used from it nondeterministic. The benchmark also contained a definition of `malloc`, that returned always the address of one global, just to return something (which again led to invalid-dereferences). I believe that removing this definition did not change the semantics of benchmark (and I do not know who is the author to check with him).
The kbfilter benchmark had a definition `PIPR ipr` (pointer to IPR) and was using it as if it was the …
=> Ntdrivers fixes

c/ldv-consumption/32_7a_cilled_true-unreach-call_linux-3.8-rc1-32_7a-drivers--pcmcia--pcmcia.ko-ldv_main2_sequence_infinite_withcheck_stateful.cil.out.c
Similar to the fix in #305, this fix remove function pointer dispatch
which is uninitialized and leads to assertion failure.
=> Attempt to fix the third benchmark in #191

c/seq-pthread/cs_fib_false-unreach-call.i, c/seq-pthread/cs_fib_longer_false-unreach-call.i, c/seq-pthread/cs_queue_false-unreach-call.i, c/seq-pthread/cs_read_write_lock_false-unreach-call.i, c/seq-pthread/cs_stack_false-unreach-call.i, c/seq-pthread/cs_stateful_false-unreach-call.i
Hi,
I found few other benchmarks that used uninitialized values. Here's a fix (simply initialize that value using the __VERIFIER_nondet function).
=> fix use of uninitialized value in cs_...false-unreach-call benchmarks

c/MemSafety-LinkedLists.set, c/list-properties/alternating_list_false-unreach-call_false-valid-memsafety.c, c/list-properties/alternating_list_false-unreach-call_false-valid-memsafety.i, c/list-properties/alternating_list_false-unreach-call_true-valid-memsafety.c, c/list-properties/alternating_list_false-unreach-call_true-valid-memsafety.i, c/list-properties/alternating_list_true-unreach-call_false-valid-memtrack.c, c/list-properties/alternating_list_true-unreach-call_false-valid-memtrack.i
This PR adds destroying the dynamically allocated list in alternating_list benchmark, which is labeled as true-valid-memsafety. The old files with leaks have been added as false-valid-memtrack.
This fixes one benchmark from the issue #333
=> Fix memory leaks in alternating_list_*_true-valid-memsafety.[ci]

c/MemSafety-LinkedLists.set
Fixes issue #327. `list-ext-properties/*_true-valid-memsafety*.i` is already present in category MemSafety-Heap.
=> Remove duplicate files from MemSafety-LinkedLists

c/pthread-complex/bounded_buffer_false-unreach-call.c, c/pthread-complex/bounded_buffer_false-unreach-call.i
The fields c_wait, p_wait (both of int type)  of the variable bbuf of bounded_buf_t type are never initialized but the values are used. Therefore, initialize these fields c_wait and p_wait with 0.
=> fixed undefined behavior of uninitialized variable;

c/list-ext-properties/list-ext_false-unreach-call_false-valid-deref.c, c/list-ext-properties/list-ext_false-unreach-call_false-valid-deref.i, c/list-ext-properties/list-ext_flag_false-unreach-call_false-valid-deref.c, c/list-ext-properties/list-ext_flag_false-unreach-call_false-valid-deref.i
`list-ext-properties/list-{ext,ext_flag}_false-unreach-call_false-valid-deref`: fix multiple errors in memsafety (deref+memleaks), fix PR #354
=> multiple errors in memsafety in list-ext-properties

c/check.py
I suggest this instead of adding a hundreds of temporary exceptions
=> Make check.py ignore -todo directories

c/pthread-driver-races/char_generic_nvram_nvram_llseek_nvram_unlocked_ioctl_true-unreach-call.i, c/pthread-driver-races/char_generic_nvram_nvram_llseek_read_nvram_true-unreach-call.i, c/pthread-driver-races/char_generic_nvram_nvram_llseek_write_nvram_true-unreach-call.i, c/pthread-driver-races/char_generic_nvram_nvram_unlocked_ioctl_write_nvram_true-unreach-call.i, c/pthread-driver-races/char_generic_nvram_read_nvram_nvram_unlocked_ioctl_true-unreach-call.i, c/pthread-driver-races/char_generic_nvram_read_nvram_write_nvram_false-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_change_pc8736x_gpio_configure_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_change_pc8736x_gpio_current_false-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_change_pc8736x_gpio_get_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_change_pc8736x_gpio_set_false-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_configure_pc8736x_gpio_current_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_configure_pc8736x_gpio_get_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_configure_pc8736x_gpio_set_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_current_pc8736x_gpio_get_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_current_pc8736x_gpio_set_false-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_get_pc8736x_gpio_set_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_change_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_configure_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_current_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_get_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_set_true-unreach-call.i
A number of programs from the folder pthread-driver-races declares an enumeration type (i.e., "enum migrate_mode") without the list of enumerators, which is against the constrain from the C standards:
6.7.2.3 Tags
Constraints
...
3 A type specifier of the form
enum identifier
without an enumerator list shall only appear after the type it specifies is complete.
This commit fixes these problems by adding a dummy list of enumerators (e.g., "{X}") for the enumeration type declaration. 
Also see issue #341
=> fixing enumeration type declaration that miss the enumerator list

c/pthread-driver-races/char_generic_nvram_nvram_llseek_nvram_unlocked_ioctl_true-unreach-call.i, c/pthread-driver-races/char_generic_nvram_nvram_llseek_read_nvram_true-unreach-call.i, c/pthread-driver-races/char_generic_nvram_nvram_llseek_write_nvram_true-unreach-call.i, c/pthread-driver-races/char_generic_nvram_nvram_unlocked_ioctl_write_nvram_true-unreach-call.i, c/pthread-driver-races/char_generic_nvram_read_nvram_nvram_unlocked_ioctl_true-unreach-call.i, c/pthread-driver-races/char_generic_nvram_read_nvram_write_nvram_false-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_change_pc8736x_gpio_configure_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_change_pc8736x_gpio_current_false-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_change_pc8736x_gpio_get_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_change_pc8736x_gpio_set_false-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_configure_pc8736x_gpio_current_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_configure_pc8736x_gpio_get_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_configure_pc8736x_gpio_set_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_current_pc8736x_gpio_get_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_current_pc8736x_gpio_set_false-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_get_pc8736x_gpio_set_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_change_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_configure_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_current_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_get_true-unreach-call.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_set_true-unreach-call.i, c/pthread-driver-races/model/linux/fs.h, c/pthread-driver-races/model/linux/mutex.h, c/pthread-driver-races/model/linux/spinlock.h
This pull request attempt to submit the fixed version of headers (`model/linux/mutex.h` and `spinlock.h`) that assume `pthread_t` is `int`, as discussed in issue 365. Also, I just realized that the enumeration type `migrate_mode` is declared in `model/linux/fs.h`, which was complained in issue 341. So I also fix it in this pull request, so that when the `*.i` are regenerated, the fix will still be reflected.
=> fixing issues in benchmarks from pthread-driver-races

c/heap-manipulation/tree_false-unreach-call_false-valid-deref.c, c/heap-manipulation/tree_false-unreach-call_false-valid-deref.i, c/heap-manipulation/tree_false-unreach-call_true-valid-memsafety.c, c/heap-manipulation/tree_false-unreach-call_true-valid-memsafety.i
Memory in this benchmark was not completely freed when the end
of the program was reached. Based on our long discussion on the
mailing list, we should fix such benchmarks. This fix addresses
this issue and frees all the memory.
=> Fixed a "reachable memory in the end" issue

c/pthread-C-DAC/pthread-numerical-integration_true-unreach-call.c, c/pthread-C-DAC/pthread-numerical-integration_true-unreach-call.i
In this program, there are two int-type variables `numberOfIntervals` and `num_threads`, and `numberOfIntervals` is initialized as `__VERIFIER_nondet_int()`, and then `num_threads = numberOfIntervals`. Then `numberOfIntervals` is use as the size argument for `malloc`. The problem is that `__VERIFIER_nondet_int()` could return negative value in which case the `malloc` call would become undefined. 
The second problem is that when `__VERIFIER_nondet_int()` returns 0, `numberOfIntervals` will become 8 while `num_threads` remains 0. In this case, the allocated memory represented by `threads` will never be initialized, but in the second loop it would read `threads[iCount]`, which leads to undefined behavior.
I'm proposing to fix this by replacing `if (numberOfIntervals == 0){numberOfIntervals = …
=> fixed undefined behaviors in the benchmark pthread-numerical-integration_true-unreach-call from pthread-C-DAC

c/termination-crafted/Arrays02-EquivalentConstantIndices_true-no-overflow.c
There is a local array in `main` that is not initialized. This pull request fixes it.
I was wondering if I should keep the original file and add a label that indicates that there is undefined behavior inside it.
=> Fix uninitialized array in termination-crafted/Arrays02-EquivalentConstantIndices_true-no-overflow.c

c/termination-crafted/LexIndexValue-Pointer_true-termination_true-valid-memsafety.c, c/termination-crafted/NonTermination3_false-termination_false-valid-deref.c, c/termination-crafted/SyntaxSupportPointer01_true-termination_true-valid-memsafety.c
Fix two memory leaks and one out-of-bound access in termination-crafted benchmarks
=> Termination crafted memsafety

c/busybox-1.22.0/basename_false-unreach-call_true-no-overflow_false-valid-deref.c, c/busybox-1.22.0/basename_false-unreach-call_true-no-overflow_false-valid-deref.i
At least for basename the call to exit() would guard against dereferencing a
null pointer. To avoid memory leaks in the additional main() wrapper that
allocates argv, bb_show_usage is replaced by return.
There may be further BusyBox examples that suffer from similar problems (but
CBMC doesn't report any such thus far).
=> bb_show_usage implies exit()

c/Systems_BusyBox_MemSafety.set
The original versions of benchmarks recently fixed had been added to the
repository, but did not become part of any tasks. This commit would thus
introduce _additional_ (though not necessarily _new_) benchmarks.
The pull request is marked as request-for-comment in light of recent discussions on the mailing list. Please do not merge without consent from >1 jury member.
=> RFC: Add BusyBox false-valid-deref benchmarks

c/termination-memory-alloca/b.05-alloca_true-termination_true-no-overflow.c, c/termination-memory-alloca/b.05-alloca_true-termination_true-no-overflow.c.i, c/termination-memory-alloca/b.09-no-inv_assume-alloca_true-termination_true-no-overflow.c, c/termination-memory-alloca/b.09-no-inv_assume-alloca_true-termination_true-no-overflow.c.i, c/termination-memory-alloca/b.09_assume-alloca_true-termination_true-no-overflow.c, c/termination-memory-alloca/b.09_assume-alloca_true-termination_true-no-overflow.c.i, c/termination-memory-alloca/b.18-alloca_true-termination_true-no-overflow.c, c/termination-memory-alloca/b.18-alloca_true-termination_true-no-overflow.c.i
In these benchmarks, there can be possibly executed either 2*INT_MIN or INT_MIN + INT_MIN operations. More detailed reasoning about the fixes is in the commit messages.
=> Fix underflows in termination-memory-alloca

c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--rtc--rtc-ds1390.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c
A simple fix. This benchmark uses pointers that are not initialized at all.
Allocate a memory using malloc (thus the contents is nondet) and free it at the end of main.
=> fix invalid dereferences in a ldv benchmark

c/termination-memory-linkedlists-todo/cll_search-alloca-WithForgottenReturn_false-valid-deref.c, c/termination-memory-linkedlists-todo/ll_append-alloca-WithAbsOfMinIntBug_false-no-overflow.c, c/termination-memory-linkedlists-todo/ll_create_rec-alloca-WithMinIntBug_false-no-overflow.c, c/termination-memory-linkedlists-todo/ll_search_not_found-alloca-WithAllocabug_false-valid-deref.c
* add original files (from termination-memory-linkedlists) that have overflow
and memsafety bugs and that were fixed in PR #425
* I kept only one file for each problem
* The files are added to a new folder termination-memory-linkedlists-todo
but we can directly move them to termination-memory-linkedlists after
the competition
=> add orginal files for the fixes in PR #425

c/reducercommutativity/rangesum05_false-unreach-call.c, c/reducercommutativity/rangesum05_false-unreach-call.i, c/reducercommutativity/rangesum10_false-unreach-call.c, c/reducercommutativity/rangesum10_false-unreach-call.i, c/reducercommutativity/rangesum20_false-unreach-call.c, c/reducercommutativity/rangesum20_false-unreach-call.i, c/reducercommutativity/rangesum40_false-unreach-call.c, c/reducercommutativity/rangesum40_false-unreach-call.i, c/reducercommutativity/rangesum60_false-unreach-call.c, c/reducercommutativity/rangesum60_false-unreach-call.i, c/reducercommutativity/rangesum_false-unreach-call.c, c/reducercommutativity/rangesum_false-unreach-call.i
In #181, there was already an effort to fix undefined behavior in the tasks in c/reducercommutativity, but the rangesum tasks of this set were omitted.
I did not preserve the undefined behavior as an example task, because the directory already contains plenty, largely equivalent examples from #181.
=> Initialize array cells in rangesum tasks to fix undefined behavior.

c/systemc/token_ring.01_false-unreach-call_false-termination.cil.c, c/systemc/token_ring.02_false-unreach-call_false-termination.cil.c, c/systemc/token_ring.03_false-unreach-call_false-termination.cil.c, c/systemc/token_ring.04_false-unreach-call_false-termination.cil.c, c/systemc/token_ring.05_false-unreach-call_false-termination.cil.c, c/systemc/token_ring.06_false-unreach-call_false-termination.cil.c, c/systemc/token_ring.07_false-unreach-call_false-termination.cil.c, c/systemc/token_ring.08_false-unreach-call_false-termination.cil.c, c/systemc/token_ring.09_false-unreach-call_false-termination.cil.c, c/systemc/token_ring.10_false-unreach-call_false-termination.cil.c, c/systemc/token_ring.11_false-unreach-call_false-termination.cil.c, c/systemc/token_ring.12_false-unreach-call_false-termination.cil.c, c/systemc/token_ring.13_false-unreach-call_false-termination.cil.c, c/systemc/token_ring.14_false-unreach-call_false-termination.cil.c, c/systemc/token_ring.15_false-unreach-call_false-termination.cil.c
The systemc token-ring tasks with verdict false-unreach-call contained uses of uninitialized variables declared as `int tmp_var ;`. This pull request fixes the undefined behavior caused by this by initializing the variables using `__VERIFIER_nondet_int()`.
=> Fix undefined behavior in systemc token-ring tasks

c/reducercommutativity/rangesum05_false-unreach-call.c, c/reducercommutativity/rangesum05_false-unreach-call.i, c/reducercommutativity/rangesum10_false-unreach-call.c, c/reducercommutativity/rangesum10_false-unreach-call.i, c/reducercommutativity/rangesum20_false-unreach-call.c, c/reducercommutativity/rangesum20_false-unreach-call.i, c/reducercommutativity/rangesum40_false-unreach-call.c, c/reducercommutativity/rangesum40_false-unreach-call.i, c/reducercommutativity/rangesum60_false-unreach-call.c, c/reducercommutativity/rangesum60_false-unreach-call.i, c/reducercommutativity/rangesum_false-unreach-call.c, c/reducercommutativity/rangesum_false-unreach-call.i
Fix a bug from #451, where the instead of assignments, expression statements were used and the array cells were not actually initialized.
=> Fix a bug from #451

c/check.py
This checks for
- unknown properties
- several verdicts for same property
- combination of `false-unreach-call` and `true-valid-memsafety` (https://github.com/sosy-lab/sv-benchmarks/issues/387#issuecomment-269199236)
- combination of multiple memsafety-related verdicts (https://github.com/sosy-lab/sv-benchmarks/issues/387#issuecomment-268516464)
- combination of a property for undefined behavior with any other property (cf. open question from https://github.com/sosy-lab/sv-benchmarks/issues/322#issuecomment-326359820)
Fixes #322 and fixes #387.
=> Add sanity checks for duplicate and contradicting properties

c/ldv-regression/volatile_alias.c_true-unreach-call.i
There was an assignment of the address of a volatile int to an int*
pointer, loosing the volatile modifier.
To keep the original intention of the benchmark,
there is now an assignment of the address of an int to a volatile int*.
I inferred the original intent from https://github.com/sosy-lab/sv-benchmarks/blob/12874bd05c3373f3154518e5b60bf8a6598a9254/ldv-regression-1/volatile_alias.c#L1
=> Fix undefined behavior in volatile_alias.c

c/heap-manipulation/dll_of_dll_false-unreach-call_false-valid-memcleanup.c, c/heap-manipulation/dll_of_dll_false-unreach-call_false-valid-memcleanup.i, c/heap-manipulation/dll_of_dll_true-unreach-call_true-valid-memsafety.c, c/heap-manipulation/dll_of_dll_true-unreach-call_true-valid-memsafety.i
(*insert_fnc)() declares insert_fnc as a function pointer with an
unknown number and type of parameters, not with an empty list of
parameters.  This may be an underspecification that can lead to possible
undefined behaviour.  This commit fixes that in two benchmarks of
Predator.
Should solve issue #462 reported by @PhilippWendler .
=> heap-manipulation: resolve function pointer with unspecified arguments (#462)

c/array-memsafety/cstrchr_unsafe_false-valid-deref.c, c/array-memsafety/cstrchr_unsafe_false-valid-deref.i, c/array-memsafety/cstrlen_unsafe_false-valid-deref.c, c/array-memsafety/cstrlen_unsafe_false-valid-deref.i, c/array-memsafety/cstrpbrk_unsafe_false-valid-deref.c, c/array-memsafety/cstrpbrk_unsafe_false-valid-deref.i, c/termination-crafted-lit-todo/cstrncmp_true-termination.c, c/termination-crafted-lit-todo/strchr_true-termination.c, c/termination-crafted-lit/cstrcmp_true-termination_true-no-overflow.c, c/termination-crafted-lit/cstrcspn_true-termination_true-no-overflow.c, c/termination-crafted-lit/cstrlen_true-termination_true-no-overflow.c, c/termination-crafted-lit/cstrncmp_false-no-overflow.c, c/termination-crafted-lit/cstrpbrk_true-termination_true-no-overflow.c, c/termination-crafted-lit/cstrspn_true-termination_true-no-overflow.c, c/termination-crafted-lit/strchr_true-no-overflow.c, c/termination-recursive-malloc/rec_strcopy_malloc2_true-termination.c, c/termination-recursive-malloc/rec_strcopy_malloc2_true-termination.c.i, c/termination-recursive-malloc/rec_strcopy_malloc_true-termination.c, c/termination-recursive-malloc/rec_strcopy_malloc_true-termination.c.i, c/termination-recursive-malloc/rec_strlen_malloc_true-termination.c, c/termination-recursive-malloc/rec_strlen_malloc_true-termination.c.i
While SV-COMP rules explicitly list the suffixes that are guaranteed to yield
non-deterministic values and have no side effects, lots of benchmarks do use
different suffixes as well (but stick with the "non-det return value and no side
effects"). The use of __VERIFIER_nondet_String violated these assumptions; as an
implementation was provided, there was no need to use a __VERIFIER_nondet prefix
anyway.
=> Avoid using __VERIFIER_nondet prefix for functions with side effects

c/bitvector/byte_add_1_false-no-overflow.c, c/bitvector/byte_add_1_false-no-overflow.i, c/bitvector/byte_add_1_true-unreach-call_true-no-overflow.i, c/bitvector/byte_add_2_false-no-overflow.c, c/bitvector/byte_add_2_false-no-overflow.i, c/bitvector/byte_add_2_true-unreach-call_true-no-overflow.c, c/bitvector/byte_add_2_true-unreach-call_true-no-overflow.i, c/bitvector/byte_add_false-no-overflow.c, c/bitvector/byte_add_false-no-overflow.i, c/bitvector/byte_add_false-unreach-call_true-no-overflow.c, c/bitvector/byte_add_false-unreach-call_true-no-overflow.i
Three tasks of similar fashion contain overflows in left-shifts:
the expression (r3 << 24U) triggers undefined behavior if the unsigned char r3 is larger than 127, because r3 gets promoted to int and r3<<24U will exceed INT_MAX (see ISO/IEC 9899:2011 6.5.7#4).
r3 does not get promoted to unsigned int as one might think, because all its values fit into int (ISO/IEC 9899:2011 6.3.1.1#2) 
Now the question is whether this classifies as an overflow, since the term overflow is not strictly defined anywhere. If an overflow is undefined behavior caused in (arithmetic) operations with signed integer types, then this is obviously an overflow. Otherwise, this is still undefined behavior and needs to be fixed.
This pull request currently does the following:
- Fix the overflows by explicitly casting …
=> Fix labels for tasks with overflows in left-shift operations

c/loops/nec20_false-unreach-call_true-termination.c, c/loops/nec20_false-unreach-call_true-termination.i
Make sure that `j` is initialised since it is used in the following loop. Limit the value of `j` so that the subsequent code can't overflow.
=> Loops undef

c/array-memsafety/cstrchr_unsafe_false-valid-deref.c, c/array-memsafety/cstrchr_unsafe_false-valid-deref.i, c/array-memsafety/cstrpbrk_unsafe_false-valid-deref.c, c/array-memsafety/cstrpbrk_unsafe_false-valid-deref.i
Same fix as the one in 68cc7e62.
Signed-off-by: Mikhail Ramalho <mikhail.ramalho@gmail.com>
=> Fix memory leak in two benchmarks with false-valid-deref verdict

c/loops/s3_false-unreach-call.i, c/ssh/s3_clnt.blast.01_false-unreach-call.i.cil.c, c/ssh/s3_clnt.blast.01_true-unreach-call.i.cil.c, c/ssh/s3_clnt.blast.02_false-unreach-call.i.cil.c, c/ssh/s3_clnt.blast.02_true-unreach-call.i.cil.c, c/ssh/s3_clnt.blast.03_false-unreach-call.i.cil.c, c/ssh/s3_clnt.blast.03_true-unreach-call.i.cil.c, c/ssh/s3_clnt.blast.04_false-unreach-call.i.cil.c, c/ssh/s3_clnt.blast.04_true-unreach-call.i.cil.c
In all of these benchmarks if `s->version` is not initialised then the bevhaviour is undefined but includes a path that leads to the `((s->version & 65280) != 768)` condition being true which causes the program to immediately exit. A tool is free to choose this path given the undefined behaviour. These fixes initialise `s->version` so that this condition is defined.
In the s3 benchmark some other temporary variables are now initialised to remove some other warnings.
Fixes #488
=> Define s->version field in ssh client benchmarks

c/check.py
Since the split between memleak and memcleanup an allocated memory at
program exit would not be a memleak and thus not violate memsafety.
This was discussed in https://github.com/sosy-lab/sv-benchmarks/pull/513#issuecomment-344690477.
=> Adjust check for possible mem leaks at __VERIFIER_error calls to current rules

c/loops/terminator_02_true-unreach-call_true-termination.c, c/loops/terminator_02_true-unreach-call_true-termination.i
Replace the if-statements by assume statements to make the
loop body of terminator_02_true-unreach-call_true-termination.c
reachable and avoid signed overflows.
=> make the loop body of terminator_02_true reachable

c/loop-industry-pattern/ofuf_1_true-unreach-call.c, c/loop-industry-pattern/ofuf_2_true-unreach-call.c, c/loop-industry-pattern/ofuf_3_true-unreach-call.c, c/loop-industry-pattern/ofuf_4_true-unreach-call.c, c/loop-industry-pattern/ofuf_5_true-unreach-call.c
Add the assume statement as __VERIFIER_assume(y!=0)
for each operation of the type x/y to avoid undefined behavior
in the loop-industry-pattern benchmarks.
=> Add assumes to avoid undefined behaviour in loop-industry-pattern

c/busybox-1.22.0/date_false-unreach-call_true-no-overflow_true-valid-memsafety.c, c/busybox-1.22.0/date_false-unreach-call_true-no-overflow_true-valid-memsafety.i
stat() is a POSIX function. The definition used is taken from
the who benchmark, adjusted to use mtim field instead of atim field.
=> busybox: define stat() function in date benchmark

c/busybox-1.22.0/busybox_sv_comp-localtime_r.h, c/busybox-1.22.0/date_false-unreach-call_true-no-overflow_true-valid-memsafety.c, c/busybox-1.22.0/date_false-unreach-call_true-no-overflow_true-valid-memsafety.i, c/busybox-1.22.0/touch_false-unreach-call_true-no-overflow_true-valid-memsafety.c, c/busybox-1.22.0/touch_false-unreach-call_true-no-overflow_true-valid-memsafety.i
Add a definition of `localtime_r` which is a POSIX function.
This prevents reading uninitialized values.
As the argument of this function is always unbounded value,
ignore it and just fill the result struct with non-deterministic
values that represent "some valid time".
This PR depends on (or supersede) #525 as it contains also the commit from #525.
=> Busybox - define localtime_r

.travis.yml
Reverts sosy-lab/sv-benchmarks#543
@dbeyer 
The pull #543 request was not yet finished with the evaluation.
It seems that `ccache` does **not improve** the runtime of TravisCI for our repository.
=> Revert "Update travis.yml (for testing)"

c/busybox-1.22.0-todo/id-incomplete_true-no-overflow_true-valid-memsafety.i, c/busybox-1.22.0/busybox_sv_comp-getpwnam.h, c/busybox-1.22.0/chroot-incomplete_false-no-overflow.i, c/busybox-1.22.0/chroot-incomplete_true-no-overflow_true-valid-memsafety.i, c/busybox-1.22.0/ls-incomplete_false-no-overflow.i, c/busybox-1.22.0/ls-incomplete_false-unreach-call_true-no-overflow_true-valid-memsafety.i, c/busybox-1.22.0/whoami-incomplete_false-no-overflow.i, c/busybox-1.22.0/whoami-incomplete_true-no-overflow_true-valid-memsafety.i
There are some busybox tasks that have the wrong overflow labels due to the way the getpwnam function is modelled in c/busybox-1.22.0/busybox_sv_comp-getpwnam.h. The affected files are:
```
c/busybox-1.22.0/whoami-incomplete_false-no-overflow.i
c/busybox-1.22.0/ls-incomplete_false-no-overflow.i
c/busybox-1.22.0/chroot-incomplete_false-no-overflow.i
```
They should be excluded from the corresponding svcomp18 overflow category.
The whoami-incomplete_false-no-overflow.i task brought this issue up because Ultimate correctly classified this tasks as true-no-overflow in the official results for svcomp18 but got a -32 point penalty due to the wrong labeling. CPAchecker is also able to generate a proof for this for the case where the number of argv parameters is reduced from 10000 to 3.
In the …
=> Improve modelling of function getpwnam for busybox

c/NoOverflows-Other.set, c/psyco/psyco_abp_1_false-no-overflow.c, c/psyco/psyco_abp_1_false-unreach-call_false-termination_true-no-overflow.c, c/psyco/psyco_abp_1_true-unreach-call_false-termination_true-no-overflow.c
This PR fixes overflows in ``psyco_abp_1_false-unreach-call_false-termination.c`` and relabels the benchmark to ``true-unreach-call`` because the error location is not reachable.  
**Regarding the overflow**
@Heizmann created the file [psyco_abp_1_false-unreach-call_false-terminationExecutable.c.txt](https://github.com/sosy-lab/sv-benchmarks/files/1530249/psyco_abp_1_false-unreach-call_false-terminationExecutable.c.txt) contains an executable variant of the original benchmark that demonstrates the signed overflow. The following modifications were made.
1. We replaced all occurrences of __VERIFIER_nondet_int() by expressions.
2. All occurrences that do not occur on the execution that reveals the overflow were replaced by -23
3. We added a printf that shows a warning shortly before the …
=> relabel and fix overflow in psyco/psyco_abp_1_false-unreach-call_false-termination.c

c/ldv-linux-3.16-rc1/205_9a_array_safes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--arcnet--capmode.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-3.16-rc1/205_9a_array_safes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--arcnet--rfc1051.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-3.16-rc1/205_9a_array_safes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--wan--lapbether.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-3.16-rc1/205_9a_array_unsafes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--wan--hdlc_x25.ko-entry_point_true-unreach-call.cil.out.c
Four benchmarks from ``ldv-linux-3.16-rc1`` contained undefined behaviour (they dereference null pointers). This PR tries to fix all of these occurrences as far as Ultimate can detect them.  
Similar to sosy-lab/sv-benchmarks/pull/536 , we do this by replacing calls to ``ldv_zalloc`` with calls to a new function ``ldv_successful_zalloc`` that never returns a null pointer and additionally add ``__VERIFIER_assume`` statements in various places. 
The files in question are
* ldv-linux-3.16-rc1/205_9a_array_safes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--arcnet--capmode.ko-entry_point_true-unreach-call.cil.out.c
* ldv-linux-3.16-rc1/205_9a_array_safes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--arcnet--rfc1051.ko-entry_point_true-unreach-call.cil.out.c
* …
=> Fix undefined behavior due to dereferencing null pointer in 4 ldvs

c/ldv-consumption/32_7a_cilled_false-unreach-call_linux-3.8-rc1-drivers--media--rc--rc-core.ko-main.cil.out.c, c/ldv-consumption/32_7a_cilled_true-unreach-call_linux-3.8-rc1-32_7a-drivers--staging--speakup--speakup.ko-ldv_main4_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--input--misc--xen-kbdfront.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--input--touchscreen--egalax_ts.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--platform--x86--xo15-ebook.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3_false-termination.4-32_1-drivers--input--misc--ab8500-ponkey.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3_false-termination.4-32_1-drivers--input--misc--mpu3050.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3_false-termination.4-32_1-drivers--input--misc--pcf50633-input.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3_false-termination.4-32_1-drivers--input--misc--rotary_encoder.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3_false-termination.4-32_1-drivers--input--touchscreen--eeti_ts.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3_false-termination.4-32_1-drivers--input--touchscreen--max11801_ts.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3_false-termination.4-32_1-drivers--input--touchscreen--stmpe-ts.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--input--misc--ims-pcu.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---drivers--input--misc--ims-pcu.ko_false-unreach-call.cil.c
Sometimes kzalloc was used before it was declared (as static function).
This patch moves the declaration before the use.
A follow-up for #556
=> ldv-benchmarks: fix kzalloc declarations

c/termination-crafted/Cairo_step2_true-no-overflow_false-termination_true-valid-memsafety.c
__VERIFIER_nondet_uint() should return an unsigned integer
(This is just a random fix, nothing to do with the inspection period)
=> fix wrong declaration

c/ldv-sets/test_add_false-unreach-call_true-termination.i, c/ldv-sets/test_add_true-unreach-call_true-termination.i, c/ldv-sets/test_mutex_double_lock_false-unreach-call_true-termination.i, c/ldv-sets/test_mutex_double_unlock_false-unreach-call.i, c/ldv-sets/test_mutex_true-unreach-call.i, c/ldv-sets/test_mutex_unbounded_false-unreach-call.i, c/ldv-sets/test_mutex_unbounded_true-unreach-call.i, c/ldv-sets/test_mutex_unlock_at_exit_false-unreach-call.i
Several signatures of VERIFIER functions (namely `__VERIFIER_error` and `__VERIFIER_assume`) were wrong, since they were returning `int` instead of being `void`.
=> Fixed signatures of VERIFIER functions

c/float-benchs/sqrt_poly2_false-unreach-call.c
I did this to avoid confusion with the standard library sqrt function.
=> Renamed sqrt function definition into sqrt_custom

c/ldv-sets/model/ldv.h
Same as PR #569, but fixes the header instead of the preprocessed files.
=> Fix wrong definitions

c/MemSafety-Other.set, c/memsafety-ext3/LICENSE.txt, c/memsafety-ext3/Makefile, c/memsafety-ext3/README.txt, c/memsafety-ext3/derefAfterFree1_false-valid-deref.c, c/memsafety-ext3/derefAfterFree2_false-valid-deref.c, c/memsafety-ext3/derefInLoop1_false-valid-deref.c, c/memsafety-ext3/freeAlloca_false-valid-free.c, c/memsafety-ext3/getNumbers1_false-valid-deref.c, c/memsafety-ext3/getNumbers1_true-valid-memsafety.c, c/memsafety-ext3/getNumbers2_false-valid-deref.c, c/memsafety-ext3/getNumbers3_true-valid-memsafety.c, c/memsafety-ext3/getNumbers4_false-valid-deref.c, c/memsafety-ext3/getNumbers4_true-valid-memsafety.c, c/memsafety-ext3/naturalNumbers1_false-valid-deref.c, c/memsafety-ext3/realloc1_false-valid-deref.c, c/memsafety-ext3/scopes1_false-valid-deref.c, c/memsafety-ext3/scopes2_false-valid-deref.c, c/memsafety-ext3/scopes3_false-valid-deref.c, c/memsafety-ext3/scopes4_false-valid-deref.c, c/memsafety-ext3/scopes4_true-valid-memsafety.c, c/memsafety-ext3/scopes5_false-valid-deref.c
New benchmarks for MemSafety category that were used by Symbiotic during testing and revealed some new errors in the tool that did not appear when testing on SV-COMP benchmarks.
Preprocessed files are not present as no file contains any preprocessor directives.
=> New MemSafety benchmarks

c/ReachSafety-Heap.set, c/heap-data/LICENSE, c/heap-data/Makefile, c/heap-data/README, c/heap-data/calendar_true-unreach-call.c, c/heap-data/calendar_true-unreach-call.i, c/heap-data/cart_true-unreach-call.c, c/heap-data/cart_true-unreach-call.i, c/heap-data/hash_fun_true-unreach-call.c, c/heap-data/hash_fun_true-unreach-call.i, c/heap-data/min_max_true-unreach-call.c, c/heap-data/min_max_true-unreach-call.i, c/heap-data/packet_filter_true-unreach-call.c, c/heap-data/packet_filter_true-unreach-call.i, c/heap-data/process_queue_true-unreach-call.c, c/heap-data/process_queue_true-unreach-call.i, c/heap-data/quick_sort_split_true-unreach-call.c, c/heap-data/quick_sort_split_true-unreach-call.i, c/heap-data/running_example_true-unreach-call.c, c/heap-data/running_example_true-unreach-call.i, c/heap-data/shared_mem1_true-unreach-call.c, c/heap-data/shared_mem1_true-unreach-call.i, c/heap-data/shared_mem2_true-unreach-call.c, c/heap-data/shared_mem2_true-unreach-call.i
=> Add heap-data benchmarks

c/pthread/README.txt, c/pthread/triangular-longer_false-unreach-call.c, c/pthread/triangular-longer_false-unreach-call.i, c/pthread/triangular-longer_true-unreach-call.c, c/pthread/triangular-longer_true-unreach-call.i, c/pthread/triangular-longest_false-unreach-call.c, c/pthread/triangular-longest_false-unreach-call.i, c/pthread/triangular-longest_true-unreach-call.c, c/pthread/triangular-longest_true-unreach-call.i, c/pthread/triangular_false-unreach-call.c, c/pthread/triangular_false-unreach-call.i, c/pthread/triangular_true-unreach-call.c, c/pthread/triangular_true-unreach-call.i
Partial PR with new tasks using pthreads, extracted from #573.
=> adding new simple concurrency benchmarks.

c/MemSafety-Concurrency.cfg, c/MemSafety-Concurrency.set, c/pthread-memsafety/LICENSE.txt, c/pthread-memsafety/Makefile, c/pthread-memsafety/README, c/pthread-memsafety/fillarray_false-valid-deref.c, c/pthread-memsafety/fillarray_false-valid-deref.i, c/pthread-memsafety/fillarray_true-valid-memsafety.c, c/pthread-memsafety/fillarray_true-valid-memsafety.i, c/pthread-memsafety/list1_false-valid-deref.c, c/pthread-memsafety/list1_false-valid-deref.i, c/pthread-memsafety/list2_false-valid-deref.c, c/pthread-memsafety/list2_false-valid-deref.i
Partial PR for the combination of threads and memory-safety, extracted from #573.
=> adding new benchmarks for the combination of MemSafety and Threads.

c/MemSafety-Arrays.set, c/array-memsafety-realloc/LICENSE.txt, c/array-memsafety-realloc/Makefile, c/array-memsafety-realloc/README, c/array-memsafety-realloc/array-realloc_false-valid-deref.c, c/array-memsafety-realloc/array-realloc_false-valid-deref.i, c/array-memsafety-realloc/array-realloc_true-valid-memsafety.c, c/array-memsafety-realloc/array-realloc_true-valid-memsafety.i
Partial PR for `array-reallocation` extracted from #573.
=> adding new simple array benchmarks with reallocation.

c/array-tiling/poly2_true-unreach-call.c, c/array-tiling/poly2_true-unreach-call.i
It returns int and not short, and so I changed it to int.
=> Fixed signature of __VERIFIER_nondet_int

c/pthread/stack_false-unreach-call.c, c/pthread/stack_false-unreach-call.i, c/pthread/stack_longer_false-unreach-call.c, c/pthread/stack_longer_false-unreach-call.i, c/pthread/stack_longer_true-unreach-call.c, c/pthread/stack_longer_true-unreach-call.i, c/pthread/stack_longest_false-unreach-call.c, c/pthread/stack_longest_false-unreach-call.i, c/pthread/stack_longest_true-unreach-call.c, c/pthread/stack_longest_true-unreach-call.i, c/pthread/stack_true-unreach-call.c, c/pthread/stack_true-unreach-call.i, c/seq-pthread/cs_stack_false-unreach-call.c, c/seq-pthread/cs_stack_false-unreach-call.i, c/seq-pthread/cs_stack_true-unreach-call.c, c/seq-pthread/cs_stack_true-unreach-call.i
Simplifying some files by replacing statement `tmp=nondet_int()%N` with simpler assumption `tmp=nondet_int();assume(0<=tmp&&tmp<N)`.
Most verifiers handle linear arithmetic much easier than modulo operation.
=> replace `MODULO` with proper `VERIFIER_assume`.

c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--media--usb--dvb-usb--dvb-usb-dw2102.ko-entry_point_false-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--net--ethernet--intel--i40e--i40e.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--net--wireless--mwifiex--mwifiex.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--media--usb--dvb-usb--dvb-usb-opera.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--media--usb--dvb-usb-v2--dvb-usb-lmedm04.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--net--ethernet--intel--i40e--i40e.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--net--wireless--mwifiex--mwifiex.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--bluetooth--hci_uart.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--ethernet--amd--xgbe--amd-xgbe.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--ethernet--natsemi--natsemi.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--fddi--defxx.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--scsi--bnx2i--bnx2i.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--tty--synclink_gt.ko-entry_point_true-unreach-call.cil.out.c, c/ntdrivers/cdaudio_true-unreach-call.i.cil.c, c/ntdrivers/diskperf_false-unreach-call.i.cil.c, c/ntdrivers/diskperf_true-unreach-call.i.cil.c, c/ntdrivers/floppy2_true-unreach-call_true-termination.i.cil.c, c/ntdrivers/floppy_true-unreach-call_true-valid-memsafety.i.cil.c, c/ntdrivers/kbfiltr_false-unreach-call.i.cil.c, c/ntdrivers/parport_false-unreach-call.i.cil.c, c/ntdrivers/parport_true-unreach-call.i.cil.c
These benchmarks call memcpy with overlapping source and destination
areas, which is undefined behaviour according to POSIX.1-2008 and the C
standard. The CBMC tool therefore gives a result of false, including a
counterexample, on the benchmarks that are expected to return true.
These benchmarks, being examples from device drivers, were supposedly
written with overlapping source and memory regions intentionally, and
the code 'works' in practice. However, SV-COMP participants should
arguably not be expected to get the right result for benchmarks relying
on quirky, non-standards-conformant hardware behaviour.
Counterexamples for all the deleted files are available on [this page](https://karkhaz.com/tmp/log-matches).
=> Replace memcpy with memmove for overlapping memory

c/ldv-linux-3.14-races/linux-3.14--drivers--media--platform--marvell-ccic--cafe_ccic.ko_false-unreach-call.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--nsc-ircc.ko_false-unreach-call.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--w83977af_ir.ko_false-unreach-call.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--spi--spi-tegra20-slink.ko_false-unreach-call.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--adutux.ko_false-unreach-call.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--iowarrior.ko_false-unreach-call.cil.i, c/ldv-linux-3.14-races/model/common.env.c, c/ldv-linux-3.14-races/model/linux-3.14--drivers--media--platform--marvell-ccic--cafe_ccic.ko_false-unreach-call.env.c, c/ldv-linux-3.14-races/model/linux-3.14--drivers--net--irda--nsc-ircc.ko_false-unreach-call.env.c, c/ldv-linux-3.14-races/model/linux-3.14--drivers--net--irda--w83977af_ir.ko_false-unreach-call.env.c, c/ldv-linux-3.14-races/model/linux-3.14--drivers--spi--spi-tegra20-slink.ko_false-unreach-call.env.c, c/ldv-linux-3.14-races/model/linux-3.14--drivers--usb--misc--adutux.ko_false-unreach-call.env.c, c/ldv-linux-3.14-races/model/linux-3.14--drivers--usb--misc--iowarrior.ko_false-unreach-call.env.c
This fixes an obvious typo in the name of the standard `__VERIFIER_*` functions.
=> fix typo in function names: __VEFIRIER -> __VERIFIER

c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--media--usb--dvb-usb--dvb-usb-dw2102.ko-entry_point_false-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--net--ethernet--intel--i40e--i40e.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--net--wireless--mwifiex--mwifiex.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--media--usb--dvb-usb--dvb-usb-opera.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--media--usb--dvb-usb-v2--dvb-usb-lmedm04.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--net--ethernet--intel--i40e--i40e.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--net--wireless--mwifiex--mwifiex.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--bluetooth--hci_uart.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--ethernet--amd--xgbe--amd-xgbe.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--ethernet--natsemi--natsemi.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--fddi--defxx.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--scsi--bnx2i--bnx2i.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--tty--synclink_gt.ko-entry_point_true-unreach-call.cil.out.c
This fixes a problem introduced in 55d4083, where some calls to memcpy
were converted to calls to memmove, but the files did not have a
prototype for memmove.
=> Add memmove prototypes to LDV benchmarks

c/ldv-linux-3.14-races/linux-3.14--drivers--media--platform--marvell-ccic--cafe_ccic.ko_false-unreach-call.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--media--platform--marvell-ccic--cafe_ccic.ko_false-unreach-call.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--nsc-ircc.ko_false-unreach-call.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--nsc-ircc.ko_false-unreach-call.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--w83977af_ir.ko_false-unreach-call.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--w83977af_ir.ko_false-unreach-call.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--spi--spi-tegra20-slink.ko_false-unreach-call.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--spi--spi-tegra20-slink.ko_false-unreach-call.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--adutux.ko_false-unreach-call.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--adutux.ko_false-unreach-call.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--iowarrior.ko_false-unreach-call.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--iowarrior.ko_false-unreach-call.cil.i
A number of fixes related to six benchmarks in ldv-linux-3.14-races/. Missed unlock functions, some initializations, fix clang warnings.
=> Fixes of ldv-linux-3.14-races/ benchmarks

c/MemSafety-Heap.set, c/MemSafety-LinkedLists.set
Some tasks have not yet been included in the corresponding set-files for memory-safety. Was there a reason for this?
I assume that "mem-cleanup" is a valid property for this year, because it appears in the [rules](https://sv-comp.sosy-lab.org/2019/rules.php).
=> include several 'mem-cleanup'-files in set-files.

c/ConcurrencySafety-Main.set, c/Systems_DeviceDriversLinux64_ConcurrencySafety.set, c/ldv-linux-3.14-races/Makefile, c/ldv-linux-3.14-races/linux-3.14--drivers--media--platform--marvell-ccic--cafe_ccic.ko_false-unreach-call.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--media--platform--marvell-ccic--cafe_ccic.ko_false-unreach-call.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--nsc-ircc.ko_false-unreach-call.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--nsc-ircc.ko_false-unreach-call.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--w83977af_ir.ko_false-unreach-call.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--w83977af_ir.ko_false-unreach-call.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--spi--spi-tegra20-slink.ko_false-unreach-call.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--spi--spi-tegra20-slink.ko_false-unreach-call.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--adutux.ko_false-unreach-call.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--adutux.ko_false-unreach-call.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--iowarrior.ko_false-unreach-call.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--iowarrior.ko_false-unreach-call.cil.i
The corresponding benchmarks are not new, they were placed into subcategory of software systems. The suggestion is to move them into main concurrency category.
=> Add ldv races into concurrency category

c/MemSafety-MemCleanup.prp
This is a follow up completion step.
The link is not really necessary, but it was done this way for the other categories.
Belongs to issue #633.
=> Add symbolic link MemSafety-MemCleanup.prp to property for convenience and consistency

c/ConcurrencySafety-Main.set, c/ldv-linux-3.14-races/linux-3.14--drivers--media--platform--marvell-ccic--cafe_ccic.ko_true-unreach-call.cil.i
Add an initialization of a global variable with a nondeterministic value. Add an old version of the benchmark as 'true_unreach_call'.
=> Add a proper initialization to correspond the false verdict

c/termination-crafted-lit/HeizmannHoenickeLeikePodelski-ATVA2013-Fig7_false-no-overflow.c
There was an undefined behaviour in `termination-crafted-lit/HeizmannHoenickeLeikePodelski-ATVA2013-Fig7_false-no-overflow.c` since the values of the array `a` were uninitialized. This commit fixes the problem.
=> Get rid of undefined behaviour in termination-crafted-lit

c/pthread/triangular-longer_false-unreach-call.c, c/pthread/triangular-longer_false-unreach-call.i, c/pthread/triangular-longer_true-unreach-call.c, c/pthread/triangular-longer_true-unreach-call.i, c/pthread/triangular-longest_false-unreach-call.c, c/pthread/triangular-longest_false-unreach-call.i, c/pthread/triangular-longest_true-unreach-call.c, c/pthread/triangular-longest_true-unreach-call.i, c/pthread/triangular_false-unreach-call.c, c/pthread/triangular_false-unreach-call.i, c/pthread/triangular_true-unreach-call.c, c/pthread/triangular_true-unreach-call.i
possible fix for #649.
A different calculation avoids overflows and matches the intention of the benchmark.
=> change pthread tasks to avoid overflows.

java/README.md, java/common/org/sosy_lab/sv_benchmarks/Verifier.java
- [n/a] programs added to new and [appropriately named](https://github.com/sosy-lab/sv-benchmarks/blob/master/CONTRIBUTING.md#directory-structure-and-names) directory
- [n/a] programs added to a `.set` file of an existing category, or new sub-category established (if justified)
- [n/a] intended property matches the corresponding `.prp` file
- [n/a] expected answer in file names according to [convention](https://github.com/sosy-lab/sv-benchmarks/blob/master/CONTRIBUTING.md#properties)
- [n/a] [architecture](https://github.com/sosy-lab/sv-benchmarks/blob/master/CONTRIBUTING.md#architecture) (32 bit vs. 64 bit) matches the corresponding `.cfg` file
- [n/a] original sources present
- [n/a] [preprocessed](https://github.com/sosy-lab/sv-benchmarks/blob/master/CONTRIBUTING.md#preprocessing) …
=> Introduce Java verifier class

c/pthread/fib_bench_false-unreach-call.c, c/pthread/fib_bench_false-unreach-call.i, c/pthread/fib_bench_longer_false-unreach-call.c, c/pthread/fib_bench_longer_false-unreach-call.i, c/pthread/fib_bench_longer_true-unreach-call.c, c/pthread/fib_bench_longer_true-unreach-call.i, c/pthread/fib_bench_longest_false-unreach-call.c, c/pthread/fib_bench_longest_false-unreach-call.i, c/pthread/fib_bench_longest_true-unreach-call.c, c/pthread/fib_bench_longest_true-unreach-call.i, c/pthread/fib_bench_true-unreach-call.c, c/pthread/fib_bench_true-unreach-call.i, c/pthread/triangular-longer_false-unreach-call.c, c/pthread/triangular-longer_false-unreach-call.i, c/pthread/triangular-longer_true-unreach-call.c, c/pthread/triangular-longer_true-unreach-call.i, c/pthread/triangular-longest_false-unreach-call.c, c/pthread/triangular-longest_false-unreach-call.i, c/pthread/triangular-longest_true-unreach-call.c, c/pthread/triangular-longest_true-unreach-call.i, c/pthread/triangular_false-unreach-call.c, c/pthread/triangular_false-unreach-call.i, c/pthread/triangular_true-unreach-call.c, c/pthread/triangular_true-unreach-call.i
fixes for #657.
@zvonimir :
Could you review the changes?
For the variables `i` and `j` in the main function I assume that we do not need locking, because the variables are only read, not written there. Same opinion?
=> Fix concurrency data races

c/array-multidimensional/transpose-u_true-unreach-call.c, c/array-multidimensional/transpose-u_true-unreach-call.i
=> change transpose-u_true-unreach-call assertion

java/jpf-regression/ExSymExe12_true/Main.java, java/jpf-regression/ExSymExe14_true/Main.java, java/jpf-regression/ExSymExe15_true/Main.java, java/jpf-regression/ExSymExeF2L_false/Main.java, java/jpf-regression/ExSymExeI2D_true/Main.java, java/jpf-regression/ExSymExeLongBytecodes_true/Main.java, java/jpf-regression/ExSymExeSimple_true/Main.java
When adapting these benchmarks to use Verifier (a3848b97) I inadvertently introduced some overflow bugs, which would change the expected outcome. These are fixed here.
=> Fix overflow bugs introduced by using Verifier

java/jpf-regression/ExSymExe6_false/Main.java
This PR should fix a division by zero from ExSymExe6_false.
=> Removed division by zero from ExSymExe6_false

java/jbmc-regression/iarith2/Main.java
Somehow the source-code formatter that was used in that commit introduced syntax errors.
=> fix broken Java code from a61b71c2

java/jpf-regression/ExSymExeFNEG_true/Main.java
Added additional check in ExSymExeFNEG_true to ensure that the
`test` method is called when `x` is a positive number and is not a NaN.
=> Check for positive floating-point numbers in ExSymExeFNEG_true

c/busybox-1.22.0/stty_false-no-overflow.c, c/busybox-1.22.0/stty_false-no-overflow.i, c/busybox-1.22.0/stty_false-unreach-call_true-no-overflow_true-valid-memsafety.c, c/busybox-1.22.0/stty_false-unreach-call_true-no-overflow_true-valid-memsafety.i
The variable "arg" is of type "const char*" anyway, so the existing cast was unnecessary.
Adding a cast to "const unsigned char*" is valid because all pointers can be converted to pointers to character types (C11 §6.3.2.3 (7)).
Subsequent reads from this pointer are also allowed (§6.5 (7)).
This fixes #675, which contains more explanation on why I think this is necessary.
=> Fix incompatible assignment in busybox-1.22.0/stty*

c/array-examples/standard_partition_false-unreach-call_ground.c, c/array-examples/standard_partition_false-unreach-call_ground.i
This benchmark read values from uninitialized array on stack.
=> arrays: fix standard_partition benchmark

c/MemSafety-Other.set, c/loops/invert_string_false-unreach-call_true-termination.i, c/loops/invert_string_false-valid-deref.c
Fix an invalid dereference in a file (described in the commit message). Move the wrong version of this file into a new directory. When another phase of SV-COMP is here, we can move it back and add it into MemSafety category.
=> Memsafety fixes

c/seq-pthread/cs_lazy_false-unreach-call_true-termination.c, c/seq-pthread/cs_lazy_false-unreach-call_true-termination.i
Remove read from uninitialized variable (initialize the variable with call to __VERIFIER_nondet)
=> cs_lazy: fix read from uninitialized variable

c/pthread-divine/condvar_spurious_wakeup_false-unreach-call.c, c/pthread-divine/condvar_spurious_wakeup_false-unreach-call.i
Conditional variables and mutexes must be initialised before use (see pthread documentation, e.g. pthread_mutex_lock()).
=> Adding missing init stmt for lock and the conditional variables

c/loop-acceleration/array_false-unreach-call3_true-termination.c, c/loop-acceleration/array_false-unreach-call3_true-termination.i
Fixes possible invalid dereference in termination benchmark.
=> Fix invalid dereference in termination benchmark

c/seq-pthread/cs_fib_false-unreach-call.c, c/seq-pthread/cs_fib_false-unreach-call.i, c/seq-pthread/cs_fib_longer_false-unreach-call.c, c/seq-pthread/cs_fib_longer_false-unreach-call.i, c/seq-pthread/cs_lazy_false-unreach-call_true-termination.c, c/seq-pthread/cs_lazy_false-unreach-call_true-termination.i, c/seq-pthread/cs_stateful_false-unreach-call_true-termination.c, c/seq-pthread/cs_stateful_false-unreach-call_true-termination.i
Fix reads of uninitialized (automatic storage) variables, as such reads are undefined behavior. This PR fixes this problem in these benchmarks:
```
seq-pthread/cs_fib_false-unreach-call.i
seq-pthread/cs_fib_longer_false-unreach-call.i
seq-pthread/cs_lazy_false-unreach-call_true-termination.i
seq-pthread/cs_stateful_false-unreach-call_true-termination.i
```
The "true" versions of these benchmarks contain the fix already, but the "false" versions did not have it for some reason.
=> Remove uninitialized reads from sequentialized benchmarks.

c/ldv-commit-tester/m0_false-unreach-call_drivers-usb-gadget-g_printer-ko--106_1a--2b9ec6c-1.i, c/ldv-commit-tester/m0_false-unreach-call_drivers-usb-gadget-g_printer-ko--106_1a--2b9ec6c.i, c/ldv-commit-tester/m0_true-unreach-call_drivers-usb-gadget-g_printer-ko--106_1a--2b9ec6c.i, c/ldv-commit-tester/main3_true-unreach-call_arch-x86-oprofile-oprofile-ko--131_1a--79db8ef-1.i, c/ldv-commit-tester/main3_true-unreach-call_arch-x86-oprofile-oprofile-ko--131_1a--79db8ef.i, c/ldv-commit-tester/main4_true-unreach-call_arch-x86-oprofile-oprofile-ko--131_1a--79db8ef-1.i, c/ldv-commit-tester/main4_true-unreach-call_arch-x86-oprofile-oprofile-ko--131_1a--79db8ef.i, c/ldv-consumption/32_7a_cilled_false-unreach-call_linux-3.8-rc1-drivers--media--usb--cpia2--cpia2.ko-main.cil.out.i, c/ldv-consumption/32_7a_cilled_true-unreach-call_linux-3.8-rc1-32_7a-drivers--gpu--drm--ttm--ttm.ko-ldv_main5_sequence_infinite_withcheck_stateful.cil.out.i, c/ldv-consumption/32_7a_cilled_true-unreach-call_linux-3.8-rc1-32_7a-drivers--misc--sgi-xp--xpc.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i, c/ldv-consumption/32_7a_cilled_true-unreach-call_linux-3.8-rc1-32_7a-drivers--mmc--host--sdhci.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i, c/ldv-consumption/32_7a_cilled_true-unreach-call_linux-3.8-rc1-32_7a-drivers--tty--mxser.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i, c/ldv-consumption/32_7a_cilled_true-unreach-call_linux-3.8-rc1-32_7a-sound--core--snd-rawmidi.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i, c/ldv-consumption/32_7a_cilled_true-unreach-call_linux-3.8-rc1-drivers--media--firewire--firedtv.ko-main.cil.out.i, c/ldv-consumption/32_7a_cilled_true-unreach-call_linux-3.8-rc1-drivers--misc--sgi-xp--xpc.ko-main.cil.out.i, c/ldv-linux-3.0/usb_urb-drivers-vhost-vhost_net.ko_true-unreach-call.cil.out.i, c/ldv-linux-3.12-rc1/linux-3.12-rc1.tar.xz-144_2a-drivers--media--usb--stkwebcam--stkwebcam.ko-entry_point_false-unreach-call.cil.out.i, c/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3_false-termination.4-32_1-drivers--usb--serial--mos7840.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i, c/ldv-linux-3.4-simple/32_7_cilled_false-unreach-call_const_ok_linux-32_1-drivers--input--mousedev_true-termination.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i, c/ldv-linux-3.4-simple/32_7_cilled_false-unreach-call_const_ok_linux-32_1-drivers--vhost--vhost_net.ko-ldv_main1_sequence_infinite_withcheck_stateful.cil.out.i, c/ldv-linux-3.4-simple/43_1a_cilled_false-unreach-call_ok_linux-43_1a-drivers--misc--sgi-xp--xpc.ko-ldv_main3_sequence_infinite_withcheck_stateful.cil.out.i, c/ldv-linux-3.4-simple/43_1a_cilled_true-unreach-call_ok_nondet_linux-43_1a-drivers--usb--serial--mos7840_false-termination.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--md--raid456.ko-entry_point_true-unreach-call.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--md--raid456.ko-entry_point_false-unreach-call.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--md--raid456.ko-entry_point_true-unreach-call.cil.out.i, c/ldv-validator-v0.6/linux-stable-2b9ec6c-1-106_1a-drivers--usb--gadget--g_printer.ko-entry_point_false-unreach-call.cil.out.i, c/ldv-validator-v0.8/linux-stable-2b9ec6c-1-106_1a-drivers--usb--gadget--g_printer.ko-entry_point_ldv-val-v0.8_false-unreach-call.cil.out.i
Running gcc -E -P had resulted in files with whitespace differences. No changes
other than whitespace in memcpy declarations in this commit.
This is just cleanup to make sure future PRs are not polluted with whitespace changes.
=> Whitespace change only: fix preprocessing difference

c/pthread-lit/fkp2014_true-unreach-call.i
The preprocessor removes all comments.
=> Remove commented line from supposedly preprocessed file

c/.Dockerfile.preprocessing-consistency, c/compare.sh
Through this PR, the `compare.sh` CI check actually parses the task definition file
to get the input file, instead of using a heuristic based on file names.
=> Compare parses yml

c/ssh-simplified/s3_clnt_1.cil-1.c, c/ssh-simplified/s3_clnt_1.cil-2.c, c/ssh-simplified/s3_clnt_2.cil-1.c, c/ssh-simplified/s3_clnt_2.cil-2.c, c/ssh-simplified/s3_clnt_3.cil-1.c, c/ssh-simplified/s3_clnt_3.cil-3.c, c/ssh-simplified/s3_clnt_4.cil-1.c, c/ssh-simplified/s3_srvr_1.cil-1.c, c/ssh-simplified/s3_srvr_1.cil-2.c, c/ssh-simplified/s3_srvr_10.cil.c, c/ssh-simplified/s3_srvr_11.cil.c, c/ssh-simplified/s3_srvr_12.cil.c, c/ssh-simplified/s3_srvr_13.cil.c, c/ssh-simplified/s3_srvr_14.cil.c, c/ssh-simplified/s3_srvr_2.cil-1.c, c/ssh-simplified/s3_srvr_2.cil-2.c, c/ssh-simplified/s3_srvr_3.cil.c, c/ssh-simplified/s3_srvr_4.cil.c, c/ssh-simplified/s3_srvr_6.cil-1.c, c/ssh-simplified/s3_srvr_6.cil-2.c, c/ssh-simplified/s3_srvr_7.cil.c, c/ssh-simplified/s3_srvr_8.cil.c
It is quite easy to see that the variable `s__init_buf___0` is read without being initialized in this benchmarks, but I confirmed this on a couple of them using MSan.  I discovered this since the Test-Comp validator seemed to incorrectly replay some test cases.
=>  Removed unitialized accesses from several related benchmarks in ssh-simplified

c/loop-acceleration/simple_2-1.c, c/loop-acceleration/simple_2-2.c, c/loop-acceleration/simple_3-1.c, c/loop-acceleration/simple_3-2.c
Fix initialization of variables in `simple` benchmark from loop-acceleration.
=> loop-acceleration - simple: fix variables initialization

c/array-multidimensional/copy-partial-3-u.c
Occurs with gcc 8.3.0 [-Werror=tautological-compare]
=> fix: error: self-comparison always evaluates to true

c/ldv-consumption/32_7a_cilled_linux-3.8-rc1-32_7a-drivers--gpu--drm--ttm--ttm.ko-ldv_main5_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-consumption/32_7a_cilled_linux-3.8-rc1-32_7a-drivers--gpu--drm--ttm--ttm.ko-ldv_main5_sequence_infinite_withcheck_stateful.cil.out.i
SMACK reports false bugs for this driver due to accesses to
unallocated or uninitialized memory. This is addressing
the problem.
=> Added allocation and initialization to avoid undefined behaviors

c/array-memsafety/openbsd_cmemrchr-alloca-2.c, c/array-memsafety/openbsd_cmemrchr-alloca-2.i, c/array-memsafety/openbsd_cmemrchr-alloca-2.yml, c/termination-memory-alloca/openbsd_cmemrchr-alloca-1.c, c/termination-memory-alloca/openbsd_cmemrchr-alloca-1.i
Fixes three problems with openbsd_cmemrchr-alloca*:
- Unbounded stack allocation (see #550, #561, #791).
- Use of a 32-bit preprocessed file in a 64-bit category.
- Memory safety violation introduced in a recent "bugfix" (#776).
=> Fix openbsd_cmemrchr-alloca*

get_tasks_for_property.sh
In case people do not use the benchexec infrastructure,
it is difficult to get the full set of benchmark files
with a certain property.
This script makes that task easier:
It gets a property name and, optionally, the benchmark directory,
and prints all tasks with the given property to stdout.
At the moment, properties must be given without a directory prefix to
reliably work. This way, it is not necessary to look at each single task
definition file separately, but it may be imprecise in case
two different properties with the same basename exist in different
directories.
Example usage:
```
./get_tasks_for_property.sh coverage-branches.prp c/
```
=> Provide script that allows to get all tasks with a certain property

c/ReachSafety-Recursive.set, c/verifythis/duplets.yml, c/verifythis/elimination_max.c, c/verifythis/elimination_max.yml, c/verifythis/elimination_max_rec.c, c/verifythis/elimination_max_rec.yml, c/verifythis/elimination_max_rec_onepoint.c, c/verifythis/elimination_max_rec_onepoint.yml, c/verifythis/lcp.yml, c/verifythis/prefixsum_iter.yml, c/verifythis/prefixsum_rec.yml, c/verifythis/tree_del_iter.yml, c/verifythis/tree_del_rec.yml
This fixes some issues and contributes variants of benchmarks.
=> Don't require memcleanup, small fix and variants of the elimination_max

c/nla-digbench/README.md, c/nla-digbench/geo2.c, c/nla-digbench/knuth.c
=> Remove math.h, update README.  Need discussion on integer overflow issue.

c/ReachSafety-Loops.set, c/loop-simple/LICENSE.txt, c/loop-simple/Makefile, c/loop-simple/README.txt, c/loop-simple/deep-nested.c, c/loop-simple/deep-nested.yml
I want to add an example program for situations where execution-based witness validators are out of their comfort zone.
I hope I chose a correct subdirectory - I would have preferred to add it to an existing one instead of creating a new one, but regarding the attribution style, this seems impractical.
I believe all relevant elements of this checklist are fulfilled, preprocessing was not necessary.
=> Added a simple C nested loop example

c/memsafety/cmp-freed-ptr.c, c/memsafety/cmp-freed-ptr.i, c/memsafety/cmp-freed-ptr.yml
=> Adding predator test case for memsafety

java/ReachSafety.set, java/java-ranger-regression/LICENSE.Apache-2.0.txt, java/java-ranger-regression/README.txt, java/java-ranger-regression/replace5_eqchk.yml, java/java-ranger-regression/replace5_eqchk/Main.java, java/java-ranger-regression/replace5_eqchk/Outputs.java, java/java-ranger-regression/replace5_eqchk/TestVeritestingReplace.java, java/java-ranger-regression/replace5_eqchk/replace.java
The replace program is part of the Siemens suite of programs. This
benchmark performs pattern matching and substitution. One simple
property that should fail on this benchmark is that the outputs of the
benchmark from running it twice should not be equivalent if the starting
states of the benchmark were not equivalent. This is done by not
resetting the benchmark to its starting state. This benchmark was
obtained from Wang et al.
(https://labs.xjtudlc.com/labs/wlaq/hjwang/toolbench.html).
- equivalence-check on the replace benchmark in a folder named replace5_eqchk
- This benchmark wasn't distributed with a license. However, since this benchmark is being contributed by the developers of Java Ranger, we're adding under the same license used to maintain Java Ranger. Since Java Ranger is an …
=> Adding a equivalence-check on the Replace benchmark

java/java-ranger-regression/siena_eqchk.yml
The task definition for `java/java-ranger-regression/siena_eqchk.yml` was wrong. This tries to fix it.
=> Fix path for Java sources

c/ntdrivers/cdaudio.i.cil-1.c, c/ntdrivers/cdaudio.i.cil-2.c, c/ntdrivers/diskperf.i.cil-1.c, c/ntdrivers/diskperf.i.cil-2.c, c/ntdrivers/floppy.i.cil-1.c, c/ntdrivers/floppy.i.cil-3.c, c/ntdrivers/parport.i.cil-1.c, c/ntdrivers/parport.i.cil-2.c
1) cdaudio, floppy, parport failed to use CurrentStackLocation in a
memory-safe way: The pointer member CurrentStackLocation is incremented
and decremented in several places and dereferenced thereafter. This may
have been memory safe in the original device driver code in case the
function calls doing increments/decrements were paired correctly. The
partly stubbed device driver that just non-deterministically invokes
individual functions does not guarantee such memory safety. Therefore
make sure CurrentStackLocation is initialized to point to a sufficiently
large memory array and set to a non-zero offset so that all possible
increments/decrements are safe.
2) Initialize the device extensions object as necessary.
3) diskperf.i.cil-2.c took the address of a pointer when using memset.
=> ntdrivers/*: fix memory-safety errors

java/properties/no-deadlock.prp, java/rtems-lock-model/lock-00-01-10.yml, java/rtems-lock-model/lock-00-01-10/Main.java, java/rtems-lock-model/lock-00-01-10/base/Condition.java, java/rtems-lock-model/lock-00-01-10/base/Lock.java, java/rtems-lock-model/lock-00-01-10/base/PrioLock.java, java/rtems-lock-model/lock-00-01-10/harness/Environment.java, java/rtems-lock-model/lock-00-01-10/harness/TestThread.java, java/rtems-lock-model/lock-00-01-10/rtems/Mutex.java, java/rtems-lock-model/lock-00-01-10/rtems/OrderList.java, java/rtems-lock-model/lock-00-01-10/rtems/RTEMSThread.java, java/rtems-lock-model/lock-00-01-10/rtems/WaitQueue.java
This is work in progress. A license, more descriptions, and more variants of this example, will be added later. (The original repo git@github.com:saurabhgadia4/lock-model.git has a BSD 2-clause license.)
=> Imported a deadlocking configuration of the RTEMS lock model.

c/MemSafety-MemCleanup.set, c/memsafety-bftpd/bftpd_3.yml
Missing `*.yml` for `bftpd_2.c` in `MemSafety-MemCleanup.set` (without free for static variable - invalid memcleanup) and incomplete `bftpd_3.yml` (rewrite unfreed static variable - invalid memtrack).
=> memsafety-bftpd: incomplete *.yml

c/array-tiling/mlceu.c, c/array-tiling/mlceu2.c, c/array-tiling/mlceu2.yml
#791 introduced a upper bound on the size of the array making the assertion in the program mlceu provable. This change corrects the upper bound making the assertion violable in mlceu as per its verdict.
=> Update mlceu.c to get the correct verdict

java/java-ranger-regression/nanoxml_eqchk.yml, java/java-ranger-regression/nanoxml_eqchk/ContentReader.java, java/java-ranger-regression/nanoxml_eqchk/DumpXML.java, java/java-ranger-regression/nanoxml_eqchk/IXMLBuilder.java, java/java-ranger-regression/nanoxml_eqchk/IXMLParser.java, java/java-ranger-regression/nanoxml_eqchk/IXMLReader.java, java/java-ranger-regression/nanoxml_eqchk/IXMLValidator.java, java/java-ranger-regression/nanoxml_eqchk/IntReader.java, java/java-ranger-regression/nanoxml_eqchk/Main.java, java/java-ranger-regression/nanoxml_eqchk/NonValidator.java, java/java-ranger-regression/nanoxml_eqchk/StdXMLBuilder.java, java/java-ranger-regression/nanoxml_eqchk/StdXMLParser.java, java/java-ranger-regression/nanoxml_eqchk/StdXMLReader.java, java/java-ranger-regression/nanoxml_eqchk/TestVeritestingDumpXML.java, java/java-ranger-regression/nanoxml_eqchk/XMLElement.java, java/java-ranger-regression/nanoxml_eqchk/XMLParseException.java, java/java-ranger-regression/nanoxml_eqchk/XMLParserFactory.java, java/java-ranger-regression/nanoxml_eqchk/XMLValidationException.java, java/java-ranger-regression/nanoxml_eqchk/XMLWriter.java
Adding an equivalence-check from the NanoXML program.
* the license for this benchmark is the same as the license used for other benchmarks already in the java-ranger-regression folder
* As already mentioned in the README, this benchmark was originally contributed by Wang et al.
this new benchmark would be in the java-ranger-regression folder which is present in ReachSafety.set
* assert.prp is the property file used
* nanoxml_eqchk.yml is the newly introduced task definition file
=> Adding NanoXML equivalence check as a benchmark

c/ldv-linux-3.14-races/linux-3.14--drivers--media--platform--marvell-ccic--cafe_ccic.ko.cil-2.c
In 99652449be3, an initialisation fix was added, but the fix was only
applied to the preprocessed code. The original source was left
unmodified. This change makes sure that re-preprocessing does not result
in reverting the fix.
CI did not catch this problem, because
Systems_DeviceDriversLinux64_ReachSafety is exempted for performance
reasons.
=> ldv-linux-3.14-races: Fix original source to match preprocessed version

c/loops/s3.i
The semantics of __VERIFIER_nondet_pointer, particular whether it does or does
not perform memory allocation, have never been clarified (see issue #767). To
avoid any such ambiguity, just cast a non-deterministic unsigned long to a
pointer. As the benchmark just performs equality tests on the pointer value and
never attempts to dereference, this is a sufficient replacement.
=> loops/s3.i: Replace use of nondet_pointer by nondet_ulong

c/ntdrivers-simplified/cdaudio_simpl1.cil-1.c, c/ntdrivers-simplified/cdaudio_simpl1.cil-2.c, c/ntdrivers-simplified/diskperf_simpl1.cil.c, c/ntdrivers-simplified/floppy_simpl3.cil-1.c, c/ntdrivers-simplified/floppy_simpl3.cil-2.c, c/ntdrivers-simplified/floppy_simpl4.cil-1.c, c/ntdrivers-simplified/floppy_simpl4.cil-2.c, c/ntdrivers-simplified/kbfiltr_simpl1.cil.c, c/ntdrivers-simplified/kbfiltr_simpl2.cil-1.c, c/ntdrivers-simplified/kbfiltr_simpl2.cil-2.c
The semantics of __VERIFIER_nondet_pointer, particular whether it does
or does not perform memory allocation, have never been clarified (see
issue #767). In ntdrivers-simplified, however, just the declaration was
present, without any actual use. Thus remove the declaration to avoid
risk of ambiguity.
The changes were applied as follows:
```
sed -i \
'/^extern void \*__VERIFIER_nondet_pointer();/d' \
c/ntdrivers-simplified/*.c
```
=> ntdrivers-simplified: Remove unused declaration of __VERIFIER_nondet_pointer

c/aws-c-common/README.txt
The order of arguments expected by makeall is different from what the
README claimed.
@gernst Which Linux distro and version thereof did you use when initially generating and submitting the benchmarks? The instructions (now) work for me, but I'm getting different preprocessing results, so I'm obviously using a different distro right now.
=> aws-c-common: fix README

.gitlab-ci.yml, .travis.yml, c/compare.py
This is a first step towards an faster CI.
Replacing the Bash script for preprocessing files by a Python-based implementation seems to have a large benefit. The runtime seems to be **more than four times faster**. For details see [old](https://travis-ci.org/sosy-lab/sv-benchmarks/builds/609000272?utm_source=github_status&utm_medium=notification) (>45min) vs [new](https://travis-ci.org/sosy-lab/sv-benchmarks/builds/609156991?utm_source=github_status&utm_medium=notification) (11min) runtime.
I would keep the old Bash script for backwards compatibility testing, except some reviewer proves functional equivalence between both scripts.
=> CI Speedup

java/java-ranger-regression/printtokens_eqchk.yml, java/java-ranger-regression/printtokens_eqchk/IntReader.java, java/java-ranger-regression/printtokens_eqchk/Main.java, java/java-ranger-regression/printtokens_eqchk/TestPrintTokens.java, java/java-ranger-regression/printtokens_eqchk/printTokens2.java, java/java-ranger-regression/printtokens_eqchk/token_stream.java
Adding an equivalence-check from the PrintTokens program.
* the license for this benchmark is the same as the license used for other benchmarks already in the java-ranger-regression folder
* As already mentioned in the README, this benchmark was originally contributed by Wang et al.
this new benchmark would be in the java-ranger-regression folder which is present in ReachSafety.set
* assert.prp is the property file used
* printtokens_eqchk.yml is the newly introduced task definition file
=> Adding equivalence check for PrintTokens benchmark

c/ldv-linux-3.14-races/linux-3.14--drivers--media--platform--marvell-ccic--cafe_ccic.ko.cil-1.i, c/ldv-linux-3.14-races/linux-3.14--drivers--media--platform--marvell-ccic--cafe_ccic.ko.cil-2.c, c/ldv-linux-3.14-races/linux-3.14--drivers--media--platform--marvell-ccic--cafe_ccic.ko.cil-2.i, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--nsc-ircc.ko.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--nsc-ircc.ko.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--w83977af_ir.ko.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--w83977af_ir.ko.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--adutux.ko.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--adutux.ko.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--iowarrior.ko.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--iowarrior.ko.cil.i
The size of the desired allocation is perfectly known, there is no need
to use the _unknown_size variant. This is in preparation of removing
uses of __VERIFIER_nondet_pointer (see #767).
Changes were made as follows:
```
perl -p -i -e \
's/ldv_xmalloc_unknown_size\(0UL\);/ldv_xmalloc(0UL);/' \
c/ldv-*/*.[ci]
```
=> Replace ldv_xmalloc_unknown_size(0UL) by ldv_xmalloc(0UL)

c/termination-libowfat/strlcat.c, c/termination-libowfat/strlcpy.c
The K&R-style function syntax is both outdated and deprecated. As this is additionally not common in today's C code, I propose to change this therefore such that the functions consistently make use of the ANSI C syntax instead.
=> Change K&R-style declared functions to use the ANSI C syntax instead

c/ldv-challenges/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-ethernet-renesas-sh_eth.cil.c, c/ldv-challenges/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-ethernet-renesas-sh_eth.cil.i, c/ldv-challenges/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-wireless-rndis_wlan.cil.c, c/ldv-challenges/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-wireless-rndis_wlan.cil.i, c/ldv-linux-3.14/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-ethernet-stmicro-stmmac-stmmac.cil.c, c/ldv-linux-3.14/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-ethernet-stmicro-stmmac-stmmac.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--misc--mic--host--mic_host.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--misc--mic--host--mic_host.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--staging--ozwpan--ozwpan.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--staging--ozwpan--ozwpan.ko.cil.i, c/ldv-multiproperty/linux-4.0-rc1---drivers--misc--mic--host--mic_host.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---drivers--staging--ozwpan--ozwpan.ko_false-unreach-call.cil.c
Removes one of the uses of ldv_malloc_unknown_size, which is implemented using
__VERIFIER_nondet_pointer. The size is known, thus using ldv_malloc is
perfectly safe.
```
perl -i -e \
'$p = 1;
while(<>) {
if(/^__inline static void \*ldv_kmalloc_array_\d+\(size_t n , size_t size , gfp_t flags \) ?$/) {
$p = 2;
}
if($p == 2) {
if(/^  res = ldv_malloc_unknown_size\(\);/) {
print "  res = ldv_malloc(size * n);\n";
$p = 1;
next;
}
elsif(/^\}$/) { $p = 1; }
}
print;
}' \
c/ldv-*/*.[ci]
```
=> Implement ldv_malloc_array_* using ldv_malloc

c/ldv-challenges/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-ethernet-intel-ixgbe-ixgbe.cil.c, c/ldv-challenges/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-ethernet-intel-ixgbe-ixgbe.cil.i, c/ldv-linux-3.14/linux-3.14_linux-alloc-spinlock_drivers-net-ethernet-chelsio-cxgb4-cxgb4.cil.c, c/ldv-linux-3.14/linux-3.14_linux-alloc-spinlock_drivers-net-ethernet-chelsio-cxgb4-cxgb4.cil.i, c/ldv-linux-3.14/linux-3.14_linux-alloc-spinlock_drivers-net-ethernet-intel-ixgbe-ixgbe.cil.c, c/ldv-linux-3.14/linux-3.14_linux-alloc-spinlock_drivers-net-ethernet-intel-ixgbe-ixgbe.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--block--mtip32xx--mtip32xx.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--block--mtip32xx--mtip32xx.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--block--nvme.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--block--nvme.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--ide--ide-core.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--ide--ide-core.ko.cil.i, c/ldv-multiproperty/linux-4.0-rc1---drivers--block--mtip32xx--mtip32xx.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---drivers--block--nvme.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---drivers--ide--ide-core.ko_false-unreach-call.cil.c
kzalloc_node provides size information, thus there is no need to use the
_unknown_size variant. This is in preparation of removing uses of
Changes were made using:
```
perl -p -i -e \
's/res = ldv_zalloc_unknown_size\(\);/res = ldv_zalloc(size);/' \
c/ldv-*/*.[ci]
```
=> Replace ldv_zalloc_unknown_size by ldv_zalloc in kzalloc_node

c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--md--raid456.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--md--raid456.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--staging--ozwpan--ozwpan.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--staging--ozwpan--ozwpan.ko.cil.i, c/ldv-multiproperty/linux-4.0-rc1---drivers--md--raid456.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---drivers--staging--ozwpan--ozwpan.ko_false-unreach-call.cil.c
kmem_cache_zalloc should allocate (from a cache) memory of the size
confirmed when the cache was created (via kmem_cache_create). Since none
of the benchmarks provide a definition of kmem_cache_create (or struct
kmem_cache), this information cannot be communicated. Instead, hard-code
the allocation size as used in the specific device driver in
kmem_cache_zalloc and use ldv_zalloc instead of ldv_zalloc_unknown_size.
(see #767).
=> Specialise kmem_cache_zalloc to the desired allocation size

c/nla-digbench/freire1.yml, c/nla-digbench/freire2.yml
The assertion in programs freire1.c and freire2.c are violable. Counter examples were obtained using bounded model checking. Hence this pull request changes the verdict of these programs.
Benchmarks from PR #808 
Similar issues discussed in PR #813 
Partial corrections issued in PR #837
=> Changed verdict of freire1.c and freire2.c

c/verifythis/prefixsum_rec.yml, c/verifythis/tree_del_iter.yml, c/verifythis/tree_del_rec.yml, c/verifythis/tree_max.yml
ESBMC, CBMC, and CPA-seq find property violations in the following benchmarks (using the scripts for the 2020 SV-COMP):
```
tree_del_iter.c
tree_del_rec.c
```
ESBMC, CBMC and CPA-seq find a violation. The witnesses are confirmed by CPAcheck.
```
tree_max.c
```
ESBMC and CPA-seq find a violation. The witnesses are confirmed by CPAcheck.
```
prefixsum_rec.c
```
ESBMC finds a property violation. The witness is confirmed by CProver witness2test.
=> Update verdict of four programs in verifythis

c/nla-digbench/hard2.c, c/nla-digbench/hard2.yml
The assertion in the hard.c program is violable. Counter example was obtained using a bounded model checker and manually verified. Hence this pull request changes the verdict of this program. Also, corrected program version hard2.c with verifiable assertion is added.
Benchmarks from PR #808 
Similar issues discussed in PR #813 
Partial corrections issued in PR #837
=> Corrected verdict of hard.c (from PR #808) and added its correct version

c/nla-digbench/divbin2.c, c/nla-digbench/divbin2.i, c/nla-digbench/divbin2.yml
The assertion in the divbin program is violable. Counter example was obtained using a bounded model checker and manually verified. Hence this pull request changes the verdict of this program. Also, corrected program version divbin2 with verifiable assertion is added.
Benchmarks from PR #808 
Similar issues discussed in PR #813 
Partial corrections issued in PR #837
=> Corrected divbin verdict (from #808) and its correct version

c/ldv-linux-3.14-races/linux-3.14--drivers--media--platform--marvell-ccic--cafe_ccic.ko.cil-1.i, c/ldv-linux-3.14-races/linux-3.14--drivers--media--platform--marvell-ccic--cafe_ccic.ko.cil-2.c, c/ldv-linux-3.14-races/linux-3.14--drivers--media--platform--marvell-ccic--cafe_ccic.ko.cil-2.i, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--nsc-ircc.ko.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--nsc-ircc.ko.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--w83977af_ir.ko.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--w83977af_ir.ko.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--spi--spi-tegra20-slink.ko.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--spi--spi-tegra20-slink.ko.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--adutux.ko.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--adutux.ko.cil.i, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--iowarrior.ko.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--usb--misc--iowarrior.ko.cil.i
Removes calls to external_allocated_data where the value was overwritten
immediately afterwards or where the value is never read anyway. This is in
preparation of removing uses of __VERIFIER_nondet_pointer (see #767).
=> Remove unnecessary use of external_allocated_data

c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--scsi--qla4xxx--qla4xxx.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--scsi--qla4xxx--qla4xxx.ko.cil.i, c/ldv-multiproperty/linux-4.0-rc1---drivers--scsi--qla4xxx--qla4xxx.ko_false-unreach-call.cil.c
mempool_alloc should allocate (from a memory pool) memory of the size specified
when the pool was created (via mempool_create). Since none of the benchmarks
provide a definition of mempool_create, this information cannot be
communicated. Instead, hard-code the allocation size as used in the specific
device driver in mempool_alloc and use ldv_malloc instead of
ldv_malloc_unknown_size.  This is in preparation of removing uses of
=> Specialise mempool_alloc to the desired allocation size

c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---net--rose--rose.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---net--rose--rose.ko.cil.i, c/ldv-multiproperty/linux-4.0-rc1---net--rose--rose.ko_true-unreach-call.cil.c_false-unreach-call.cil.c
This is a manual follow-up to b7723fa766ab, the script of which should
also have been applied to functions with a `___0` suffix.
=> Implement ldv_skb_clone* using ldv_malloc(sizeof(struct sk_buff))

c/ldv-linux-3.14/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-ethernet-mellanox-mlx5-core-mlx5_core.cil.c, c/ldv-linux-3.14/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-ethernet-mellanox-mlx5-core-mlx5_core.cil.i, c/ldv-linux-3.14/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-usb-kaweth.cil.c, c/ldv-linux-3.14/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-usb-kaweth.cil.i, c/ldv-linux-3.14/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-wireless-b43legacy-b43legacy.cil.c, c/ldv-linux-3.14/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-wireless-b43legacy-b43legacy.cil.i, c/ldv-linux-3.14/linux-3.14_linux-alloc-spinlock_drivers-net-wireless-b43legacy-b43legacy.cil.c, c/ldv-linux-3.14/linux-3.14_linux-alloc-spinlock_drivers-net-wireless-b43legacy-b43legacy.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--block--xen-blkfront.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--block--xen-blkfront.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--ide--ide-core.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--ide--ide-core.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--misc--mic--host--mic_host.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--misc--mic--host--mic_host.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--net--usb--kaweth.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--net--usb--kaweth.ko.cil.i, c/ldv-multiproperty/linux-4.0-rc1---drivers--block--xen-blkfront.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---drivers--ide--ide-core.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---drivers--misc--mic--host--mic_host.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---drivers--net--usb--kaweth.ko_false-unreach-call.cil.c
Removes one of the uses of ldv_malloc_unknown_size, which is implemented
using __VERIFIER_nondet_pointer. The size is known (the second argument
is the order, which is the 2-logarithm of the number of pages, and a
page usually is 4K), thus using ldv_malloc is perfectly safe. This is in
preparation of removing uses of __VERIFIER_nondet_pointer (see #767).
```
do
perl -i -e \
while(<>) {
if(/^void \*ldv_malloc\(size_t size \) ;$/) {
$d = 1;
}
if(/^static unsigned long ldv___get_free_pages_\d+\(gfp_t flags , unsigned int ldv_func_arg2 \) ?$/) {
$p = 2;
if($d == 0) {
print "void *ldv_malloc(size_t size ) ;\n";
$d = 2;
}
}
if($p == 2) {
if(/^  tmp = ldv_malloc_unknown_size\(\);/) { …
```
=> Implement ldv___get_free_pages_* using ldv_malloc

c/ldv-challenges/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-wireless-rndis_wlan.cil.c, c/ldv-challenges/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-wireless-rndis_wlan.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--scsi--advansys.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--scsi--advansys.ko.cil.i, c/ldv-multiproperty/linux-4.0-rc1---drivers--scsi--advansys.ko_false-unreach-call.cil.c
Removes one of the uses of ldv_malloc_unknown_size, which is implemented
using __VERIFIER_nondet_pointer. The size is known (passed in as
parameter), and `realloc` much more closely resembles the semantics.
(see #767).
```
do
perl -i -e \
while(<>) {
if(/^static void \*ldv_krealloc_\d+\(void const  *\*ldv_func_arg1 , size_t ldv_func_arg2 , ?$/) {
$p = 2;
if($d == 0) {
print "extern void *realloc(void * , size_t  ) ;\n";
$d = 1;
}
}
if($p == 2) {
if(/^  tmp = ldv_malloc_unknown_size\(\);/) {
print "  tmp = realloc(ldv_func_arg1, ldv_func_arg2);\n";
$p = 1;
next;
}
elsif(/^\}$/) { $p = 1; }
}
print;
}' \
$f
done
```
=> Implement ldv_krealloc_* using realloc

c/ldv-challenges/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-ethernet-intel-ixgbe-ixgbe.cil.c, c/ldv-challenges/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-ethernet-intel-ixgbe-ixgbe.cil.i, c/ldv-linux-3.14/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-ethernet-mellanox-mlx5-core-mlx5_core.cil.c, c/ldv-linux-3.14/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-ethernet-mellanox-mlx5-core-mlx5_core.cil.i, c/ldv-linux-3.14/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-wireless-ipw2x00-ipw2200.cil.c, c/ldv-linux-3.14/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-wireless-ipw2x00-ipw2200.cil.i, c/ldv-linux-3.14/linux-3.14_linux-alloc-spinlock_drivers-net-ethernet-intel-ixgbe-ixgbe.cil.c, c/ldv-linux-3.14/linux-3.14_linux-alloc-spinlock_drivers-net-ethernet-intel-ixgbe-ixgbe.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--block--nvme.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--block--nvme.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--scsi--be2iscsi--be2iscsi.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--scsi--be2iscsi--be2iscsi.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--scsi--mvsas--mvsas.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--scsi--mvsas--mvsas.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--scsi--pmcraid.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--scsi--pmcraid.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--scsi--qla4xxx--qla4xxx.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--scsi--qla4xxx--qla4xxx.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--usb--gadget--udc--pch_udc.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--usb--gadget--udc--pch_udc.ko.cil.i, c/ldv-multiproperty/linux-4.0-rc1---drivers--block--nvme.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---drivers--scsi--be2iscsi--be2iscsi.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---drivers--scsi--mvsas--mvsas.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---drivers--scsi--pmcraid.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---drivers--scsi--qla4xxx--qla4xxx.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---drivers--usb--gadget--udc--pch_udc.ko_false-unreach-call.cil.c
Removes one of the uses of ldv_malloc_unknown_size, which is implemented
using __VERIFIER_nondet_pointer. The size is inferred as described
below.  This is in preparation of removing uses of
```
do
perl -i -e \
while(<>) {
if(/^void \*ldv_malloc\(size_t size \) ;$/) {
$d = 1;
}
if(/^static void \*ldv_dma_pool_alloc_\d+\(struct dma_pool \*ldv_func_arg1 , gfp_t flags , ?$/) {
$p = 2;
if($d == 0) {
print "void *ldv_malloc(size_t size ) ;\n";
$d = 2;
}
}
if($p == 2) {
if(/^  tmp = ldv_malloc_unknown_size\(\);/) {
print "  tmp = ldv_malloc(FIXME);\n";
$p = 1;
next;
}
elsif(/^\}$/) { $p = 1; }
}
print;
}' \
$f
done
```
The actual allocation size …
=> Implement ldv_dma_pool_alloc_* using ldv_malloc

java/algorithms/InsertionSort-FunSat02.yml, java/algorithms/InsertionSort-FunSat02/Main.java, java/algorithms/MergeSortIterative-FunSat01/Main.java, java/algorithms/MergeSortIterative-FunSat02.yml, java/algorithms/MergeSortIterative-FunSat02/Main.java, java/algorithms/MergeSortIterative-FunUnsat01/Main.java, java/algorithms/MergeSortIterative-MemSat01/Main.java, java/algorithms/MergeSortIterative-MemUnsat01/Main.java, java/algorithms/SortedListInsert-FunSat02.yml, java/algorithms/SortedListInsert-FunSat02/Main.java
Three extra java algorithm benchmarks, which are actually copies of some of the benchmarks from [this PR](https://github.com/sosy-lab/sv-benchmarks/pull/823), but with stronger sortedness assertions as discussed [here](https://github.com/sosy-lab/sv-benchmarks/pull/823#discussion_r338081500).
- [] programs added to a `.set` file of an existing category, or new sub-category established (if justified)
- [] intended property matches the corresponding `.prp` file
=> Extra java algorithm benchmarks which check stronger sortedness properties

c/ldv-challenges/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-ethernet-emulex-benet-be2net.cil.c, c/ldv-challenges/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-ethernet-emulex-benet-be2net.cil.i, c/ldv-challenges/linux-3.14_linux-alloc-spinlock_drivers-net-ethernet-emulex-benet-be2net.cil.c, c/ldv-challenges/linux-3.14_linux-alloc-spinlock_drivers-net-ethernet-emulex-benet-be2net.cil.i, c/ldv-linux-3.14/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-team-team.cil.c, c/ldv-linux-3.14/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-team-team.cil.i, c/ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-drivers--net--ethernet--emulex--benet--be2net.ko-entry_point.cil.out.c, c/ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-drivers--net--ethernet--emulex--benet--be2net.ko-entry_point.cil.out.i, c/ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-net--batman-adv--batman-adv.ko-entry_point.cil.out.c, c/ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-net--batman-adv--batman-adv.ko-entry_point.cil.out.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--net--team--team.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--net--team--team.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--staging--ozwpan--ozwpan.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--staging--ozwpan--ozwpan.ko.cil.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--ethernet--intel--fm10k--fm10k.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--ethernet--intel--fm10k--fm10k.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--scsi--fcoe--fcoe.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--scsi--fcoe--fcoe.ko-entry_point.cil.out.i, c/ldv-multiproperty/linux-4.0-rc1---drivers--net--team--team.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---drivers--staging--ozwpan--ozwpan.ko_false-unreach-call.cil.c
Removes one of the uses of ldv_malloc_unknown_size, which is implemented using
__VERIFIER_nondet_pointer. The size is known (sizeof(struct sk_buff)), thus
using ldv_malloc is perfectly safe. This is in preparation of removing uses of
```
do
perl -i -e \
while(<>) {
if(/^void \*ldv_malloc\(size_t size \) ;$/) {
$d = 1;
}
if(/^__inline static struct sk_buff \*skb_share_check\(struct sk_buff \*skb , gfp_t flags \) ?$/) {
$p = 2;
if($d == 0) {
print "void *ldv_malloc(size_t size ) ;\n";
$d = 2;
print;
next;
}
}
if($p == 2) {
if(/^  tmp = ldv_malloc_unknown_size\(\);/) {
print "  tmp = __VERIFIER_nondet_bool() ? skb : ldv_malloc(sizeof(struct …
```
=> Implement skb_share_check using ldv_malloc(sizeof(struct sk_buff))

c/MemSafety-Other.set
The new VerifyThis tasks came with properties `unreach-call` and `memsafety`, but only the `unreach-call` ones were added to SV-COMP categories.
=> Add the forgotten memsafety tasks

java/algorithms/BellmanFord-FunSat01/Main.java, java/algorithms/BellmanFord-MemSat01/Main.java, java/algorithms/MergeSortIterative-FunSat01/Main.java
Would otherwise affect the expected verdict.
- [n/a] programs added to new and [appropriately named](https://github.com/sosy-lab/sv-benchmarks/blob/master/CONTRIBUTING.md#directory-structure-and-names) directory
- [n/a] license present and [acceptable](https://github.com/sosy-lab/sv-benchmarks/blob/master/CONTRIBUTING.md#license) (either in separate file or as comment at beginning of program)
- [n/a] [contributed-by](https://github.com/sosy-lab/sv-benchmarks/blob/master/CONTRIBUTING.md#origin-description-and-attribution) present (either in README file or as comment at beginning of program)
- [n/a] programs added to a `.set` file of an existing category, or new sub-category established (if justified)
- [n/a] intended property matches the corresponding `.prp` file
- [n/a] programs and …
=> Fix unintended runtime exceptions in algorithms Java benchmarks

c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--block--rsxx--rsxx.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--block--rsxx--rsxx.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--mtd--ubi--ubi.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--mtd--ubi--ubi.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--scsi--advansys.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--scsi--pmcraid.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--scsi--pmcraid.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--staging--ozwpan--ozwpan.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--staging--ozwpan--ozwpan.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---fs--ncpfs--ncpfs.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---fs--ncpfs--ncpfs.ko.cil.i, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---fs--squashfs--squashfs.ko.cil.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---fs--squashfs--squashfs.ko.cil.i, c/ldv-multiproperty/linux-4.0-rc1---drivers--block--rsxx--rsxx.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---drivers--mtd--ubi--ubi.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---drivers--scsi--pmcraid.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---drivers--staging--ozwpan--ozwpan.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---fs--ncpfs--ncpfs.ko_false-unreach-call.cil.c, c/ldv-multiproperty/linux-4.0-rc1---fs--squashfs--squashfs.ko_true-unreach-call.cil.c_false-unreach-call.cil.c
kmem_cache_alloc should allocate (from a cache) memory of the size
specified when the cache was created (via kmem_cache_create). Since none
of the benchmarks provide a definition of kmem_cache_create (or struct
kmem_cache), this information cannot be communicated. Instead, hard-code
the allocation size as used in the specific device driver (and the
particular cache, when multiple caches are used) in kmem_cache_alloc and
use ldv_malloc instead of ldv_malloc_unknown_size.  This is in
preparation of removing uses of __VERIFIER_nondet_pointer (see #767).
=> Specialise kmem_cache_alloc to the desired allocation size

java/java-ranger-regression/WBS_prop2.yml, java/java-ranger-regression/WBS_prop2/Main.java
This version of Wheel Brake System has been part of the SPF repository
for the past few years. It can be found at https://github.com/SymbolicPathFinder/jpf-symbc/blob/master/src/examples/WBS.java. An existing pull request checks one property on this benchmark (https://github.com/sosy-lab/sv-benchmarks/pull/825). In this commit, I am adding it again to the SV-COMP repository of benchmarks so that we can check a different property in it.
* WBS_prop2 is the name of the newly added benchmark
* license file is the same as the one used for existing benchmarks in the java-ranger-regression/ folder
* contributed by developers of Java Ranger (https://github.com/vaibhavbsharma/java-ranger). This benchmark originates from the WBS version maintained in the src/examples directory of the source code of …
=> Adding a second property in WBS to prove

java/java-ranger-regression/WBS_prop3.yml, java/java-ranger-regression/WBS_prop3/Main.java
This version of Wheel Brake System has been part of the SPF repository
for the past few years. It can be found at https://github.com/SymbolicPathFinder/jpf-symbc/blob/master/src/examples/WBS.java. An existing pull request checks one property on this benchmark (#825). In this commit, I am adding it again to the SV-COMP repository of benchmarks so that we can check a different property in it.
* WBS_prop3 is the name of the newly added benchmark
license file is the same as the one used for existing benchmarks in the java-ranger-regression/ folder
* contributed by developers of Java Ranger (https://github.com/vaibhavbsharma/java-ranger). This benchmark originates from the WBS version maintained in the src/examples directory of the source code of SPF as mentioned earlier.
* The ReachSafety.set …
=> Adding a 3rd property in Wheel Brake System

java/java-ranger-regression/WBS_prop4.yml, java/java-ranger-regression/WBS_prop4/Main.java
This version of Wheel Brake System has been part of the SPF repository
for the past few years. It can be found at https://github.com/SymbolicPathFinder/jpf-symbc/blob/master/src/examples/WBS.java. An existing pull request checks one property on this benchmark (#825). In this commit, I am adding it again to the SV-COMP repository of benchmarks so that we can check a different property in it.
* WBS_prop4 is the name of the newly added benchmark
license file is the same as the one used for existing benchmarks in the java-ranger-regression/ folder
* contributed by developers of Java Ranger (https://github.com/vaibhavbsharma/java-ranger). This benchmark originates from the WBS version maintained in the src/examples directory of the source code of SPF as mentioned earlier.
* The ReachSafety.set …
=> Adding a 4th property to check on Wheel Brake System

java/java-ranger-regression/TCAS_prop2.yml, java/java-ranger-regression/TCAS_prop2/Main.java
TCAS is another benchmark that has been used several times over the past few years to demonstrate the capabilities of symbolic execution. This version of the benchmark was obtained from here: https://labs.xjtudlc.com/labs/wlaq/hjwang/toolbench.html. This benchmark set is distributed by Wang et al., the authors of the paper titled ``Dependence Guided Symbolic Execution'' which was published in the IEEE Transactions of Software Engineering Volume 43, Issue 3, March 1 2017 (https://doi.org/10.1109/TSE.2016.2584063).
In this PR, I am adding a second property to be verified on the TCAS benchmark.
- TCAS_prop2 is the newly added benchmark
- This benchmark wasn't distributed with a license. However, since this benchmark is being contributed by the developers of Java Ranger, we're adding under …
=> Adding 2nd property on TCAS benchmark

java/java-ranger-regression/TCAS_prop3.yml, java/java-ranger-regression/TCAS_prop3/Main.java
TCAS is another benchmark that has been used several times over the past few years to demonstrate the capabilities of symbolic execution. This version of the benchmark was obtained from here: https://labs.xjtudlc.com/labs/wlaq/hjwang/toolbench.html. This benchmark set is distributed by Wang et al., the authors of the paper titled ``Dependence Guided Symbolic Execution'' which was published in the IEEE Transactions of Software Engineering Volume 43, Issue 3, March 1 2017 (https://doi.org/10.1109/TSE.2016.2584063).
In this PR, I am adding a third property to be verified on the TCAS benchmark.
- TCAS_prop3 is the newly added benchmark
- This benchmark wasn't distributed with a license. However, since this benchmark is being contributed by the developers of Java Ranger, we're adding under the …
=> Adding a 3rd property to check on TCAS

c/ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-net--core--pktgen.ko-entry_point.cil.out.c, c/ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-net--core--pktgen.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--block--mtip32xx--mtip32xx.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--block--mtip32xx--mtip32xx.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--crypto--qat--qat_common--intel_qat.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--crypto--qat--qat_common--intel_qat.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--ethernet--intel--ixgbe--ixgbe.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--ethernet--intel--ixgbe--ixgbe.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--ethernet--mellanox--mlx5--core--mlx5_core.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--ethernet--mellanox--mlx5--core--mlx5_core.ko-entry_point.cil.out.i
Removes one of the uses of ldv_undef_ptr, which is implemented using
__VERIFIER_nondet_pointer. The size is known, thus using ldv_zalloc is
perfectly safe, and also more consistent as it will ensure
zero-initialisation. This is in preparation of removing uses of
```
do
perl -i -e \
while(<>) {
if(/^void \*ldv_zalloc\(size_t size \) ;$/) {
$d = 1;
}
if(/^__inline static void \*kzalloc_node\(size_t size , gfp_t flags , int node \) ?$/) {
$p = 2;
if($d == 0) {
print "void *ldv_zalloc(size_t size ) ;\n";
$d = 2;
print;
next;
}
}
if($p == 2) {
if(/^  tmp = ldv_undef_ptr\(\);/) {
print "  tmp = ldv_zalloc(size);\n";
$p = 1;
next;
}
elsif(/^\}$/) { …
```
=> Implement kzalloc_node using ldv_zalloc

c/ldv-linux-3.14-races/linux-3.14--drivers--spi--spi-tegra20-slink.ko.cil.c, c/ldv-linux-3.14-races/linux-3.14--drivers--spi--spi-tegra20-slink.ko.cil.i
external_allocated_data is implemented using __VERIFIER_nondet_pointer,
which has an unspecified semantics. Instead, allocate memory using
ldv_malloc. This is in preparation of removing uses of
__VERIFIER_nondet_pointer (see #767), but may turn the debate into one
about the initialisation state of the object.
=> Replace two uses of external_allocated_data by ldv_malloc

c/MemSafety-Arrays.set, c/MemSafety-MemCleanup.set, c/MemSafety-Other.set, c/verifythis/duplets.c, c/verifythis/elimination_max.c, c/verifythis/elimination_max_rec.c, c/verifythis/elimination_max_rec_onepoint.c, c/verifythis/lcp.c, c/verifythis/prefixsum_iter.c, c/verifythis/prefixsum_rec.c, c/verifythis/prefixsum_rec.yml, c/verifythis/tree_del_iter.c, c/verifythis/tree_del_iter.yml, c/verifythis/tree_del_rec.c, c/verifythis/tree_del_rec.yml, c/verifythis/tree_max.yml
There is no `free()` after allocation on heap, that means the memtrack property is violated. Where `__VERIFIER_error()` (for memsafety `abort()`) is reachable, the memcleanup property is violated. According to PR #923 by @mikhailramalho:
```
verifythis/prefixsum_rec.c
verifythis/tree_del_iter.c
verifythis/tree_del_rec.c
verifythis/tree_max.c
```
This PR fixed invalid memtracks in tasks except `verifythis/tree_max.c`.
I suggest move the benchmarks into a better sub-category, because `MemSafety-Other` is for these tasks that don't fit anywhere. Benchmarks with arrays -> `MemSafety-Arrays` and for safe trees -> `MemSafety-Heap`, but there is memcleanup violation -> `MemSafety-MemCleanup`.
@gernst
=> Verifythis: fix memory leaks

c/array-fpi/eqn1.c, c/array-fpi/eqn2.c, c/array-fpi/eqn3.c, c/array-fpi/eqn4.c, c/array-fpi/eqn5.c, c/array-fpi/ifcomp.c, c/array-fpi/ifeqn1.c, c/array-fpi/ifeqn2.c, c/array-fpi/ifeqn3.c, c/array-fpi/ifeqn4.c, c/array-fpi/ifeqn5.c, c/array-fpi/ifncomp.c, c/array-fpi/indp1.c, c/array-fpi/indp3.c, c/array-fpi/indp4.c, c/array-fpi/indp5.c, c/array-fpi/ncomp.c, c/array-fpi/nsqm-if.c, c/array-fpi/nsqm.c, c/array-fpi/pcomp.c, c/array-fpi/sqm-if.c, c/array-fpi/sqm.c, c/array-fpi/ss1.c, c/array-fpi/ss2.c, c/array-fpi/ss3.c, c/array-fpi/ss4.c, c/array-fpi/ssina.c
Fixes several programs from PR #824 to ensure that integer overflow does not cause property violation. Changed the data type of the loop counter variable and cast expressions in assertion from int to long long to avoid overflows.
=> Fix property violations due to overflow

c/ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-drivers--media--usb--pwc--pwc.ko-entry_point.cil.out.c, c/ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-drivers--media--usb--pwc--pwc.ko-entry_point.cil.out.i, c/ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-drivers--usb--class--cdc-acm.ko-entry_point.cil.out.c, c/ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-drivers--usb--class--cdc-acm.ko-entry_point.cil.out.i, c/ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-drivers--usb--misc--usbtest.ko-entry_point.cil.out.c, c/ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-drivers--usb--misc--usbtest.ko-entry_point.cil.out.i, c/ldv-linux-3.4-simple/43_1a_cilled_ok_nondet_linux-43_1a-drivers--media--video--gspca--gspca_benq.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/43_1a_cilled_ok_nondet_linux-43_1a-drivers--media--video--gspca--gspca_benq.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--media--usb--cx231xx--cx231xx.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--media--usb--cx231xx--cx231xx.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--media--usb--tm6000--tm6000.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--media--usb--tm6000--tm6000.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--wireless--mediatek--mt7601u--mt7601u.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--wireless--mediatek--mt7601u--mt7601u.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--wireless--zd1211rw--zd1211rw.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--wireless--zd1211rw--zd1211rw.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--usb--class--cdc-acm.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--usb--class--cdc-acm.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--usb--misc--ftdi-elan.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--usb--misc--ftdi-elan.ko-entry_point.cil.out.i
Removes one of the uses of ldv_undef_ptr, which is implemented using
__VERIFIER_nondet_pointer. The size is known (the second parameter of
the function, ldv_func_arg2), thus using ldv_malloc is perfectly safe.
(see #767).
```
do
perl -i -e \
while(<>) {
if(/^void \*ldv_malloc\(size_t size \) ;$/) {
$d = 1;
}
if(/^void \*ldv_usb_alloc_coherent_\d+\(struct usb_device \*ldv_func_arg1 , size_t ldv_func_arg2 , ?$/) {
$p = 2;
if($d == 0) {
print "void *ldv_malloc(size_t size ) ;\n";
$d = 2;
print;
next;
}
}
if($p == 2) {
if(/^  tmp = ldv_undef_ptr\(\);/) {
print "  tmp = ldv_malloc(ldv_func_arg2);\n";
$p = 1;
next;
} …
```
=> Implement ldv_usb_alloc_coherent_* using ldv_malloc

c/memsafety-bftpd/bftpd_1a.yml, c/memsafety-bftpd/bftpd_1b.yml, c/memsafety-bftpd/bftpd_2a.yml, c/memsafety-bftpd/bftpd_2b.yml
BenchExec uses the file name as id, and SV-COMP's benchmark definitions
put the tasks for memsafety and memcleanup in one run set.
May be this should be changed. But for now, I split the four tasks into four separate task-definition files.
=> Split tasks in order to make task names unique

c/ntdrivers/floppy.i.cil-3.yml
There is at least one struct 'devobj' in the main function,
whose members are allocated on the heap, but never freed.
This violates the memory property for mem-track,
because when returning from the main function,
the struct itself is cleaned up with the stack frame,
but the heap object is no longer reachable.
Some of the allocation was introduced with d21602b024af034628dd81cf82e77d7eee2177c9.
=> change verdict of memory safety (mem-track).

c/memsafety/cmp-freed-ptr.c, c/memsafety/cmp-freed-ptr.i
According to ISO-C99 6.2.4(2),
the value of a pointer becomes indeterminate when
the object it points to reaches the end of its lifetime.
The undefined behavior comes from computing "x==y" in this task,
because "y" was freed before, so its value is indeterminate.
The fix uses a temporary variable for storing the corresponding value.
=> fix undefined behaviour from pointer comparison after a pointer was freed

c/ldv-consumption/32_7a_cilled_linux-3.8-rc1-32_7a-drivers--gpu--drm--ttm--ttm.ko-ldv_main5_sequence_infinite_withcheck_stateful.cil.out.i, c/ldv-consumption/32_7a_cilled_linux-3.8-rc1-32_7a-drivers--infiniband--hw--mlx4--mlx4_ib.ko-ldv_main4_sequence_infinite_withcheck_stateful.cil.out.i, c/ldv-consumption/model/32_7a_cilled_true-unreach-call_linux-3.8-rc1-32_7a-drivers--gpu--drm--ttm--ttm.ko-ldv_main5_sequence_infinite_withcheck_stateful.env.c, c/ldv-consumption/model/32_7a_cilled_true-unreach-call_linux-3.8-rc1-32_7a-drivers--infiniband--hw--mlx4--mlx4_ib.ko-ldv_main4_sequence_infinite_withcheck_stateful.env.c, c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--video--fbdev--core--fb.ko.cil.i, c/ldv-linux-4.0-rc1-mav/model/linux-4.0-rc1---drivers--video--fbdev--core--fb.ko_false-unreach-call.cil.env.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--gpu--drm--drm.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--infiniband--hw--cxgb4--iw_cxgb4.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--infiniband--hw--mlx5--mlx5_ib.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--video--fbdev--core--fb.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--infiniband--hw--mlx5--mlx5_ib.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/model/linux-4.2-rc1.tar.xz-08_1a-drivers--gpu--drm--drm.ko-entry_point_false-unreach-call.cil.out.env.c, c/ldv-linux-4.2-rc1/model/linux-4.2-rc1.tar.xz-08_1a-drivers--gpu--drm--i915--i915.ko-entry_point_true-unreach-call.cil.out.env.c, c/ldv-linux-4.2-rc1/model/linux-4.2-rc1.tar.xz-08_1a-drivers--infiniband--hw--cxgb4--iw_cxgb4.ko-entry_point_true-unreach-call.cil.out.env.c, c/ldv-linux-4.2-rc1/model/linux-4.2-rc1.tar.xz-08_1a-drivers--infiniband--hw--mlx5--mlx5_ib.ko-entry_point_true-unreach-call.cil.out.env.c, c/ldv-linux-4.2-rc1/model/linux-4.2-rc1.tar.xz-08_1a-drivers--video--fbdev--core--fb.ko-entry_point_true-unreach-call.cil.out.env.c, c/ldv-linux-4.2-rc1/model/linux-4.2-rc1.tar.xz-32_7a-drivers--gpu--drm--i915--i915.ko-entry_point_true-unreach-call.cil.out.env.c, c/ldv-linux-4.2-rc1/model/linux-4.2-rc1.tar.xz-32_7a-drivers--infiniband--hw--mlx5--mlx5_ib.ko-entry_point_true-unreach-call.cil.out.env.c
Removes one of the uses of external_alloc, which is implemented using
__VERIFIER_nondet_pointer. The type and size are known, so just allocate
memory using ldv_xmalloc, which also simplifies the implementation.
(see #767).
```
for f in c/ldv-*/model/*.c
do
perl -i -e \
'$p = 1;
while(<>) {
if(/^\/\/ Function: (vm_get_page_prot|pgprot_writecombine)\s*$/) {
$p = 2;
}
elsif($p == 2) {
if(/^void \*external_alloc\(void\);\s*$/) { next; }
elsif(/^void __VERIFIER_assume\(int\);\s*$/) { next; }
elsif(/^  struct pgprot \*tmp = \(struct pgprot\*\)external_alloc\(\);\s*$/) { next; }
elsif(/^  __VERIFIER_assume\(tmp != 0\);\s*$/) { next; }
elsif(/^  return \*tmp;\s*$/) {
print " …
```
=> Implement vm_get_page_prot, pgprot_writecombine using ldv_xmalloc

c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--staging--lustre--lnet--lnet--lnet.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--staging--lustre--lnet--selftest--lnet_selftest.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--staging--lustre--lnet--lnet--lnet.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--staging--lustre--lnet--selftest--lnet_selftest.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--staging--lustre--lustre--mdc--mdc.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--staging--lustre--lnet--lnet--lnet.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--staging--lustre--lnet--selftest--lnet_selftest.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--staging--lustre--lustre--llite--lustre.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--staging--lustre--lustre--osc--osc.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/model/linux-4.2-rc1.tar.xz-08_1a-drivers--staging--lustre--lnet--lnet--lnet.ko-entry_point_true-unreach-call.cil.out.env.c, c/ldv-linux-4.2-rc1/model/linux-4.2-rc1.tar.xz-08_1a-drivers--staging--lustre--lnet--selftest--lnet_selftest.ko-entry_point_true-unreach-call.cil.out.env.c, c/ldv-linux-4.2-rc1/model/linux-4.2-rc1.tar.xz-32_7a-drivers--staging--lustre--lnet--lnet--lnet.ko-entry_point_true-unreach-call.cil.out.env.c, c/ldv-linux-4.2-rc1/model/linux-4.2-rc1.tar.xz-32_7a-drivers--staging--lustre--lnet--selftest--lnet_selftest.ko-entry_point_true-unreach-call.cil.out.env.c, c/ldv-linux-4.2-rc1/model/linux-4.2-rc1.tar.xz-32_7a-drivers--staging--lustre--lustre--mdc--mdc.ko-entry_point_false-unreach-call.cil.out.env.c, c/ldv-linux-4.2-rc1/model/linux-4.2-rc1.tar.xz-43_2a-drivers--staging--lustre--lnet--lnet--lnet.ko-entry_point_true-unreach-call.cil.out.env.c, c/ldv-linux-4.2-rc1/model/linux-4.2-rc1.tar.xz-43_2a-drivers--staging--lustre--lnet--selftest--lnet_selftest.ko-entry_point_true-unreach-call.cil.out.env.c, c/ldv-linux-4.2-rc1/model/linux-4.2-rc1.tar.xz-43_2a-drivers--staging--lustre--lustre--llite--lustre.ko-entry_point_true-unreach-call.cil.out.env.c, c/ldv-linux-4.2-rc1/model/linux-4.2-rc1.tar.xz-43_2a-drivers--staging--lustre--lustre--osc--osc.ko-entry_point_true-unreach-call.cil.out.env.c
Implement cfs_block_{allsigs,sigsinv} using ldv_xmalloc.
Removes one of the uses of external_alloc, which is implemented using
__VERIFIER_nondet_pointer. The type and size are known, so just allocate
memory using ldv_xmalloc, which also simplifies the implementation.
(see #767).
```
for f in c/ldv-*/model/*.c
do
perl -i -e \
'$p = 1; $t = "";
while(<>) {
if(/^\/\/ Function: cfs_block_(allsigs|sigsinv)\s*$/) {
$p = 2;
}
elsif($p == 2) {
if(/^void \*external_alloc\(void\);\s*$/) { next; }
elsif(/^void __VERIFIER_assume\(int\);\s*$/) { next; }
elsif(/^  struct (__anonstruct_sigset_t_\d+) \*tmp = \(struct .*\*\)external_alloc\(\);\s*$/) { $t = $1; next; }
elsif(/^ …
```
=> Implement cfs_block_{allsigs,sigsinv} using ldv_xmalloc

c/verifythis/duplets.c, c/verifythis/elimination_max.c, c/verifythis/elimination_max_rec.c, c/verifythis/elimination_max_rec_onepoint.c, c/verifythis/lcp.c, c/verifythis/prefixsum_iter.c, c/verifythis/prefixsum_rec.c
The man page for calloc says: "The  calloc()  function  allocates memory
for  an array of nmemb elements of size bytes each and returns a pointer
to the allocated memory." It is not further specified what the behaviour
is when nmemb * size exceeds the maximum addressable storage. Thus guard
the call to calloc by an assumption that ensures that nmemb is strictly
less than 2^30 (this is a 32-bit category).
=> VerifyThis benchmarks: avoid overflow in calloc

c/bitvector/s3_clnt_1.BV.c.cil-1a.yml, c/bitvector/s3_clnt_1.BV.c.cil-2a.yml, c/bitvector/s3_srvr_1a_alt.BV.c.cil.yml
The two s3_clnt_1 tasks can result in an arithmetic overflow when
computing
```
s__s3__flags = (long )s__s3__flags - -5L;
```
as `s__s3__flags` has a non-deterministic value.
The s3_srvr_1a_alt task yields an overflow when computing
```
s__state = (ag_X * ag_Y) / ag_Z;
```
as both `ag_X` and `ag_y` have non-deterministic values.
=> bitvector/s3_{clnt_1,srvr_1a_alt}: Update overflow verdict

java/algorithms/BellmanFord-FunSat01.yml
As discussed in [PR-916](https://github.com/sosy-lab/sv-benchmarks/pull/916) this change had a race condition with changes done by @peterschrammel in 24e7400.
Hence, I want to revert this flag change
=> Revert label due to changes in 24e7400

c/list-ext-properties/list-ext_flag.c, c/list-ext-properties/list-ext_flag.i, c/list-ext-properties/list-ext_flag.yml
Removed double-free to contain only one memory violation
(i.e., invalid dereference). Removed unreach property from
list-ext_flag.yml since invalid dereference leads to
undefined behaviour.
=> Changed list-ext_flag to contain one memory violation

c/aws-c-common/aws_priority_queue_s_swap_harness.i, c/aws-c-common/makeall, c/aws-c-common/s_swap-fix.diff, c/check.py
This PR fixes the `aws_priority_queue_s_swap_harness.i` benchmark from `SoftwareSystems-AWS-C-Common-ReachSafety`. The benchmark does not have the implementation for the `__CPROVER_file_local_priority_queue_c_s_swap` function, which might lead to spurious verification results. The original version of this function is available at [s_swap_override_no_op.c](https://github.com/awslabs/aws-c-common/blob/0459e83c0d0c96f1506bda89b0c3eab80c4f11ab/.cbmc-batch/stubs/s_swap_override_no_op.c).
=> Implements __CPROVER_file_local_priority_queue_c_s_swap function

c/aws-c-common/aws_mul_size_saturating_harness.i, c/aws-c-common/makeall, c/aws-c-common/overflow-fix-1.diff, c/check.py
Fix #922 
In AWS C Common benchmarks, every time it checks for overflow in 32-bit operations, it uses the `__CPROVER_overflow_plus` or `__CPROVER_overflow_mul` functions. For instance, take a look at the following example:
```
static inline uint32_t aws_mul_u32_saturating(uint32_t a, uint32_t b) {
if (__CPROVER_overflow_mul(a, b))
return
(4294967295U)
;
return a * b;
}
```
However, there is only one version of `__CPROVER_overflow_mul`:
```
_Bool __CPROVER_overflow_mul(unsigned long a, unsigned long b) {
unsigned long c;
return __builtin_umull_overflow(a, b, &c);
}
```
Therefore, when we pass a `uint32_t` to the `__CPROVER_overflow_mul` function, it cast the `uint32_t` value to `unsigned long` and only then it performs the overflow check …
=> Check overflow with appropriate builtin functions

c/memsafety-ext3/freeAlloca.c
This file is part of MemSafety-Other category, which is 32-bit, so int should be used instead of long.
`clang -m32 freeAlloca.c` yields -Wincompatible-library-redeclaration in case unsigned long is used.
=> memsafety-ext3/freeAlloca.c: change long to int

c/aws-c-common/aws_array_list_front_harness.i, c/aws-c-common/aws_array_list_get_at_harness.i, c/aws-c-common/aws_array_list_get_at_ptr_harness.i, c/aws-c-common/aws_array_list_pop_front_harness.i, c/aws-c-common/aws_byte_buf_append_dynamic_harness.i, c/aws-c-common/aws_byte_buf_append_harness.i, c/aws-c-common/aws_hash_iter_delete_harness.i, c/aws-c-common/aws_linked_list_push_front_harness.i
The following benchmarks have non-explicit null-ness tests in assertions, which may lead to spurious results:
```
aws_array_list_front_harness.i
aws_array_list_get_at_harness.i
aws_array_list_get_at_ptr_harness.i
aws_array_list_pop_front_harness.i
aws_byte_buf_append_dynamic_harness.i
aws_byte_buf_append_harness.i
aws_hash_iter_delete_harness.i
aws_linked_list_push_front_harness.i
```
Therefore, this PR does `s/__VERIFIER_assert(ptr)/__VERIFIER_assert(ptr != ((void *)0))/g`
=> Make null-ness test explicit in AWS C Common benchmarks

java/java-ranger-regression/schedule_eqchk.yml, java/java-ranger-regression/schedule_eqchk/Main.java, java/java-ranger-regression/schedule_eqchk/Process.java, java/java-ranger-regression/schedule_eqchk/Queue.java, java/java-ranger-regression/schedule_eqchk/Schedule2.java, java/java-ranger-regression/schedule_eqchk/TestSchedule2.java
Adding an equivalence check on the Schedule benchmark and closing pull request #858 because it contains other unnecessary commits and I cant get git rebase to not include those commits. 
* the license for this benchmark is the same as the license used for other benchmarks already in the java-ranger-regression folder. This benchmark did not come with an original license file when it was distributed by Wang et al., the authors of the paper titled ``Dependence Guided Symbolic Execution'' which was published in the IEEE Transactions of Software Engineering Volume 43, Issue 3, March 1 2017 (https://doi.org/10.1109/TSE.2016.2584063). 
* this new benchmark would be in the java-ranger-regression folder which is present in ReachSafety.set
* assert.prp is the property file used
* schedule_eqchk.yml …
=> Adding an equivalence check on Schedule benchmark

c/ldv-commit-tester/m0_drivers-usb-gadget-g_printer-ko--106_1a--2b9ec6c-2.yml
Commit 17420e1f5089f422137226aff27657be5880ccb4 from #942 changed the verdict of at least one verification task ([ldv-commit-tester/m0_drivers-usb-gadget-g_printer-ko--106_1a--2b9ec6c-2.yml](https://github.com/sosy-lab/sv-benchmarks/blob/master/c/ldv-commit-tester/m0_drivers-usb-gadget-g_printer-ko--106_1a--2b9ec6c-2.yml)) from `false` to `true`.
Previously, there was this [counterexample trace](https://github.com/sosy-lab/sv-benchmarks/files/3878567/Counterexample.1.txt) ([shortened version](https://github.com/sosy-lab/sv-benchmarks/files/3878574/Counterexample.1.core.txt)):
- `main()` calls `init()`.
- `init()` [calls](https://github.com/sosy-lab/sv-benchmarks/blob/8b98491f2d70e9eeb94f6fb1b0882ad70d85f9f3/c/ldv-commit-tester/m0_drivers-usb-gadget-g_printer-ko--106_1a--2b9ec6c-2.i#L5319) …
=> Fix verdict of a ldv-commit-tester task after changes from #942

c/recursive-with-pointer/system-with-recursion.c, c/recursive-with-pointer/system-with-recursion.i, c/verifythis/prefixsum_rec.c
Fix invalid dereferences in two tasks that are not in memsafety category. See commit messages for more info.
=> Invalid deref fixes

c/termination-crafted/LexIndexValue-Pointer-3.c
Initialize allocated memory to nondeterministic values.
=> LexIndexValue-Pointer-3: properly initialize the allocated memory

c/termination-libowfat/strlcat.c, c/termination-libowfat/strlcpy.c
Reverts sosy-lab/sv-benchmarks#905
This revert is necessary because of the discussion in issue https://github.com/sosy-lab/sv-benchmarks/issues/934.
This PR fixes issue #934.
=> Revert "Change K&R-style declared functions to use the ANSI C syntax instead"

c/MemSafety-MemCleanup.set, c/verifythis/prefixsum_rec.yml
After PR #1014 there is no more memsafety/memcleanup violation (original error due to invalid dereference, if `n == 1` reported by esbmc in PR #923 by @mikhailramalho).
@mchalupa said:
> Fix invalid dereferences in two tasks that are not in memsafety category.
But `verifythis/prefixsum_rec.c` was/is (wrongly) in memcleanup category and pull request was incomplete. Now it should be in MemSafety-Arrays.
=> verifythis/prefixsum_rec.c: incorrectly labelled after PR #1014

c/aws-c-common/aws_priority_queue_s_remove_node_harness.i, c/aws-c-common/makeall, c/aws-c-common/s_remove_node-fix.diff, c/check.py
This PR fixes the `aws_priority_queue_s_remove_node_harness.i` benchmark from `SoftwareSystems-AWS-C-Common-ReachSafety`. The benchmark does not have the implementation for the `__CPROVER_file_local_priority_queue_c_s_remove_node` function, which might lead to spurious verification results. The original version of this function is available at [s_remove_node_override.c](https://github.com/awslabs/aws-c-common/blob/cd71284bab93835816ed02cd1d5f94e0f9e14067/.cbmc-batch/stubs/s_remove_node_override.c).
=> Implements __CPROVER_file_local_priority_queue_c_s_remove_node function

c/aws-c-common/aws_ring_buffer_acquire_harness.i, c/aws-c-common/aws_ring_buffer_acquire_up_to_harness.i, c/aws-c-common/makeall, c/aws-c-common/s_buf_belongs_to_pool-fix.diff, c/check.py
This PR fixes the `aws_ring_buffer_acquire_harness.i` and `aws_ring_buffer_acquire_up_to_harness.i` benchmarks from `SoftwareSystems-AWS-C-Common-ReachSafety`. The original implementation of the `s_buf_belongs_to_pool` function contains a code snippet for CBMC only:
```
static inline bool s_buf_belongs_to_pool(const struct aws_ring_buffer *ring_buffer, const struct aws_byte_buf *buf) {
#ifdef CBMC
/* only continue if buf points-into ring_buffer because comparison of pointers to different objects is undefined
* (C11 6.5.8) */
if ((__CPROVER_POINTER_OBJECT(buf->buffer) != __CPROVER_POINTER_OBJECT(ring_buffer->allocation)) ||
(__CPROVER_POINTER_OBJECT(buf->buffer) != __CPROVER_POINTER_OBJECT(ring_buffer->allocation_end))) {
return false;
} …
```
=> Removes unnecessary code snippet on s_buf_belongs_to_pool function

java/jayhorn-recursive/SatFibonacci01/Main.java, java/jayhorn-recursive/SatFibonacci02/Main.java, java/jayhorn-recursive/SatFibonacci03/Main.java, java/jbmc-regression/classtest1/Main.java
Non-public main methods don't comply with the rules and cannot be executed with `java`.
=> Fix invalid Java main methods

c/ldv-regression/rule57_ebda_blast.yml, c/ldv-regression/rule57_ebda_blast_2.i, c/ldv-regression/rule57_ebda_blast_2.yml
Due to the changes in 43eed055 and 05e736a7 the call of VERIFIER_nondet_pointer was removed.
According to SV-COMP rules all memory allocations suceed and do not return a null pointer.
This resulted in a pointer that is always valid, i.e. the underlying task was fixed by that change.
Now we need to fix the expected verdict.
=> change expected verdict of rule57_ebda_blast.

c/busybox-1.22.0/uudecode-2.c, c/busybox-1.22.0/uudecode-2.i
According to 6.5.16.1 of the C standard, types for assignment must be compatible.
According to that, for the affected line, the types are only compatible, if "both operands are pointers to qualified or unqualified versions of compatible types [...]".
Regarding the compatible types, 6.2.7 describes that "two types have compatible type if their types are the same", and  6.7.2 describes that `char`, `unsigned char` and `signed char` are not the same, but three distinct types.
I didn't find anything about that for GNU C, but gcc prints a warning for that line when compiling with `-Wall`.
=> Fix incompatible types in assignment

c/list-ext3-properties/sll_circular_traversal-1.c, c/list-ext3-properties/sll_circular_traversal-1.i
This problem is a follow-up of #979.
According to ISO-C99 6.2.4(2),
the value of a pointer becomes indeterminate when
the object it points to reaches the end of its lifetime.
There is also a nice blog post about that:
https://kristerw.blogspot.com/2016/03/c-pointers-are-not-hardware-pointers.html
For the task changed in 59606cd, the pointer itself is not even used in the `free` operation,
but only another pointer to the same object.
This makes it hard to understand the consequences of strict application of the C standard here.
We need to check for further tasks containing such a kind of undefined behaviour,
because it is quite common to write code like this in C and GCC/Clang happily compile the code,
even if the standard does not specify the behaviour for such cases.
I do not know …
=> fix comparison of freed pointer.

c/aws-c-common/aws_array_list_clean_up_harness.i, c/aws-c-common/aws_array_list_init_dynamic_harness.i, c/aws-c-common/aws_linked_list_node_reset_harness.i, c/aws-c-common/aws_linked_list_pop_back_harness.i, c/aws-c-common/aws_linked_list_pop_front_harness.i, c/aws-c-common/aws_linked_list_remove_harness.i, c/aws-c-common/aws_priority_queue_capacity_harness.i, c/aws-c-common/aws_priority_queue_clean_up_harness.i, c/aws-c-common/aws_priority_queue_init_dynamic_harness.i, c/aws-c-common/aws_priority_queue_init_static_harness.i, c/aws-c-common/aws_priority_queue_pop_harness.i, c/aws-c-common/aws_priority_queue_push_harness.i, c/aws-c-common/aws_priority_queue_push_ref_harness.i, c/aws-c-common/aws_priority_queue_remove_harness.i, c/aws-c-common/aws_priority_queue_s_remove_node_harness.i, c/aws-c-common/aws_priority_queue_s_sift_down_harness.i, c/aws-c-common/aws_priority_queue_s_sift_either_harness.i, c/aws-c-common/aws_priority_queue_s_sift_up_harness.i, c/aws-c-common/aws_priority_queue_s_swap_harness.i, c/aws-c-common/aws_priority_queue_size_harness.i, c/aws-c-common/aws_priority_queue_top_harness.i
Part of #1042.
The original code contains a strict-aliasing violation.
This removes the violating code and leaves only the loop
that iterates char-wise over the buffer (which is allowed).
This PR fixes the function in those tasks where it is syntactically
reachable. This is a subset of the fixes of #1044.
=> Fix code in aws_is_mem_zeroed of AWS-C-Common where reachable

c/aws-c-common/aws_array_eq_c_str_harness.i, c/aws-c-common/aws_array_list_capacity_harness.i, c/aws-c-common/aws_array_list_clean_up_harness.i, c/aws-c-common/aws_array_list_clear_harness.i, c/aws-c-common/aws_array_list_comparator_string_harness.i, c/aws-c-common/aws_array_list_init_dynamic_harness.i, c/aws-c-common/aws_array_list_init_static_harness.i, c/aws-c-common/aws_array_list_length_harness.i, c/aws-c-common/aws_array_list_sort_harness.i, c/aws-c-common/aws_array_list_swap_harness.i, c/aws-c-common/aws_byte_buf_eq_c_str_harness.i, c/aws-c-common/aws_byte_buf_from_c_str_harness.i, c/aws-c-common/aws_byte_buf_write_from_whole_string_harness.i, c/aws-c-common/aws_byte_buf_write_harness.i, c/aws-c-common/aws_byte_cursor_from_c_str_harness.i, c/aws-c-common/aws_hash_callback_c_str_eq_harness.i, c/aws-c-common/aws_is_power_of_two_harness.i, c/aws-c-common/aws_linked_list_node_reset_harness.i, c/aws-c-common/aws_linked_list_remove_harness.i, c/aws-c-common/aws_mul_size_checked_harness.i, c/aws-c-common/aws_mul_size_saturating_harness.i, c/aws-c-common/aws_priority_queue_init_dynamic_harness.i, c/aws-c-common/aws_round_up_to_power_of_two_harness.i, c/aws-c-common/aws_string_compare_harness.i, c/aws-c-common/aws_string_eq_byte_buf_harness.i, c/aws-c-common/aws_string_eq_byte_cursor_harness.i, c/aws-c-common/aws_string_eq_harness.i, c/aws-c-common/memset_override_0_harness.i
Part of #1043.
All these programs define some functions (at least abort)
that are also defined by the C standard,
but these identifiers are reserverd and so this is undefined
behavior.
This commit renames functions called "abort", "qsort", "memcpy",
"memmove", and "memset" if they have a body.
These were the only functions I found where this is necessary.
Checking which tasks are affected and the renaming was done
automatically, the code for this is in [`makeall`](https://github.com/sosy-lab/sv-benchmarks/pull/1047/files#diff-6e91d3085a54899adfa01a201ac91950) of #1047.
This PR is a subset of the fixes of #1047
where it is relevant for SV-COMP'20.
=> Rename functions that collide with the C standard in part of AWS-C-Common

c/aws-c-common/aws_byte_cursor_read-fix.diff, c/aws-c-common/aws_byte_cursor_read_be16_harness.i, c/aws-c-common/aws_byte_cursor_read_be32_harness.i, c/aws-c-common/aws_byte_cursor_read_be64_harness.i, c/aws-c-common/aws_byte_cursor_read_u8_harness.i, c/aws-c-common/makeall, c/check.py
The original benchmarks contain the following assumptions:
```
__CPROVER_assume(AWS_MEM_IS_WRITABLE(dest, 1));
```
see [aws_byte_cursor_read_u8_harness.c](https://github.com/awslabs/aws-c-common/blob/17e2a5a462da952795f2f564acfe83029c4f9375/.cbmc-batch/jobs/aws_byte_cursor_read_u8/aws_byte_cursor_read_u8_harness.c#L31).
The line was converted to:
```
__VERIFIER_assume(((((1)) == 0) || ((dest))));
```
This PR removes the unnecessary parts of the assumptions.
=> Fixes misconverted assumptions in aws_byte_cursor_read_* benchmarks

c/openbsd-6.2/if_etherip-double-free.c, c/openbsd-6.2/if_etherip-double-free.i, c/openbsd-6.2/if_etherip-fixed-double-free.c, c/openbsd-6.2/if_etherip-fixed-double-free.i, c/openbsd-6.2/sources/stubs/mbuf.c, c/openbsd-6.2/sources/stubs/sv_comp.h
These benchmarks declared functions malloc and free taking three arguments each,
as is done in the OpenBSD kernel. Rename those to openbsd_kernel_{malloc,free}
and make them wrappers around malloc/free. Furthermore define the previously
missing functions m_free, m_get, m_leadingspace.
After adding the necessary stubs to sources/stubs/*, `make modules` was
used, but only a subset of the resulting changes was committed to keep
the diff to a minimum.
=> openbsd-6.2/*: use compatible malloc, free, stub mbuf functions

.travis.yml
Travis build is triggered multiple times. The intention is that it is triggered only on a pull request.
Made changes to the `.travis.yml` file. Now testing that the travis build should trigger.
At the moment not to be considered for pulling into master.
=> Test travis build trigger

c/ldv-consumption/32_7a_cilled_linux-3.8-rc1-32_7a-drivers--net--wireless--ath--ath5k--ath5k.ko-ldv_main16_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-consumption/32_7a_cilled_linux-3.8-rc1-32_7a-drivers--net--wireless--ath--ath5k--ath5k.ko-ldv_main16_sequence_infinite_withcheck_stateful.cil.out.i
CBMC initially produced a counterexample as invalid pointers were being
passed to memcpy. Upon further review, various pointers declared in main
and passed to module functions required object allocation to avoid
invalid dereferences.
=> net--wireless--ath--ath5k--ath5k: allocate objects

c/ldv-commit-tester/m0_drivers-net-slip-ko--108_1a--1b0b0ac-1.c, c/ldv-commit-tester/m0_drivers-net-slip-ko--108_1a--1b0b0ac-1.i, c/ldv-commit-tester/m0_drivers-net-slip-ko--108_1a--1b0b0ac.c, c/ldv-commit-tester/m0_drivers-net-slip-ko--108_1a--1b0b0ac.i
CBMC produced a counterexample as an uninitialised pointer was being
passed to memcpy. The fix now stack-allocates several objects in main
rather than merely declaring pointers.
=> net-slip: allocate objects in main

c/ldv-commit-tester/m0_drivers-hwmon-ibmpex-ko--130_7a--d631323.c, c/ldv-commit-tester/m0_drivers-hwmon-ibmpex-ko--130_7a--d631323.i
CBMC reported a counterexample involving use of invalid pointers being
passed to memcpy. Allocate the objects involved, and do so by just
declaring them as local objects in main.
=> hwmon-ibmpex: stack-allocate objects passed to memcpy

c/ldv-linux-3.4-simple/43_1a_cilled_ok_nondet_linux-43_1a-drivers--w1--slaves--w1_ds2431.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/43_1a_cilled_ok_nondet_linux-43_1a-drivers--w1--slaves--w1_ds2431.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i
The character array are is used in a call to memcmp. CBMC produced
counterexamples for this benchmark as the use of memcmp with uninitialised
pointers is undefined behaviour.
=> linux-43_1a-drivers--w1--slaves--w1_ds2431: allocate char buffer

c/ldv-consumption/32_7a_cilled_linux-3.8-rc1-32_7a-drivers--staging--bcm--bcm_wimax.ko-ldv_main17_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-consumption/32_7a_cilled_linux-3.8-rc1-32_7a-drivers--staging--bcm--bcm_wimax.ko-ldv_main17_sequence_infinite_withcheck_stateful.cil.out.i, c/ldv-linux-3.4-simple/32_1_cilled_ok_nondet_linux-3.4-32_1-drivers--media--dvb--dvb-usb--dvb-usb-vp7045.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_ok_nondet_linux-3.4-32_1-drivers--media--dvb--dvb-usb--dvb-usb-vp7045.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i, c/ldv-linux-3.4-simple/43_1a_cilled_ok_nondet_linux-43_1a-drivers--usb--serial--usb_debug.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/43_1a_cilled_ok_nondet_linux-43_1a-drivers--usb--serial--usb_debug.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i
CBMC reports counterexamples as access to non-existent objects in memcmp
is undefined behaviour. Use local variables instead of pointers in main
to ensure the necessary var_group* objects exist.
=> LDV: stack-allocate var_group* as they are passed to memcmp

c/ldv-linux-3.4-simple/32_1_cilled_ok_nondet_linux-3.4-32_1-drivers--usb--serial--usb_debug.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_ok_nondet_linux-3.4-32_1-drivers--usb--serial--usb_debug.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i
The initial counterexample produced by CBMC involved var_group2, which
is passed to usb_debug_process_read_urb, where the underlying
(non-allocated) storage is accessed via memcmp. Just allocate it as a
local object.
=> linux-3.4-32_1-drivers--usb--serial--usb_debug: stack-allocate var_group2

c/ldv-linux-3.4-simple/32_1_cilled_ok_nondet_linux-3.4-32_1-drivers--platform--x86--topstar-laptop.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_ok_nondet_linux-3.4-32_1-drivers--platform--x86--topstar-laptop.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i
The initial counterexample produced by CBMC involved var_group1, which
is passed to acpi_topstar_add, where eventually a member of it is passed to
strcpy, and thus causing undefined behaviour.
=> linux-3.4-32_1-drivers--platform--x86--topstar-laptop: allocate var_group1 object

c/ldv-linux-3.4-simple/32_1_cilled_ok_nondet_linux-3.4-32_1-drivers--acpi--fan.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c, c/ldv-linux-3.4-simple/32_1_cilled_ok_nondet_linux-3.4-32_1-drivers--acpi--fan.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i
The initial counterexample produced by CBMC involved var_group1, which
is passed to acpi_fan_add, where eventually a member of it is passed to
strcpy, and thus causing undefined behaviour.
Further code review of this task revealed further var_group* variables
that are being dereferenced in functions invoked from main. Where
necessary, members are non-deterministically initialised.
=> linux-3.4-32_1-drivers--acpi--fan: allocate var_group* objects

c/ldv-commit-tester/m0_drivers-media-radio-si4713-i2c-ko--111_1a--064368f-1.c, c/ldv-commit-tester/m0_drivers-media-radio-si4713-i2c-ko--111_1a--064368f-1.i, c/ldv-commit-tester/m0_drivers-media-radio-si4713-i2c-ko--111_1a--064368f.c, c/ldv-commit-tester/m0_drivers-media-radio-si4713-i2c-ko--111_1a--064368f.i
The initial counterexample produced by CBMC involved var_group1, which
is passed to si4713_s_ext_ctrls, si4713_write_econtrol_string,
si4713_set_rds_ps_name, where eventually a member of it is passed to
strncpy, and thus causing undefined behaviour.
Further code review of this task revealed further var_group* variables
that are being dereferenced in functions invoked from main. Where
necessary, members are non-deterministically initialised.
=> m0_drivers-media-radio-si4713-i2c: allocate var_group* objects

c/array-memsafety/reverse_array_alloca_unsafe.c
Change `__VERIFIER_nondet_nt` to `__VERIFIER_nondet_int`.
=> array-memsafety/reverse_array_alloca_unsafe: Fix typo in function name

c/loops/insertion_sort-1.c, c/loops/insertion_sort-2.c
Value of v is used before being initialized causing an UB
```
int v[SIZE];   
for (j=1;j<SIZE;j++) {	  
key = v[j];
```
My suggestion is to initialize the array with nondeterministic values.
=> Fix undefined behaviour on c/loops/insertion_sort

c/loop-invariants/Makefile, c/loop-invariants/README, c/loop-invariants/linear-inequality-inv-a.c, c/loop-invariants/linear-inequality-inv-a.yml, c/loop-invariants/linear-inequality-inv-b.c, c/loop-invariants/linear-inequality-inv-b.yml
- Fixes outdates (and now wrong) documentation of tasks
- Add two new tasks
Reasoning for unchecked bullet points:
- Not sure if two tasks warrent creating a new directory. If this is preferable, please suggest a directory name.
- No preprocessing required.
Please review this pull request carefully; while I have contributed in the past, there seem to have been some changes to how things are done (yml, reach_error(), ...). I tried to comply but may have missed something.
=> New tasks from Witnesses journal paper

c/memsafety/20051113-1.c, c/memsafety/20051113-1.i
As per the C99 standard 6.5.6p8:
"If both the pointer operand and the result point to elements of the same array
object, or one past the last element of the array object, the evaluation shall
not produce an overflow; otherwise, the behavior is undefined."
This is only allowed for flexible array member, i.e. declared as zero-sized.
=> 20051113-1: Remove undefined behavior in C90-style structhack

c/check.py
Error-function `__VERIFIER_error` has been replaced with a defined method `reach_error` in e3f389a61aea5fc43e1d8380ef15cd405269f887.
Currently, the `check.py` script still checks for calls to function `__VERIFIER_error`, and thus creates a large set of false alarms.
To avoid this, apply the rename to `check.py`, as well.
=> Replace VERIFIER_error with reach_error in check.py

c/check.py
Currently, check.py takes quite some time to execute.
This PR halves the walltime of check.py by introducing multiprocessing.
This halves the walltime required by check.py on my machine.
(measured with runexec, walltime drops from ~100s to ~50s)
I understand that entries are sorted in the main method before checking. I assume this was done to get log results in the same order.
Deterministic output will of course be gone with this PR, but IMHO, the script's output is detailed enough to be fully understandable, even if not in lexicographic order.
In this PR, multiprocessing is applied on the directory level.
I also tested multiprocessing on the file level within each directory (within method `DirectoryChecks#run`).
This did not yield any further improvement on walltime.
Even if …
=> Speed-up check.py through multiprocessing

c/list-ext-properties/list-ext.yml, c/list-ext-properties/list-ext_2.c, c/list-ext-properties/list-ext_2.i, c/list-ext-properties/list-ext_2.yml
The original memory property violation was reached after iterating over the whole list (list
elements: 10x1, 10x2, 1x3) and then cleaning up the list elements with free.
The last loop condition "p->n!=0" could have dereferenced an invalid memory location in "p->n",
and this possibility was removed with #1052. As a consequence, the task is now memory-safe.
=> Change the expected verdict for task "list-ext.c".

c/pthread-driver-races/char_generic_nvram_nvram_llseek_nvram_unlocked_ioctl.i, c/pthread-driver-races/char_generic_nvram_nvram_llseek_read_nvram.i, c/pthread-driver-races/char_generic_nvram_nvram_llseek_write_nvram.i, c/pthread-driver-races/char_generic_nvram_nvram_unlocked_ioctl_write_nvram.i, c/pthread-driver-races/char_generic_nvram_read_nvram_nvram_unlocked_ioctl.i, c/pthread-driver-races/char_generic_nvram_read_nvram_write_nvram.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_change_pc8736x_gpio_configure.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_change_pc8736x_gpio_current.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_change_pc8736x_gpio_get.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_change_pc8736x_gpio_set.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_configure_pc8736x_gpio_current.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_configure_pc8736x_gpio_get.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_configure_pc8736x_gpio_set.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_current_pc8736x_gpio_get.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_current_pc8736x_gpio_set.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_get_pc8736x_gpio_set.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_change.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_configure.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_current.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_get.i, c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_set.i, c/pthread-driver-races/model/undef_funcs_generic_nvram.h, c/pthread-driver-races/model/undef_funcs_pc8736x_gpio.h
In d2bfcfc1599, not all preprocessed files received the latest version
of the changes to the svcomp.h header.
=> Fixup preprocessing of pthread-driver-races after d2bfcfc1599

README.md
PR #1112 reveals that option 'data_model' is only for 'C' programs.
=> Option 'data_model' is only for 'C' programs

c/NoDataRace-Main.cfg, c/NoDataRace-Main.set
This PR adds a first set file for the planned demo category on detecting data races.
There are already some tasks that were merged with https://github.com/sosy-lab/sv-benchmarks/pull/1107,
but of course we need more tasks, please contribute (and extend NoDataRace-Main.set to include your tasks)!
I also added a `cfg` file just to be consistent, but this will probably be deleted soon anyway now since we have #1111 merged.
=> Add .set and .cfg file for new (demo) category on data races

.gitlab-ci.yml, .travis.yml, java/.Dockerfile, java/check-compile.sh, java/compile.xml
Add a build script for the Docker image), so that we can update it via a schedule in GitLab.
Motivation: CI for Java uses an outdated BenchExec and thus, the CI fails for PR #1111. I would like to add a schedule to the CI that builds the Docker image weekly, and where I can press a button for a rebuild.
=> Add a build script for the Docker image

c/MemSafety-MemCleanup.set, c/memsafety/README.txt, c/memsafety/global-atexit-1.c, c/memsafety/global-atexit-1.i, c/memsafety/global-atexit-1.yml, c/memsafety/global-atexit-2.c, c/memsafety/global-atexit-2.i, c/memsafety/global-atexit-2a.yml, c/memsafety/global-atexit-2b.yml, c/memsafety/global-atexit-3.c, c/memsafety/global-atexit-3.i, c/memsafety/global-atexit-3.yml, c/memsafety/global-atexit.c, c/memsafety/global-atexit.i, c/memsafety/global-atexit.yml
Simple regression tests using atexit.
=> Adding test cases for MemSafety-Memcleanup

c/openbsd-6.2/if_etherip-double-free.c, c/openbsd-6.2/if_etherip-double-free.i, c/openbsd-6.2/if_etherip-fixed-double-free.c, c/openbsd-6.2/if_etherip-fixed-double-free.i
The introduction of reach_error() did not apply formatting otherwise
used in this directory. This results in `make modules` generating
additional (whitespace-only) changes.
The changes in this commit were obtained solely by running
```
make modules
```
in c/openbsd-6.2 with `clang-format` version 6.0.0.
The purpose of this whitespace-only commit is to reduce the size of
future changes to these benchmark tasks to a minimum (cf. #1152).
=> Whitespace changes only: Re-preprocess c/openbsd-6.2

c/openbsd-6.2/Makefile, c/openbsd-6.2/if_etherip-double-free.i, c/openbsd-6.2/if_etherip-fixed-double-free.i, c/openbsd-6.2/sources/stubs/stub.h, c/openbsd-6.2/sources/stubs/sv_comp.h, c/openbsd-6.2/sources/sys/machine/cpu_full.h
As discussed in the (virtual) community meeting on 2020-09-18,
unreach-call may be turned into plain assertion checking. As first step,
make the body of reach_error() `assert(0);`. For preprocessed files, the
result of assert(0) expansion is what we get on Ubuntu 18.04 with glibc
and GCC 7.5.0.
This change was previously made in 7341f59ba96, which did not properly handle
the case of reach_error not being defined in the main source file. This commit
now only handles openbsd-6.2 tasks, which define reach_error in a header file
and use files included in the repository for preprocessing. Other tasks will be
handled in a separate commit.
The changes were made in two commits: the first is manual work (diffstat: 4 files changed, 3 insertions(+), 6 deletions(-)), and the second commit is the …
=> c/openbsd-6.2: Insert assert(0) into the body of reach_error

c/diff_ci.sh
While the script worked correctly if a folder where things were changed
contains NO Makefile, it was broken in cases where it actually contained
a Makefile. Then no command was executed for that directory.
=> Fix diff_ci.sh, run CI on folders with Makefile

c/goblint-regression/28-race_reach_23-sound_unlock_racing.c, c/goblint-regression/28-race_reach_23-sound_unlock_racing.i, c/goblint-regression/28-race_reach_36-indirect_racefree.c, c/goblint-regression/28-race_reach_36-indirect_racefree.i, c/goblint-regression/28-race_reach_37-indirect_racing.c, c/goblint-regression/28-race_reach_37-indirect_racing.i, c/goblint-regression/28-race_reach_40-trylock_racing.c, c/goblint-regression/28-race_reach_40-trylock_racing.i, c/goblint-regression/28-race_reach_70-funloop_racefree.c, c/goblint-regression/28-race_reach_70-funloop_racefree.i, c/goblint-regression/28-race_reach_71-funloop_racing.c, c/goblint-regression/28-race_reach_71-funloop_racing.i, c/goblint-regression/28-race_reach_72-funloop_hard_racing.c, c/goblint-regression/28-race_reach_72-funloop_hard_racing.i, c/goblint-regression/28-race_reach_73-funloop_hard_racefree.c, c/goblint-regression/28-race_reach_73-funloop_hard_racefree.i, c/goblint-regression/28-race_reach_74-tricky_address1_racefree.c, c/goblint-regression/28-race_reach_74-tricky_address1_racefree.i, c/goblint-regression/28-race_reach_75-tricky_address2_racefree.c, c/goblint-regression/28-race_reach_75-tricky_address2_racefree.i, c/goblint-regression/28-race_reach_76-tricky_address3_racefree.c, c/goblint-regression/28-race_reach_76-tricky_address3_racefree.i, c/goblint-regression/28-race_reach_77-tricky_address4_racing.c, c/goblint-regression/28-race_reach_77-tricky_address4_racing.i, c/goblint-regression/28-race_reach_78-equ_racing.c, c/goblint-regression/28-race_reach_78-equ_racing.i, c/goblint-regression/28-race_reach_79-equ_racefree.c, c/goblint-regression/28-race_reach_79-equ_racefree.i
In #1164 some issues were revealed and fixed. Since the already merged races-as-reachability benchmarks (#1168) in part overlap, these fixes are also ported here:
1. Make mutex initialization explicit to avoid possible undefined behavior.
2. Fix lock-unlock copy-paste mistakes.
3. Fix unlocking not-locked mutex undefined behavior using `ERRORCHECK` mutex type.
=> Port undefined behavior fixes from #1164 to goblint-regression races-as-reachability benchmarks

c/array-cav19/array_tiling_poly6.c, c/array-cav19/array_tiling_tcpy.c
Added the fixes for integer overflow issues raised in #1173, for the benchmarks submitted in PR #835
=> Fixes for Integer Overflows

c/diff_ci.sh
This PR adds "-s" flag to the cut command.
without this flag the changes if the dir `c` is found in the diff it will be included.
This is causing the script to hang later.
e.g., in the PR #1099 the file `Makefile-detect-compiler.c` was changed and this put the directory `c` to be in the list of directories to be built. We don't build this directory. We iteratively build the directories in `c`
=> fix diff build

c/aws-c-common/aws_array_eq_c_str_harness.i, c/aws-c-common/aws_array_eq_c_str_ignore_case_harness.i, c/aws-c-common/aws_array_eq_harness.i, c/aws-c-common/aws_array_eq_ignore_case_harness.i, c/aws-c-common/aws_byte_buf_cat_harness.i, c/aws-c-common/aws_byte_buf_eq_c_str_harness.i, c/aws-c-common/aws_byte_buf_eq_c_str_ignore_case_harness.i, c/aws-c-common/aws_byte_buf_eq_harness.i, c/aws-c-common/aws_byte_buf_eq_ignore_case_harness.i, c/aws-c-common/aws_byte_cursor_compare_lexical_harness.i, c/aws-c-common/aws_byte_cursor_compare_lookup_harness.i, c/aws-c-common/aws_byte_cursor_eq_byte_buf_harness.i, c/aws-c-common/aws_byte_cursor_eq_byte_buf_ignore_case_harness.i, c/aws-c-common/aws_byte_cursor_eq_c_str_harness.i, c/aws-c-common/aws_byte_cursor_eq_c_str_ignore_case_harness.i, c/aws-c-common/aws_byte_cursor_eq_harness.i, c/aws-c-common/aws_byte_cursor_eq_ignore_case_harness.i, c/aws-c-common/aws_hash_callback_c_str_eq_harness.i, c/aws-c-common/aws_hash_callback_string_eq_harness.i
I renamed the existing definition into memcmp_safe
to match its intentions. Then, this safe definition
invoked the standard memcmp.
=> Cleaned up definitions of memcmp function

c/check.py
This is a quite small PR: just a few chars are added.
An empty dirname crashes the script. The fix uses '.' instead of empty string ''.
=> fix crash of check-script when called with `python3 check.py`.

c/SoftwareSystems-DeviceDriversLinux64Large-ReachSafety.set
The file was created with redundant lines in 2acda1c0b076d6ea322d1f70f4436bf3bf5be47a .
I do not know whether this is a bug in the set file or the intention was something else.
What was the criteria to select large benchmarks? Maybe that went wrong.
=> removing redundant/repeated lines from set file.

.reuse/dep5
It was recently added but still has the old License.txt
Fixes current CI after #1171 was merged without REUSE-style headers.
=> Add uthash to list of directories without license headers

c/SoftwareSystems-uthash-MemSafety.set, c/SoftwareSystems-uthash-NoOverflows.set, c/SoftwareSystems-uthash-ReachSafety.set
I overlooked this mistake when reviewing.
=> Fix wrong reference to the software system BusyBox

c/MemSafety-Juliet.set, c/Unused_Juliet.set
Many CWE IDs of the preprocessed files in Juliet_Test folder can not be mapped on our MemSafety property.
This PR restricts the MemSafety-Juliet.set to two CWEs:
- CWE415_Double_Free
- CWE476_NULL_Pointer_Dereference
The PR includes 668 Juliet Tasks.
=> Shrink Juliet MemSafety integration

c/nla-digbench/divbin.yml, c/nla-digbench/divbin2.yml, c/nla-digbench/freire1.yml, c/nla-digbench/freire2.yml, c/nla-digbench/knuth.yml, c/nla-digbench/lcm1.yml, c/nla-digbench/lcm2.yml, c/nla-digbench/mannadiv.yml
#1155 fixed several overflows and added the corresponding expected behaviour for the modified files.
However the files that were not modified (because they did not have overflows) did not get an expected behaviour for `no-overflow`.
This PR adds those expected behaviours.
=> Added missing expected result for no-overflow property

c/MemSafety-Juliet.set
There are more Tasks which CWE IDs might not match our MemSafety property, but the tasks preprocessed 'good' (without bugs) 'bad '(with bugs) seems to match.
This PR adds subsets of tasks of different CWE IDs to the MemSafety-Juliet.set and adds about 2200 new tasks. 
This is a follow up PR of #1193
=> Re-add more juliet tasks

c/aws-c-common/aws_array_eq_c_str_harness-1.i, c/aws-c-common/aws_array_eq_c_str_harness-1.yml
Seeded what I think is a reasonable bug into this benchmark to create some benchmarks with bugs in this category.
It is a first step towards doing #1183.
If people are reasonably happy with this one, I'll do more.
=> Seeded an off-by-one bug

c/Unused_Juliet.set
In PR #1194 several Juliet tasks were included into memory safety category but not removed from the Unused_Juliet.set file.
This PR removes those tasks which are now included into memory safety category.
=> Remove used Juliet tasks from Unused_Juliet.set

c/ldv-races/race-2_2-container_of.c, c/ldv-races/race-2_2-container_of.i, c/ldv-races/race-2_5-container_of.c, c/ldv-races/race-2_5-container_of.i
Changes made by me in #1157 and #1177 changed the semantics of two benchmarks which changed the result of the verification.
In both cases the problem was the same. The original code
```
data->shared.a = 1;
data->shared.b = data->shared.b + 1;
```
was changed to 
```
__VERIFIER_atomic_begin();
data->shared.a = 1;
__VERIFIER_atomic_end();
__VERIFIER_atomic_begin();
data->shared.b = data->shared.b + 1;
__VERIFIER_atomic_end();
```
This clearly changes the semantics of the program since in the original case there can be a context switch between the read and the write of `data->shared.b`. This is not possible in the benchmarks after my changes.
This PR fix these while still providing a solution for the data races (which was the intention of #1157 and #1177).
=> Restore original benchmark semantics

c/aws-c-common/aws_array_eq_harness-1.i, c/aws-c-common/aws_array_eq_harness-1.yml, c/aws-c-common/aws_byte_buf_from_c_str_harness-1.i, c/aws-c-common/aws_byte_buf_from_c_str_harness-1.yml, c/aws-c-common/aws_byte_buf_write_from_whole_buffer_harness-1.i, c/aws-c-common/aws_byte_buf_write_from_whole_buffer_harness-1.yml, c/aws-c-common/aws_hash_iter_begin_harness-1.i, c/aws-c-common/aws_hash_iter_begin_harness-1.yml, c/aws-c-common/aws_linked_list_node_reset_harness-1.i, c/aws-c-common/aws_linked_list_node_reset_harness-1.yml, c/aws-c-common/aws_priority_queue_init_dynamic_harness-1.i, c/aws-c-common/aws_priority_queue_init_dynamic_harness-1.yml
I am moving slowly since I am doing it manually.
Here are more seeded bugs that are addressing #1183.
=> Seed more aws bugs

java/juliet-java/CWE369_Divided_by_Zero__float_connect_tcp_divide_81a_good.yml
This file originates from the good part of the original benchmark. In this example, there is no assertion violation expected. I made a mistake here.
=> Update the verdict for the good task

c/aws-c-common/aws_string_eq_byte_buf_harness.i, c/aws-c-common/aws_string_new_from_array_harness.i
This commit avoids the situation where size of 0 can be
passed to malloc. I think it does not alter the spirit
of the benchmark.
This is related to the unresolved mailing list discussion with the subject line "Can malloc return 0 when 0 is passed as size?".
As I wrote there, if we assume that malloc(0) can return NULL, which C standard allows, then these two benchmarks have an interesting (in my opinion) corner case bug. However, since we have not resolved the discussion, and in my opinion the current SVCOMP spec for malloc does not adequately cover this corner case, I am disabling 0 being passed to malloc.
If we decide that malloc(0) can return NULL, I will create buggy versions of these benchmarks.
=> Passing size of 0 to malloc leads to assertion violation

c/busybox-1.22.0/busybox_sv_comp-getlogin_r.h, c/busybox-1.22.0/logname-1.i, c/busybox-1.22.0/logname-2.i
getlogin_r model in busybox benchmarks uses an uninitialized loop counter which leads to undefined behavior. This PR fixes the model and files where it is used.
=> busybox: initialize a variable in getlogin_r model

c/openbsd-6.2/if_etherip-fixed-double-free-invalid-deref1.c, c/openbsd-6.2/if_etherip-fixed-double-free-invalid-deref1.i, c/openbsd-6.2/if_etherip-fixed-double-free-invalid-deref1.yml, c/openbsd-6.2/if_etherip-fixed-double-free-invalid-deref2.c, c/openbsd-6.2/if_etherip-fixed-double-free-invalid-deref2.i, c/openbsd-6.2/if_etherip-fixed-double-free-invalid-deref2.yml, c/openbsd-6.2/if_etherip-fixed-double-free.c
1) ipcounters global variable is not initialized and therefore is null
when accessed in counters_inc() (called from main -> ip_deliver -> ipstat_inc ->
counters_inc).
2) ip_deliver() is called from main with nxt = 0 and af = AF_INET6,
which causes to take the 0th element of inet6sw (line 631) which has
pr_input set to null. Then this null is dereferenced on line 634.
Both invalid dereferences may be hit if you replace the nondet values with the following concrete values:
```diff
diff --git a/c/openbsd-6.2/if_etherip-fixed-double-free.i b/c/openbsd-6.2/if_etherip-fixed-double-free.i
index 93be21b267..fd164a049b 100644
--- a/c/openbsd-6.2/if_etherip-fixed-double-free.i
+++ b/c/openbsd-6.2/if_etherip-fixed-double-free.i
@@ -407,7 +407,7 @@ void assume_abort_if_not(int cond) {
abort();
}
} …
```
=> Fix two invalid dereferences in if_etherip-fixed-double-free

c/goblint-regression/04-mutex_19-call_by_ptr_rc.c, c/goblint-regression/04-mutex_19-call_by_ptr_rc.i, c/goblint-regression/04-mutex_19-call_by_ptr_rc.yml, c/goblint-regression/28-race_reach_19-callback_racing.c, c/goblint-regression/28-race_reach_19-callback_racing.i, c/goblint-regression/28-race_reach_20-callback_racefree.c, c/goblint-regression/28-race_reach_20-callback_racefree.i
Closes #1225.
This PR replaces the use of `extern` function `ftw` with a normal function that non-deterministically calls the function pointer given to it.
=> Replace extern ftw function with mock implementation in goblint-regression

c/ldv-commit-tester/m0_drivers-media-radio-si4713-i2c-ko--111_1a--064368f-1.c, c/ldv-commit-tester/m0_drivers-media-radio-si4713-i2c-ko--111_1a--064368f-1.i, c/ldv-commit-tester/m0_drivers-media-radio-si4713-i2c-ko--111_1a--064368f.c, c/ldv-commit-tester/m0_drivers-media-radio-si4713-i2c-ko--111_1a--064368f.i, c/ldv-commit-tester/m0_drivers-scsi-gdth-ko--111_1a--5934df9-1.c, c/ldv-commit-tester/m0_drivers-scsi-gdth-ko--111_1a--5934df9-1.i, c/ldv-commit-tester/m0_sound-oss-opl3-ko--111_1a--42f9f8d-1.c, c/ldv-commit-tester/m0_sound-oss-opl3-ko--111_1a--42f9f8d-1.i, c/ldv-commit-tester/m0_sound-oss-opl3-ko--111_1a--42f9f8d.c, c/ldv-commit-tester/m0_sound-oss-opl3-ko--111_1a--42f9f8d.i, c/ldv-validator-v0.6/linux-stable-064368f-1-111_1a-drivers--media--radio--si4713-i2c.ko-entry_point.cil.out.c, c/ldv-validator-v0.6/linux-stable-064368f-1-111_1a-drivers--media--radio--si4713-i2c.ko-entry_point.cil.out.i, c/ldv-validator-v0.6/linux-stable-42f9f8d-1-111_1a-sound--oss--opl3.ko-entry_point.cil.out.c, c/ldv-validator-v0.6/linux-stable-42f9f8d-1-111_1a-sound--oss--opl3.ko-entry_point.cil.out.i, c/ldv-validator-v0.6/linux-stable-5934df9-1-111_1a-drivers--scsi--gdth.ko-entry_point.cil.out.c, c/ldv-validator-v0.6/linux-stable-5934df9-1-111_1a-drivers--scsi--gdth.ko-entry_point.cil.out.i, c/ldv-validator-v0.8/linux-stable-064368f-1-111_1a-drivers--media--radio--si4713-i2c.ko-entry_point_ldv-val-v0.8.cil.out.c, c/ldv-validator-v0.8/linux-stable-064368f-1-111_1a-drivers--media--radio--si4713-i2c.ko-entry_point_ldv-val-v0.8.cil.out.i, c/ldv-validator-v0.8/linux-stable-42f9f8d-1-111_1a-sound--oss--opl3.ko-entry_point_ldv-val-v0.8.cil.out.c, c/ldv-validator-v0.8/linux-stable-42f9f8d-1-111_1a-sound--oss--opl3.ko-entry_point_ldv-val-v0.8.cil.out.i, c/ldv-validator-v0.8/linux-stable-5934df9-1-111_1a-drivers--scsi--gdth.ko-entry_point_ldv-val-v0.8.cil.out.c, c/ldv-validator-v0.8/linux-stable-5934df9-1-111_1a-drivers--scsi--gdth.ko-entry_point_ldv-val-v0.8.cil.out.i, c/ldv-validator-v0.8/linux-stable-8817633-1-144_2a-drivers--staging--media--easycap--easycap.ko-entry_point_ldv-val-v0.8.cil.out.c, c/ldv-validator-v0.8/linux-stable-8817633-1-144_2a-drivers--staging--media--easycap--easycap.ko-entry_point_ldv-val-v0.8.cil.out.i
Several benchmarks provide custom definitions for these functions,
which causes name clashes with standard definitions. This commit
fixed that by renaming them by prefixing them with ldv_.
=> Added ldv_ prefix to strlen and strerror function definitions

c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_calloc_45_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_calloc_68_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_malloc_45_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_malloc_68_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_realloc_45_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_realloc_68_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_calloc_45_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_calloc_68_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_malloc_45_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_malloc_68_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_realloc_45_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_realloc_68_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_calloc_45_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_calloc_68_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_malloc_45_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_malloc_68_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_realloc_45_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_realloc_68_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_calloc_45_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_calloc_68_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_malloc_45_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_malloc_68_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_realloc_45_bad.yml, c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_realloc_68_bad.yml
Those tasks all contain the same behaviour:
They allocate some memory and store a reference to it
in a global static variable `CWE401_Memory_Leak__TASKNAME_badData`
that is never freed and remains reachable beyond the exit of the main function.
Found by CPAchecker (SMG analysis).
=> change labelling for some Juliet tasks.

c/aws-c-common/aws_byte_cursor_read_be16_harness.i, c/aws-c-common/aws_byte_cursor_read_be32_harness.i, c/aws-c-common/aws_byte_cursor_read_be64_harness.i, c/aws-c-common/aws_byte_cursor_read_u8_harness.i
These benchmarks were not memory safe as the assumptions to constrain
the allocation size were missing or non-sensical.
=> aws-c-common: ensure allocation of sufficient size

c/nla-digbench-scaling/divbin_unwindbound10.yml, c/nla-digbench-scaling/divbin_unwindbound100.yml, c/nla-digbench-scaling/divbin_unwindbound20.yml, c/nla-digbench-scaling/divbin_unwindbound50.yml, c/nla-digbench-scaling/generate.py
This fixes issue #1238 by updating the task generation script.
We do not add "fixed" versions of the tasks since these are derived, bounded versions of the tasks in `nla-digbench`.  
There are already bounded versions of this task anyway where the verdict is `true(unreach-call)` (plus the original unbounded version in `nla-digbench`), so this should be covered.
Thanks to @mchalupa for finding this issue.
=> Fix verdicts for bounded divbin tasks

c/nla-digbench-scaling/freire1_valuebound1.yml, c/nla-digbench-scaling/freire1_valuebound10.yml, c/nla-digbench-scaling/freire1_valuebound100.yml, c/nla-digbench-scaling/freire1_valuebound2.yml, c/nla-digbench-scaling/freire1_valuebound20.yml, c/nla-digbench-scaling/freire1_valuebound5.yml, c/nla-digbench-scaling/freire1_valuebound50.yml, c/nla-digbench-scaling/generate.py
The assertion in these tasks checks that,
for int r and double a,
r^2 - r - a + 2 * (a / 2 - sum(range(0, r))) == 0
(for range-end exclusive)
If there's no imprecisions due to floating-point arithmetics,
this equality is correct.
In the value-bounded tasks, a is restricted to 0 <= a <= 100.
In this value-range, no imprecision is introduced.
Thus, the tasks fulfill property unreach-call.
This PR adjusts the verdicts to match that expectation.
=> Fix verdict of value-bounded freire1 tasks to 'true'

c/busybox-1.22.0/mkdir-2.yml, c/busybox-1.22.0/seq-1.yml, c/busybox-1.22.0/touch-2.yml
This fixes issue #1246. I also added the C files of the relabelled benchmarks into the `todo` directory that was created in the past to keep track of benchmarks that we would like to fix in the future. However, I can remove that commit if it is not desirable.
=> MemSafety: fix labelling of three busybox benchmarks

c/aws-c-common/aws_priority_queue_s_sift_down_harness.i
This pull request initializes two local variables to avoid undefined behaviors that
happen because the subsequent code is accessing them without initializing
them.
=> Initializing local variables to fix undefined behaviors

c/busybox-1.22.0/date-1.yml
I didn't know how to fix the issue on all paths, so I relabelled the benchmark to false(def-behavior).
Fixes #1250.
=> busybox date-1: label as undefined

c/aws-c-common/memcpy_using_uint64_harness.i, c/aws-c-common/memset_override_0_harness.i, c/aws-c-common/memset_using_uint64_harness.i
There are a few cases of uninitialized local variables being used (i.e., undefined behavior) in the three `c/aws-c-common/mem*.i` programs (several ints and one array). This adds proper nondeterministic initialization with calls to `__VERIFIER_nondet_*` (in a loop for the array).
=> Properly initialize local variables in c/aws-c-common/mem*.i

c/termination-recursive-malloc/chunk3.c, c/termination-recursive-malloc/chunk3.i
The two pointers that were being passed to `free` hold the same value on
all execution paths, thus 1) resulting in a double-free and 2) making
the fix as simple as removing the second call to `free`.
Fixes: #1257
=> termination-recursive-malloc/chunk3.c: remove double free

c/seq-mthreaded/pals_floodmax.4.2.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_floodmax.4.3.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_floodmax.4_overflow.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_floodmax.5.2.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_floodmax.5_overflow.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_lcr.6_overflow.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_lcr.7_overflow.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_lcr.8_overflow.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_opt-floodmax.4.2.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_opt-floodmax.4.3.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_opt-floodmax.4_overflow.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_opt-floodmax.5.2.ufo.UNBOUNDED.pals.yml, c/seq-mthreaded/pals_opt-floodmax.5_overflow.ufo.UNBOUNDED.pals.yml
The previous verdicts were introduced in #786 without any evidence. CBMC
reports these tasks to be terminating, see
https://sv-comp.sosy-lab.org/2021/results/results-verified/cbmc.2020-12-05_12-30-28.results.SV-COMP21_termination.Termination-Other.xml.bz2.merged.xml.bz2.table.html#/table?filter=0(0*status*(category(in(wrong)))).
Fixes: #1259
=> Fix termination verdicts in seq-mthreaded

c/ldv-linux-3.0/module_get_put-drivers-gpu-drm-i915-i915.ko.cil.out.c, c/ldv-linux-3.0/module_get_put-drivers-gpu-drm-i915-i915.ko.cil.out.i
The pointer var_group3 is eventually passed to `kfree`, and thus needs
to point to heap-allocated memory to avoid memory safety issues. See
also #1270.
=> ldv-linux-3.0/module_get_put-drivers-gpu-drm-i915-i915.ko.cil.out: allocate memory

c/aws-c-common/aws_byte_buf_write_from_whole_buffer_harness-1.i, c/aws-c-common/aws_priority_queue_init_dynamic_harness-1.i
=> aws: initialize variables in two aws benchmarks

c/loops/linear_sea.ch.c, c/loops/linear_search.c
See issue #1241 for previous discussion, which didn't get the attention it deserves.
As discussed in #1241, reading `malloc`-ed memory without initializing it first is possibly undefined behavior, depending on whether to follow the C standard or the GCC implementation. [It was also pointed out](https://github.com/sosy-lab/sv-benchmarks/issues/1241#issuecomment-734003163) that there exists precedent for handling it here either way. Clearly there is a lack of consensus in this regard. Since this affects SV-COMP more widely than just these two tasks, it would be great to hear more opinions in the issue and hopefully this PR brings more peoples' attention to it.
This PR adds explicit `malloc` array initialization to these tasks, avoiding the problem altogether. I believe this change should be …
=> Fix possible undefined behavior and intent of loops/linear_search and loops/linear_sea.ch

c/ntdrivers/parport.i.cil-2.c
The task eventually tries to access the memory pointed to by
`irp.Tail.Overlay.__annonCompField17.__annonCompField16.CurrentStackLocation->Parameters.FilterResourceRequirements.IoResourceRequirementList`.
This member was never initialised, and could thus point anywhere.
Fixes: #1269
=> Add missing initialisation in ntdrivers/parport.i.cil-2

c/ntdrivers/diskperf.i.cil-1.c
In line 3368, the same member was already initialised via a call to
`malloc`. Resetting it to `NULL` results in memory safety errors at a
later point.
Fixes: #1266
=> ntdrivers/diskperf.i.cil-1: remove duplicate initialisation

c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--media--usb--dvb-usb--dvb-usb-opera.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--media--usb--dvb-usb--dvb-usb-opera.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--misc--sgi-gru--gru.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--misc--sgi-gru--gru.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--net--wireless--prism54--prism54.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--net--wireless--prism54--prism54.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--media--usb--s2255--s2255drv.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--media--usb--s2255--s2255drv.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--wireless--prism54--prism54.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--net--wireless--prism54--prism54.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--usb--serial--digi_acceleport.ko-entry_point.cil.out.c, c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--usb--serial--digi_acceleport.ko-entry_point.cil.out.i, c/ldv-linux-4.2-rc1/todo/linux-4.2-rc1.tar.xz-43_2a-drivers--net--appletalk--ipddp.ko-entry_point_true-unreach-call.cil.out.c, c/ldv-linux-4.2-rc1/todo/linux-4.2-rc1.tar.xz-43_2a-drivers--net--appletalk--ipddp.ko-entry_point_true-unreach-call.cil.out.i, c/ntdrivers/diskperf.i.cil-1.c, c/ntdrivers/floppy.i.cil-3.c, c/ntdrivers/floppy2.i.cil.c, c/ntdrivers/parport.i.cil-2.c
Comparing pointers pointing to distinct objects is undefined behaviour.
Instead, perform the comparison over integers, which is
implementation-defined behaviour.
This fix also contributes to addressing #1266, but several more tasks have this problem. Thus I instead opted to fix it for all of them.
=> Do not perform pointer comparison over distinct objects

c/xcsp/README.md
Licenses are stored as SPDX, and the license files referenced doesn't exist anymore.
=> Remove dead link from XCSP Readme

.gitlab-ci.yml
This PR adds a Gitlab-CI check for links referenced in Markdown files.
It uses the tool [markdown-link-check](https://github.com/tcort/markdown-link-check) and its official Docker image for this.
Example output of the CI check: https://gitlab.com/lemberger/sv-benchmarks/-/jobs/1046665217
=> Add CI job that checks links in all markdown files of the repository

README.md
The two commits in this PR seem to have been pushed directly to the repository mirror on gitlab.com on 2021-01-29. Parts of these improvements have also been pushed to GitHub a few minutes later with 3d1593c549f1983370cf88c51b5a4743c8dcc479, but not everything.
=> Adjust some links to https

c/SoftwareSystems-BusyBox-ReachSafety.set
There are tasks with property unreach-call that are not yet included in the benchmark set.
The CI script for the benchmark definitions has identified this issue:
https://gitlab.com/sosy-lab/sv-comp/bench-defs/-/jobs/1624885676
Example for missing task: https://github.com/sosy-lab/sv-benchmarks/blob/master/c/busybox-1.22.0/cut-3.yml
=> Add missing tasks to a category
